variables:
  RELEASE_VERSION: "1.0.0"

stages:
  - build

image: node:22

build_extension:
  stage: build
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.rnd.mendix.com/innovation-incubation/agent-editor.git temp_repo
    - cd temp_repo
    - npm ci
    - npm run build
    - cd ..
    - rm -rf temp_repo
  artifacts:
    paths:
      - temp_repo/dist/  # Adjust based on your build output directory
    expire_in: 1 hour

