include:
  - project: innovation-incubation/genai-components/genai-pipeline-templates
    ref: $REF_BRANCH
    file: scan.yml
    rules:
      - if: '$CI_PIPELINE_SOURCE =~ /^(trigger|web)$/ && $TYPE != null && $TYPE != "" && $FIX_VERSION != null && $FIX_VERSION != ""'
        when: never
      - if: '$CI_PIPELINE_SOURCE =~ /^(trigger|web|pipeline)$/ && (($TYPE == null || $TYPE == "") && ($FIX_VERSION == null || $FIX_VERSION == ""))'
        when: always
      - if: $CI_COMMIT_BRANCH
        when: always
      - when: never

  - project: innovation-incubation/genai-components/genai-pipeline-templates
    ref: $REF_BRANCH
    file: release.yml
    rules:
      - if: '$CI_PIPELINE_SOURCE =~ /^(trigger|web)$/ && ($TYPE == null || $TYPE == "" || $FIX_VERSION == null || $FIX_VERSION == "")'
        when: never
      - if: '$CI_PIPELINE_SOURCE =~ /^(trigger|web)$/ && $TYPE != null && $TYPE != "" && $FIX_VERSION != null && $FIX_VERSION != ""'
        when: always
      - when: never
  
workflow:  
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /^(trigger|web|pipeline)$/'
      when: always
    - if: '$CI_COMMIT_BRANCH'
      when: always
    - when: never