// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import static java.util.Objects.requireNonNull;
import java.util.HashMap;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazons3connector.impl.AmazonS3Client;
import amazons3connector.impl.MxLogger;
import amazons3connector.proxies.S3RequestMetaData;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.CopyObjectRequest.Builder;
import java.util.List;
import java.util.Map;
import com.mendix.systemwideinterfaces.core.UserAction;

public class CopyObject extends UserAction<java.lang.Boolean>
{
	/** @deprecated use CopyObjectRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CopyObjectRequest;
	private final amazons3connector.proxies.CopyObjectRequest CopyObjectRequest;
	private final awsauthentication.proxies.ENUM_Region Region;
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;

	public CopyObject(
		IContext context,
		IMendixObject _copyObjectRequest,
		java.lang.String _region,
		IMendixObject _credentials
	)
	{
		super(context);
		this.__CopyObjectRequest = _copyObjectRequest;
		this.CopyObjectRequest = _copyObjectRequest == null ? null : amazons3connector.proxies.CopyObjectRequest.initialize(getContext(), _copyObjectRequest);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		software.amazon.awssdk.services.s3.model.CopyObjectResponse awsResponse = null;
		try {
			//Validation of input parameters
			requireNonNull(this.Credentials, "AWS Credentials are required.");
			requireNonNull(this.Region, "AWS Region is required.");
			requireNonNull(this.CopyObjectRequest, "CopyObjectRequest is required.");
			
			//Validation of the CopyObjectRequest object
			validateRequest();
			
			// Building the Java CopyObjectRequest
			software.amazon.awssdk.services.s3.model.CopyObjectRequest awsRequest = createAWSRequest();
			// Logging of the request building
			LOGGER.debug("AWS request:", awsRequest);
			// Client creation
			S3Client client = AmazonS3Client.getS3Client(Credentials, Region, CopyObjectRequest);
			// Invoke action on AWS client
			awsResponse = client.copyObject(awsRequest);
						
			// Log the response
			LOGGER.debug("AWS response:", awsResponse);			
			}
			catch (Exception e) {
				LOGGER.error(e.getMessage());
				throw e;
			}
			// Determine return value
			return awsResponse.sdkHttpResponse().isSuccessful();

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CopyObject";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(CopyObject.class);
	
	private void validateRequest() throws CoreException {	
		// Validate request 
		requireNonNull(CopyObjectRequest.getSourceBucketName(), "The Source Bucket name is required");
		requireNonNull(CopyObjectRequest.getDestinationBucketName(), "The Destination Bucket name is required");
		requireNonNull(CopyObjectRequest.getSourceKey(), "The Source Key is required");
		requireNonNull(CopyObjectRequest.getDestinationKey(), "The Destination Key is required");
		if (CopyObjectRequest.getSourceBucketName().isBlank()) {
			throw new IllegalArgumentException("Source bucket name cannot be empty or blank");
		}
		if (CopyObjectRequest.getDestinationBucketName().isBlank()) {
			throw new IllegalArgumentException("Destination bucket name cannot be empty or blank");
		}
		if (CopyObjectRequest.getSourceKey().isBlank()) {
			throw new IllegalArgumentException("Source Key cannot be empty or blank");
		}
		if (CopyObjectRequest.getDestinationKey().isBlank()) {
			throw new IllegalArgumentException("Destination Key cannot be empty or blank");
		}
	}
	
	private Map<String, String> getMetadata(amazons3connector.proxies.CopyObjectRequest CopyObjectRequest){
		// Retrieve every MetaData object connected to PutObjectRequest inside a list
		List<IMendixObject> s3MetaData = Core.retrieveByPath(getContext(),
				CopyObjectRequest.getMendixObject(),
				S3RequestMetaData.MemberNames.S3RequestMetaData_AbstractS3Request.toString());

		// Convert the list into a HashMap by looping over the list and using put on the HashMap
		Map<String, String> map = new HashMap<>();
		for (IMendixObject iMendixObject : s3MetaData) {
			S3RequestMetaData m = amazons3connector.proxies.S3RequestMetaData.initialize(getContext(), iMendixObject);
			LOGGER.debug("S3RequestMetaData: ", m.getKey() , ':', m.getValue());			
			map.put(m.getKey(), m.getValue());
		}
		return map;
	}

	private software.amazon.awssdk.services.s3.model.CopyObjectRequest createAWSRequest() {
		Builder awsRequestBuilder = software.amazon.awssdk.services.s3.model.CopyObjectRequest.builder()
				.destinationBucket(CopyObjectRequest.getDestinationBucketName())
				.sourceBucket(CopyObjectRequest.getSourceBucketName())
				.destinationKey(CopyObjectRequest.getDestinationKey())
				.sourceKey(CopyObjectRequest.getSourceKey())
				.metadata(getMetadata(CopyObjectRequest));
		return awsRequestBuilder.build();
	}
	
	// END EXTRA CODE
}
