// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import static java.util.Objects.requireNonNull;
import java.util.Date;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import amazons3connector.impl.AmazonS3Client;
import amazons3connector.impl.MxLogger;
import amazons3connector.proxies.ENUM_AWS_CommitmentPolicy;
import amazons3connector.proxies.ENUM_StorageClass;
import amazons3connector.proxies.GetObjectMetaData;
import amazons3connector.proxies.GetObjectResponse;
import amazons3connector.proxies.GetS3ObjectUsage;
import awsauthentication.proxies.Credentials;
import awsauthentication.proxies.ENUM_Region;
import software.amazon.awssdk.core.ResponseInputStream;
import software.amazon.awssdk.core.async.AsyncResponseTransformer;
import software.amazon.awssdk.services.s3.S3AsyncClient;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.GetObjectRequest;
import software.amazon.awssdk.services.s3.model.GetObjectRequest.Builder;
import software.amazon.awssdk.services.s3.model.StorageClass;
import software.amazon.encryption.s3.S3AsyncEncryptionClient;

public class GetObject extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	private final awsauthentication.proxies.ENUM_Region Region;
	/** @deprecated use GetObjectRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __GetObjectRequest;
	private final amazons3connector.proxies.GetObjectRequest GetObjectRequest;
	/** @deprecated use TargetFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TargetFile;
	private final system.proxies.FileDocument TargetFile;
	/** @deprecated use ClientsideEncryptionConfig.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ClientsideEncryptionConfig;
	private final amazons3connector.proxies.ClientsideEncryptionConfig ClientsideEncryptionConfig;

	public GetObject(
		IContext context,
		IMendixObject _credentials,
		java.lang.String _region,
		IMendixObject _getObjectRequest,
		IMendixObject _targetFile,
		IMendixObject _clientsideEncryptionConfig
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
		this.__GetObjectRequest = _getObjectRequest;
		this.GetObjectRequest = _getObjectRequest == null ? null : amazons3connector.proxies.GetObjectRequest.initialize(getContext(), _getObjectRequest);
		this.__TargetFile = _targetFile;
		this.TargetFile = _targetFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _targetFile);
		this.__ClientsideEncryptionConfig = _clientsideEncryptionConfig;
		this.ClientsideEncryptionConfig = _clientsideEncryptionConfig == null ? null : amazons3connector.proxies.ClientsideEncryptionConfig.initialize(getContext(), _clientsideEncryptionConfig);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			//Validation of the input parameters
			requireNonNull(this.Credentials, "AWS Credentials are required.");
			requireNonNull(this.Region, "AWS Region is required.");
			requireNonNull(this.GetObjectRequest, "GetObjectRequest is required.");
		
			//validation of the request
			validateRequest();
			
			// Building the AWS GetObjectRequest
			GetObjectRequest awsRequest = createAWSRequest();
		
			// Logging of the request building		
			LOGGER.debug("AWS request:", awsRequest);
			// Check if ClientsideEncryptionConfig exists or not
			if (ClientsideEncryptionConfig == null) {
				// Client creation		
				S3Client client = AmazonS3Client.getS3Client(Credentials, Region, GetObjectRequest);
				ResponseInputStream<software.amazon.awssdk.services.s3.model.GetObjectResponse> awsResponseStream = client.getObject(awsRequest);
				// Logging of the AWS response
				LOGGER.debug("AWS response:", awsResponseStream);
				
				// Creating and committing TargetFile
				createMxSystemFileObject(awsResponseStream, TargetFile);
		
				//Mapping response to Mx objects
				amazons3connector.proxies.GetObjectResponse MxResponse = mapResponseToMxObject(awsResponseStream);
				LOGGER.debug("MxResponse:", MxResponse);
				return MxResponse.getMendixObject();	
			} else {	
				// ---- Read Mendix parameters ----
				String kmsKeyId = ClientsideEncryptionConfig.getKmsKey();
				ENUM_Region kmsRegion = ClientsideEncryptionConfig.getKmsRegion();
				Credentials kmsCredentials = ClientsideEncryptionConfig.getClientsideEncryptionConfig_Credentials();
				ENUM_AWS_CommitmentPolicy mxPolicy = ClientsideEncryptionConfig.getCommitmentPolicy();

				// ---- Validation ----
				requireNonNull(kmsKeyId, "KMS keyId is required");
				requireNonNull(kmsCredentials, "KMS credentials are required");
				requireNonNull(kmsRegion, "KMS region is required");
				requireNonNull(mxPolicy, "Commitment policy is required");

				// Client creation		
				S3AsyncClient client = AmazonS3Client.getS3AsyncClient(Credentials, Region, GetObjectRequest);

				ExecutorService executor = Executors.newFixedThreadPool(2);

				S3AsyncEncryptionClient encryptedClient = AmazonS3Client.createEncryptedClient(kmsCredentials, kmsRegion, kmsKeyId, client, mxPolicy, GetObjectRequest);

				CompletableFuture<ResponseInputStream<software.amazon.awssdk.services.s3.model.GetObjectResponse>> future =
					encryptedClient.getObject(
						awsRequest,
						AsyncResponseTransformer.toBlockingInputStream()
					);

				ResponseInputStream<software.amazon.awssdk.services.s3.model.GetObjectResponse> decryptedStream = future.join();

				createMxSystemFileObject(decryptedStream, TargetFile);

				GetObjectResponse mxResponse = mapResponseToMxObject(decryptedStream);

				return mxResponse.getMendixObject();
			}	
		}
		catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetObject";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(GetObject.class);

	private void validateRequest() throws CoreException {
		// Validate name
		requireNonNull(GetObjectRequest.getBucketName(), "Bucket name is required");
		if (GetObjectRequest.getBucketName().isBlank()) {
			throw new IllegalArgumentException("Bucket name cannot be empty or blank");
		}
		requireNonNull(GetObjectRequest.getKey(), "Key name is required");
		if (GetObjectRequest.getKey().isBlank()) {
			throw new IllegalArgumentException("Key cannot be empty or blank");
		}
	}

	private software.amazon.awssdk.services.s3.model.GetObjectRequest createAWSRequest() {Builder awsRequestBuilder = software.amazon.awssdk.services.s3.model.GetObjectRequest.builder()
				.bucket(GetObjectRequest.getBucketName())
				.key(GetObjectRequest.getKey());
		return awsRequestBuilder.build();
	}

	private void createMxSystemFileObject(ResponseInputStream<software.amazon.awssdk.services.s3.model.GetObjectResponse> awsResponseStream, system.proxies.FileDocument TargetFile) throws CoreException {
		String fileName = GetObjectRequest.getKey().substring(GetObjectRequest.getKey().lastIndexOf('/') + 1);
		
		TargetFile.setDeleteAfterDownload(true);
		Core.storeFileDocumentContent(getContext(), TargetFile.getMendixObject(), fileName, awsResponseStream);
		TargetFile.commit(getContext());
	}

	private void addMetaData(GetObjectResponse mxResponse, String key, String value) {
		// Get every MetaData object that's connected to the GetObject object and create a GetObjectMetaData with the same key/value
		GetObjectMetaData getObjectMetaData = new GetObjectMetaData(getContext());
		getObjectMetaData.setKey(key);
		getObjectMetaData.setValue(value);
		getObjectMetaData.setGetObjectMetaData_GetObjectResponse(mxResponse);
		LOGGER.debug("getObjectMetaData: ", key , ':', value);			
	}

	private GetObjectResponse mapResponseToMxObject(ResponseInputStream<software.amazon.awssdk.services.s3.model.GetObjectResponse> awsResponseStream) {
		GetObjectResponse mxResponse = new GetObjectResponse(getContext());
		GetS3ObjectUsage mxGetS3ObjectUsage = new GetS3ObjectUsage(getContext());
		software.amazon.awssdk.services.s3.model.GetObjectResponse awsResponse = awsResponseStream.response();

		String fileName = GetObjectRequest.getKey().substring(GetObjectRequest.getKey().lastIndexOf('/') + 1);
		java.util.Date LastModified = Date.from(awsResponse.lastModified());

		if (!(awsResponse.storageClass() == null)) {
			ENUM_StorageClass StorageClass = getStorageClassEnumValue(awsResponse.storageClass());
			mxGetS3ObjectUsage.setStorageClass(StorageClass);
		}
		mxGetS3ObjectUsage.setETag(awsResponse.eTag());
		mxGetS3ObjectUsage.setKey(fileName);
		mxGetS3ObjectUsage.setLastModified(LastModified);
		mxGetS3ObjectUsage.setSize(awsResponse.contentLength());

		mxResponse.setGetObjectResponse_GetS3ObjectUsage(mxGetS3ObjectUsage);

		// Get all metadata from aws and use that inside the addMetaData call
		awsResponse.metadata().forEach((key, value) -> addMetaData(mxResponse, key, value));
		return mxResponse;
	}

	private ENUM_StorageClass getStorageClassEnumValue(StorageClass storageClass) {
		try {
			return ENUM_StorageClass.valueOf(storageClass.name());
		}
		catch (IllegalArgumentException e) {
			LOGGER.warn("ENUM_StorageClass value not found for value ", storageClass.name(), ", returning value ", ENUM_StorageClass.UNKNOWN_TO_SDK_VERSION.name());
			return ENUM_StorageClass.UNKNOWN_TO_SDK_VERSION;
		}
	}

	// END EXTRA CODE
}
