// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static java.util.Objects.requireNonNull;
import amazons3connector.impl.AmazonS3Client;
import amazons3connector.impl.MxLogger;
import amazons3connector.proxies.HeadObjectMetaData;
import amazons3connector.proxies.HeadObjectResponse;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.NoSuchBucketException;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * You can use the HeadBucket operation to retrieve the AWS Region the bucket is located and determine if a bucket exists and if you have permission to access it. Additionally, it will indicate whether the bucket name used in the request is an access point alias.
 * 
 * All parameters are required.
 * - AWS_Region (Enumeration)
 * - GetObjectRequest (Object)
 * - Credentials (Object)
 */
public class HeadObject extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	/** @deprecated use HeadObjectRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HeadObjectRequest;
	private final amazons3connector.proxies.HeadObjectRequest HeadObjectRequest;
	private final awsauthentication.proxies.ENUM_Region Region;

	public HeadObject(
		IContext context,
		IMendixObject _credentials,
		IMendixObject _headObjectRequest,
		java.lang.String _region
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.__HeadObjectRequest = _headObjectRequest;
		this.HeadObjectRequest = _headObjectRequest == null ? null : amazons3connector.proxies.HeadObjectRequest.initialize(getContext(), _headObjectRequest);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		software.amazon.awssdk.services.s3.model.HeadObjectResponse awsResponse = null;
		try {
			// Validation of input parameters
			requireNonNull(this.Credentials, "AWS Credentials are required.");
			requireNonNull(this.HeadObjectRequest, "HeadObjectRequest is required.");
			requireNonNull(this.Region, "AWS Region is required.");
			
			// Validation of the HeadObjectRequest object
			validateRequest();
			
			// Building the AWS HeadObjectRequest
			software.amazon.awssdk.services.s3.model.HeadObjectRequest awsRequest = createAWSRequest();
			
			// Log the request
			LOGGER.debug("AWS request:", awsRequest);
			// Client creation
			S3Client client = AmazonS3Client.getS3Client(Credentials, Region, HeadObjectRequest);
			
			// Invoke action on AWS client
			awsResponse = client.headObject(awsRequest);
			
			// Log the response
			LOGGER.debug("AWS response:", awsResponse);
			
			//Mapping response to Mx objects
			amazons3connector.proxies.HeadObjectResponse MxResponse = mapResponseToMxObject(awsResponse);

			return MxResponse.getMendixObject();
		}
		catch (NoSuchBucketException e) {
			LOGGER.error("The specified bucket (" + HeadObjectRequest.getBucketName() + ") cannot be located in the specified region (" + Region + ")");
			throw e;
		}
		catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "HeadObject";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(HeadObject.class);
	
	private void validateRequest() throws CoreException {	
		// Validate bucket name 
		requireNonNull(HeadObjectRequest.getBucketName(), "Bucket name is required.");
		if (HeadObjectRequest.getBucketName().isBlank()) {
			throw new IllegalArgumentException("Bucket name cannot be blank.");
		}
	}
	
	private software.amazon.awssdk.services.s3.model.HeadObjectRequest createAWSRequest() {
		software.amazon.awssdk.services.s3.model.HeadObjectRequest awsRequest = software.amazon.awssdk.services.s3.model.HeadObjectRequest.builder()
			.bucket(HeadObjectRequest.getBucketName())
			.key(HeadObjectRequest.getKey())
			.build();
		return awsRequest;
	}

	private void addMetaData(HeadObjectResponse mxResponse, String key, String value) {
		HeadObjectMetaData headObjectMetaData = new HeadObjectMetaData(getContext());
		headObjectMetaData.setKey(key);
		headObjectMetaData.setValue(value);
		headObjectMetaData.setHeadObjectMetaData_HeadObjectResponse(mxResponse);
		LOGGER.debug("getObjectMetaData: ", key , ':', value);			
	}

	private HeadObjectResponse mapResponseToMxObject(software.amazon.awssdk.services.s3.model.HeadObjectResponse awsResponse){
		HeadObjectResponse mxResponse = new HeadObjectResponse(getContext());
		awsResponse.metadata().forEach((key, value) -> addMetaData(mxResponse, key, value));
		return mxResponse;
	}
	// END EXTRA CODE
}
