// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import static java.util.Objects.requireNonNull;
import amazons3connector.impl.AmazonS3Client;
import amazons3connector.impl.MxLogger;
import amazons3connector.proxies.HeadBucketResponse;
import awsauthentication.proxies.ENUM_Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.NoSuchBucketException;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * You can use the HeadBucket operation to retrieve the AWS Region the bucket is located and determine if a bucket exists and if you have permission to access it. Additionally, it will indicate whether the bucket name used in the request is an access point alias.
 * 
 * All parameters are required.
 * - AWS_Region (Enumeration)
 * - GetObjectRequest (Object)
 * - Credentials (Object)
 */
public class HeadBucket extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	/** @deprecated use HeadBucketRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __HeadBucketRequest;
	private final amazons3connector.proxies.HeadBucketRequest HeadBucketRequest;
	private final awsauthentication.proxies.ENUM_Region Region;

	public HeadBucket(
		IContext context,
		IMendixObject _credentials,
		IMendixObject _headBucketRequest,
		java.lang.String _region
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.__HeadBucketRequest = _headBucketRequest;
		this.HeadBucketRequest = _headBucketRequest == null ? null : amazons3connector.proxies.HeadBucketRequest.initialize(getContext(), _headBucketRequest);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		software.amazon.awssdk.services.s3.model.HeadBucketResponse awsResponse = null;
		try {
			// Validation of input parameters
			requireNonNull(this.Credentials, "AWS Credentials are required.");
			requireNonNull(this.HeadBucketRequest, "HeadBucketRequest is required.");
			requireNonNull(this.Region, "AWS Region is required.");
			
			// Validation of the HeadBucketRequest object
			validateRequest();
			
			// Building the AWS HeadBucketRequest
			software.amazon.awssdk.services.s3.model.HeadBucketRequest awsRequest = createAWSRequest();
			
			// Log the request
			LOGGER.debug("AWS request:", awsRequest);
			
			// Client creation
			S3Client client = AmazonS3Client.getS3Client(Credentials, Region, HeadBucketRequest);
			
			// Invoke action on AWS client
			awsResponse = client.headBucket(awsRequest);
			
			// Log the response
			LOGGER.debug("AWS response:", awsResponse);
			
			//Mapping response to Mx objects
			amazons3connector.proxies.HeadBucketResponse MxResponse = mapResponseToMxObject(awsResponse);
			LOGGER.debug("MxResponse:", MxResponse);
			return MxResponse.getMendixObject();
		}
		catch (NoSuchBucketException e) {
			LOGGER.error("The specified bucket (" + HeadBucketRequest.getBucketName() + ") cannot be located in the specified region (" + Region + ")");
			throw e;
		}
		catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "HeadBucket";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(HeadBucket.class);
	
	private void validateRequest() throws CoreException {	
		// Validate bucket name 
		requireNonNull(HeadBucketRequest.getBucketName(), "Bucket name is required.");
		if (HeadBucketRequest.getBucketName().isBlank()) {
			throw new IllegalArgumentException("Bucket name cannot be blank.");
		}
	}
	
	private software.amazon.awssdk.services.s3.model.HeadBucketRequest createAWSRequest() {
		software.amazon.awssdk.services.s3.model.HeadBucketRequest awsRequest = software.amazon.awssdk.services.s3.model.HeadBucketRequest.builder()
			.bucket(HeadBucketRequest.getBucketName())
			.build();
		return awsRequest;
	}

	private HeadBucketResponse mapResponseToMxObject(software.amazon.awssdk.services.s3.model.HeadBucketResponse awsResponse){
		HeadBucketResponse mxResponse = new HeadBucketResponse(getContext());
		mxResponse.setRegion(getRegionEnumValue(awsResponse.sdkHttpResponse().firstMatchingHeader("x-amz-bucket-region").get()));
		mxResponse.setAccessPointAlias(Boolean.parseBoolean(awsResponse.sdkHttpResponse().firstMatchingHeader("x-amz-access-point-alias").get()));
		return mxResponse;
	}

	// String to ENUM_Region AWS Region Enumeration value
	
	private ENUM_Region getRegionEnumValue(String region) {
		if (region != null && !region.isBlank()) {
			try {
				return ENUM_Region.valueOf(region.replace('-', '_'));
			}
			catch (IllegalArgumentException e) {
				throw new MendixRuntimeException("No region returned from AWS response");
			}
		}
		else {
			throw new MendixRuntimeException("Unsupported region " + region);
		}
	}
	// END EXTRA CODE
}
