// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazons3connector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazons3connector.impl.AmazonS3Client;
import amazons3connector.impl.MxLogger;
import amazons3connector.proxies.S3RequestMetaData;
import software.amazon.awssdk.services.s3.S3Client;
import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.mendix.core.Core;
import software.amazon.awssdk.core.sync.RequestBody;
import com.mendix.systemwideinterfaces.core.UserAction;

public class PutObject extends UserAction<java.lang.Boolean>
{
	/** @deprecated use PutObjectRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __PutObjectRequest;
	private final amazons3connector.proxies.PutObjectRequest PutObjectRequest;
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	private final awsauthentication.proxies.ENUM_Region Region;
	/** @deprecated use FileDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __FileDocument;
	private final system.proxies.FileDocument FileDocument;

	public PutObject(
		IContext context,
		IMendixObject _putObjectRequest,
		IMendixObject _credentials,
		java.lang.String _region,
		IMendixObject _fileDocument
	)
	{
		super(context);
		this.__PutObjectRequest = _putObjectRequest;
		this.PutObjectRequest = _putObjectRequest == null ? null : amazons3connector.proxies.PutObjectRequest.initialize(getContext(), _putObjectRequest);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
		this.__FileDocument = _fileDocument;
		this.FileDocument = _fileDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _fileDocument);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		software.amazon.awssdk.services.s3.model.PutObjectResponse awsResponse = null;
		try {
			// Validation of input parameters
			requireNonNull(this.Credentials, "AWS Credentials are required.");
			requireNonNull(this.Region, "AWS Region is required.");
			requireNonNull(this.PutObjectRequest, "PutObjectRequest is required.");
			requireNonNull(this.FileDocument, "File document is required");

			// Validation of the PutObjectRequest object
			validateRequest();

			// Building the AWS PutObjectRequest
			software.amazon.awssdk.services.s3.model.PutObjectRequest awsRequest = createAWSRequest();

			// Logging of the awsRequest
			LOGGER.debug("AWS request:", awsRequest);

			// Client creation
			S3Client client = AmazonS3Client.getS3Client(Credentials, Region, PutObjectRequest);

			// Create request
			InputStream is = Core.getFileDocumentContent(getContext(), FileDocument.getMendixObject());
			RequestBody body = RequestBody.fromInputStream(is, FileDocument.getSize());

			// Invoke action on AWS client
			awsResponse = client.putObject(awsRequest, body);
			is.close();

			// Log the response
			LOGGER.debug("AWS response:", awsResponse);
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		// Determine return value
		return awsResponse.sdkHttpResponse().isSuccessful();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PutObject";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(PutObject.class);

	private void validateRequest() throws CoreException {
		// Validate BucketName
		requireNonNull(PutObjectRequest.getBucketName(), "Bucket name is required");
		if (PutObjectRequest.getBucketName().isBlank()) {
			throw new IllegalArgumentException("Bucket name cannot be blank");
		}

		// Validate Key
		requireNonNull(PutObjectRequest.getKey(), "Key is required");
		if (PutObjectRequest.getKey().isBlank()) {
			throw new IllegalArgumentException("Key cannot be blank");
		}

		// Validate file size
		if (!this.FileDocument.getHasContents()) {
			throw new NullPointerException("File size can not be empty");
		}

	}

	private Map<String, String> getMetadata(amazons3connector.proxies.PutObjectRequest PutObjectRequest){
		// Retrieve every MetaData object connected to PutObjectRequest inside a list
		List<IMendixObject> s3MetaData = Core.retrieveByPath(getContext(),
				PutObjectRequest.getMendixObject(),
				S3RequestMetaData.MemberNames.S3RequestMetaData_AbstractS3Request.toString());

		// Convert the list into a HashMap by looping over the list and using put on the HashMap
		Map<String, String> map = new HashMap<>();
		for (IMendixObject iMendixObject : s3MetaData) {
			S3RequestMetaData m = amazons3connector.proxies.S3RequestMetaData.initialize(getContext(), iMendixObject);
			LOGGER.debug("S3RequestMetaData: ", m.getKey() , ':', m.getValue());			
			map.put(m.getKey(), m.getValue());
		}
		return map;
	}

	private software.amazon.awssdk.services.s3.model.PutObjectRequest createAWSRequest() {
		software.amazon.awssdk.services.s3.model.PutObjectRequest awsRequest = software.amazon.awssdk.services.s3.model.PutObjectRequest
				.builder()
				.bucket(PutObjectRequest.getBucketName())
				.key(PutObjectRequest.getKey())
				.metadata(getMetadata(PutObjectRequest))
				.build();

		return awsRequest;
	}
	// END EXTRA CODE
}
