// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import static java.util.Objects.requireNonNull;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.azure.ai.openai.OpenAIClient;
import com.azure.ai.openai.OpenAIClientBuilder;
import com.azure.core.credential.AzureKeyCredential;
import com.azure.ai.openai.models.ChatCompletions;
import com.azure.ai.openai.models.ChatCompletionsOptions;
import com.azure.ai.openai.models.ChatRequestMessage;
import com.azure.ai.openai.models.ChatRequestSystemMessage;
import com.azure.ai.openai.models.ChatRequestUserMessage;
import com.azure.ai.openai.models.ChatRequestAssistantMessage;
import com.azure.ai.openai.models.ChatResponseMessage;
import com.azure.core.util.IterableStream;
import com.azure.core.util.CoreUtils;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.Request;
import openaiconnector.proxies.OpenAIDeployedModel;
import openaiconnector.proxies.Configuration;
import com.mendix.systemwideinterfaces.core.UserAction;

public class AzureOpenAI_ChatCompletions_Stream extends UserAction<java.lang.Void>
{
	/** @deprecated use OpenAIRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OpenAIRequest;
	private final openaiconnector.proxies.OpenAIRequest_Extension OpenAIRequest;
	/** @deprecated use OpenAIDeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OpenAIDeployedModel;
	private final openaiconnector.proxies.OpenAIDeployedModel OpenAIDeployedModel;
	private final java.lang.String CallbackMicroflow;
	private final java.lang.String RequestID;

	public AzureOpenAI_ChatCompletions_Stream(
		IContext context,
		IMendixObject _openAIRequest,
		IMendixObject _openAIDeployedModel,
		java.lang.String _callbackMicroflow,
		java.lang.String _requestID
	)
	{
		super(context);
		this.__OpenAIRequest = _openAIRequest;
		this.OpenAIRequest = _openAIRequest == null ? null : openaiconnector.proxies.OpenAIRequest_Extension.initialize(getContext(), _openAIRequest);
		this.__OpenAIDeployedModel = _openAIDeployedModel;
		this.OpenAIDeployedModel = _openAIDeployedModel == null ? null : openaiconnector.proxies.OpenAIDeployedModel.initialize(getContext(), _openAIDeployedModel);
		this.CallbackMicroflow = _callbackMicroflow;
		this.RequestID = _requestID;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(this.OpenAIRequest, "A Request object is required");
			requireNonNull(this.OpenAIDeployedModel, "A DeployedModel object is required");
			requireNonNull(this.CallbackMicroflow, "A callback microflow name is required");
			requireNonNull(this.RequestID, "A RequestID is required");
			
			LOGGER.info("Starting Azure OpenAI streaming request with ID: " + RequestID);
			
			// Create Azure OpenAI client with API key and endpoint from deployed model
			OpenAIClient client = createOpenAIClient();
			
			// Build the chat completion request with streaming enabled
		ChatCompletionsOptions requestParams = buildChatCompletionRequest();
			LOGGER.info("Azure OpenAI streaming request initiated successfully");

			// Execute the streaming request
			executeStreamingRequest(client, requestParams);
			return null;
			
		} catch (Exception e) {
			LOGGER.error("Error in Azure OpenAI streaming: " + e.getMessage(), e);
			notifyCallbackOnError(e);
			return null;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AzureOpenAI_ChatCompletions_Stream";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(AzureOpenAI_ChatCompletions_Stream.class);
	private static final ObjectMapper MAPPER = new ObjectMapper();
	
	/**
	 * Creates an Azure OpenAI client using the API key and endpoint from the deployed model's configuration
	 */
	private OpenAIClient createOpenAIClient() throws Exception {
		// Initialize the DeployedModel proxy
		OpenAIDeployedModel deployedModel = OpenAIDeployedModel.initialize(getContext(), this.OpenAIDeployedModel.getMendixObject());
		
		// Get the Configuration object via the many-to-one relationship
		Configuration configuration = deployedModel.getOpenAIDeployedModel_Configuration();
		requireNonNull(configuration, "Configuration is required to retrieve API Key and Endpoint");
		
		// Get the encrypted API key from Configuration
		String encryptedApiKey = configuration.getApiKey();
		requireNonNull(encryptedApiKey, "API Key is required in Configuration");
		
		// Decrypt the API key using Encryption module microflow
		String apiKey = encryption.proxies.microflows.Microflows.decrypt(getContext(), encryptedApiKey);
		requireNonNull(apiKey, "Failed to decrypt API Key");
		
		// Get the Azure endpoint - typically something like https://<resource>.openai.azure.com/
		String endpoint = configuration.getEndpoint();
		requireNonNull(endpoint, "Azure endpoint is required in Configuration");
		
		// Remove /openai/deployments/ if present (Azure SDK adds it automatically)
		if (endpoint.contains("/openai/deployments")) {
			endpoint = endpoint.replace("/openai/deployments/", "").replace("/openai/deployments", "");
			LOGGER.debug("Cleaned endpoint by removing /openai/deployments/: " + endpoint);
		}
		
		// Ensure endpoint ends with /
		if (!endpoint.endsWith("/")) {
			endpoint = endpoint + "/";
		}
		
		LOGGER.debug("Azure OpenAI client created successfully with endpoint: " + endpoint);
		
		return new OpenAIClientBuilder()
			.endpoint(endpoint)
			.credential(new AzureKeyCredential(apiKey))
			.buildClient();
	}
	
	/**
	 * Builds the ChatCompletionsOptions request from the GenAICommons.Request
	 * Converts Mendix request object to Azure OpenAI SDK format
	 */
	private ChatCompletionsOptions buildChatCompletionRequest() throws Exception {
		// Initialize the DeployedModel proxy to get the model name (deployment name in Azure)
		OpenAIDeployedModel deployedModel = OpenAIDeployedModel.initialize(getContext(), this.OpenAIDeployedModel.getMendixObject());
		String model = deployedModel.getModel();
		requireNonNull(model, "Model name is required in DeployedModel");
		
		// Get the associated GenAICommons.Request via the association
		Request request = this.OpenAIRequest.getOpenAIRequest_Extension_Request();
		requireNonNull(request, "GenAICommons.Request is required via association");
		
		// Build messages list from request
		List<ChatRequestMessage> messages = buildMessagesList(request);
		requireNonNull(messages, "Messages list cannot be null");
		
		if (messages.isEmpty()) {
			LOGGER.warn("Request contains no messages");
		}
		
		// Build the request parameters
		ChatCompletionsOptions options = new ChatCompletionsOptions(messages);
		
		// Add optional parameters if they exist
		BigDecimal temperature = request.getTemperature();
		if (temperature != null) {
			// Convert BigDecimal to double
			options.setTemperature(temperature.doubleValue());
		}
		
		Integer maxTokens = request.getMaxTokens();
		if (maxTokens != null && maxTokens > 0) {
			options.setMaxTokens(maxTokens);
		}
		
		BigDecimal topP = request.getTopP();
		if (topP != null && topP.signum() > 0) {
			options.setTopP(topP.doubleValue());
		}
		
		LOGGER.debug("Chat completion request built successfully with model: " + model);
		
		return options;
	}
	
	/**
	 * Converts GenAICommons.Request messages to Azure OpenAI SDK ChatRequestMessage format
	 * Accesses messages via the many-to-many relationship from Request
	 */
	private List<ChatRequestMessage> buildMessagesList(Request request) throws Exception {
		List<ChatRequestMessage> messages = new ArrayList<>();
		
		try {
			// Retrieve messages via the association using the proxy's getter method
			List<genaicommons.proxies.Message> messageList = request.getRequest_Message();
			
			if (messageList == null || messageList.isEmpty()) {
				LOGGER.warn("No messages found in Request object");
				return messages;
			}
			
			// Convert proxy objects to IMendixObjects for processing
			List<IMendixObject> messageObjects = messageList.stream()
				.map(msg -> msg.getMendixObject())
				.toList();
			
			LOGGER.debug("Found " + messageObjects.size() + " messages in Request");
			
			// Convert each message object to ChatRequestMessage
			for (IMendixObject msgObj : messageObjects) {
				try {
					String role = (String) msgObj.getValue(getContext(), "Role");
					String content = (String) msgObj.getValue(getContext(), "Content");
					
					if (content == null || content.trim().isEmpty()) {
						LOGGER.warn("Skipping message with empty content");
						continue;
					}
					
					ChatRequestMessage message = convertRoleToMessage(role, content);
					
					messages.add(message);
					LOGGER.debug("Added message with role: " + role);
					
				} catch (Exception e) {
					LOGGER.error("Error processing individual message: " + e.getMessage(), e);
					// Continue processing remaining messages
				}
			}
			
		} catch (Exception e) {
			LOGGER.error("Error building messages list: " + e.getMessage(), e);
			throw new Exception("Failed to build messages list from Request", e);
		}
		
		return messages;
	}
	
	/**
	 * Converts Mendix Message.Role to Azure OpenAI SDK ChatRequestMessage
	 */
	private ChatRequestMessage convertRoleToMessage(String role, String content) {
		String normalizedRole = normalizeRole(role);
		
		return switch (normalizedRole) {
			case "system" -> new ChatRequestSystemMessage(content);
			case "assistant" -> new ChatRequestAssistantMessage(content);
			case "user" -> new ChatRequestUserMessage(content);
			default -> {
				LOGGER.warn("Unknown role: " + normalizedRole + ", defaulting to USER");
				yield new ChatRequestUserMessage(content);
			}
		};
	}

	private String normalizeRole(String role) {
		if (role == null || role.trim().isEmpty()) {
			LOGGER.debug("Role is null or empty, defaulting to USER");
			return "user";
		}
		return role.trim().toLowerCase();
	}
		
	/**
	 * Executes the streaming request using Azure OpenAI SDK
	 * Processes each chunk as it arrives from the API
	 */
	private void executeStreamingRequest(OpenAIClient client, ChatCompletionsOptions options) {
		try {
			LOGGER.info("Initiating Azure OpenAI streaming request");
			
			// Get the deployed model to retrieve the deployment name (used as model name in Azure)
			OpenAIDeployedModel deployedModel = OpenAIDeployedModel.initialize(getContext(), this.OpenAIDeployedModel.getMendixObject());
			String deploymentName = deployedModel.getModel();
			
			// Create streaming request - returns IterableStream<ChatCompletions>
			IterableStream<ChatCompletions> chatCompletionsStream = client.getChatCompletionsStream(deploymentName, options);
			
			// Process the stream of chunks
			chatCompletionsStream.stream()
				.forEach(chatCompletions -> {
					try {
						processChunk(chatCompletions);
					} catch (Exception e) {
						LOGGER.error("Error processing chunk: " + e.getMessage(), e);
						// Continue processing remaining chunks
					}
				});
			
			LOGGER.info("Stream completed successfully for request: " + RequestID);
			notifyCallbackOnStreamComplete();
			
		} catch (Exception e) {
			LOGGER.error("Error executing streaming request: " + e.getMessage(), e);
			notifyCallbackOnError(e);
		}
	}

	/**
	 * Processes a single ChatCompletions from the stream
	 * Extracts the content delta and sends it to the callback microflow
	 */
	private void processChunk(ChatCompletions chatCompletions) throws Exception {
		// Extract the content from the chunk
		// The chunk contains choices with delta content
		if (!CoreUtils.isNullOrEmpty(chatCompletions.getChoices())) {
			ChatResponseMessage delta = chatCompletions.getChoices().get(0).getDelta();
			if (delta != null && delta.getContent() != null) {
				String content = delta.getContent();
				
				LOGGER.debug("Received chunk content: " + content);
				
				// Send chunk to callback microflow
				notifyCallbackOnChunk(content);
			}
		}
	}
	
	
	/**
	 * Notifies the callback microflow of a new chunk
	 */
	private void notifyCallbackOnChunk(String content) {
		try {
			Core.microflowCall(CallbackMicroflow)
				.withParam("RequestId", RequestID)
				.withParam("Content", content)
				.execute(getContext());
		} catch (Exception e) {
			LOGGER.error("Failed to notify callback of chunk: " + e.getMessage(), e);
		}
	}
	
	/**
	 * Notifies the callback microflow that the stream is complete
	 */
	private void notifyCallbackOnStreamComplete() {
		try {
			Core.microflowCall(CallbackMicroflow)
				.withParam("RequestId", RequestID)
				.withParam("Content", "[STREAM_COMPLETE]")
				.execute(getContext());
		} catch (Exception e) {
			LOGGER.error("Failed to notify callback of stream completion: " + e.getMessage(), e);
		}
	}
	
	/**
	 * Notifies the callback microflow of any errors
	 */
	private void notifyCallbackOnError(Exception e) {
		try {
			Core.microflowCall(CallbackMicroflow)
				.withParam("RequestId", RequestID)
				.withParam("Content", "[ERROR] " + e.getMessage())
				.execute(getContext());
		} catch (Exception callbackError) {
			LOGGER.error("Failed to notify callback of error: " + callbackError.getMessage(), callbackError);
		}
	}
	
	// END EXTRA CODE
}
