// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import amazonbedrockconnector.proxies.InvokeModelRequest;
import amazonbedrockconnector.proxies.InvokeModelResponse;
import awsauthentication.proxies.Credentials;
import awsauthentication.proxies.ENUM_Region;
import myfirstmodule.handlers.StreamingInvokeModelHandler;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.mendix.core.Core;
import com.mendix.externalinterface.connector.RequestHandler;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.thirdparty.org.json.JSONObject;
import software.amazon.awssdk.auth.credentials.AwsCredentials;
import software.amazon.awssdk.identity.spi.AwsCredentialsIdentity;
import java.io.BufferedInputStream;

public class InitAsyncInvokeHandler extends UserAction<java.lang.Void>
{
	public InitAsyncInvokeHandler(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Core.addRequestHandler("llm-streaming", new StreamingInvokeModelHandler());
		Core.addRequestHandler("llm", new RequestHandler() {
			@Override
			protected void processRequest(IMxRuntimeRequest iMxRuntimeRequest, IMxRuntimeResponse resp, String s) throws Exception {
				String requestBody = new String(iMxRuntimeRequest.getInputStream().readAllBytes());

				IContext ctx = Core.createSystemContext();
				Credentials creds = awsauthentication.proxies.microflows.Microflows.getCredentials(ctx, true, ENUM_Region.eu_central_1);

				InvokeModelRequest awsRequest = new InvokeModelRequest(ctx);
				awsRequest.setModelID("eu.anthropic.claude-sonnet-4-20250514-v1:0");
				awsRequest.setRequestBody("""
						{
						    "anthropic_version": "bedrock-2023-05-31",
						    "max_tokens": 512,
						    "temperature": 0.5,
						    "messages": [{
						        "role": "user",
						        "content": " """ +
								requestBody
						+ """
"
						    }]
						}						
						""");
				InvokeModelResponse invokeResponse = amazonbedrockconnector.proxies.microflows.Microflows.invokeModel(ctx, awsRequest, creds, ENUM_Region.eu_central_1);

				String response = invokeResponse.getResponseBody();

				ObjectMapper objectMapper = new ObjectMapper();
				ObjectNode result = (ObjectNode) objectMapper.readTree(response);
				JsonNode text = result.path("content").get(0).path("text");

				resp.setContentType("text/plain");
				resp.setStatus(200);
				resp.getWriter().write(text.toString());
				resp.getWriter().flush();
			}
		});
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InitAsyncInvokeHandler";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
