// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import static java.util.Objects.requireNonNull;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.Future;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import amazonbedrockconnector.impl.AmazonBedrockClient;
import amazonbedrockconnector.impl.MxLogger;
import amazonbedrockconnector.proxies.InvokeModelResponse;
import com.mendix.thirdparty.org.json.JSONObject;
import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.services.bedrockruntime.BedrockRuntimeAsyncClient;
import software.amazon.awssdk.http.SdkHttpResponse;
import com.mendix.systemwideinterfaces.core.UserAction;
import software.amazon.awssdk.services.bedrockruntime.model.InvokeModelWithResponseStreamRequest;
import software.amazon.awssdk.services.bedrockruntime.model.InvokeModelWithResponseStreamResponseHandler;

/**
 * My InvokeModelWithResponseStream Java Action.
 */
public class InvokeModelWithResponseStream extends UserAction<java.lang.Void>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	private final awsauthentication.proxies.ENUM_Region Region;
	/** @deprecated use InvokeModelRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __InvokeModelRequest;
	private final amazonbedrockconnector.proxies.InvokeModelRequest InvokeModelRequest;
	private final java.lang.String RequestId;
	private final java.lang.String CallbackMicroflow;

	public InvokeModelWithResponseStream(
		IContext context,
		IMendixObject _credentials,
		java.lang.String _region,
		IMendixObject _invokeModelRequest,
		java.lang.String _requestId,
		java.lang.String _callbackMicroflow
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
		this.__InvokeModelRequest = _invokeModelRequest;
		this.InvokeModelRequest = _invokeModelRequest == null ? null : amazonbedrockconnector.proxies.InvokeModelRequest.initialize(getContext(), _invokeModelRequest);
		this.RequestId = _requestId;
		this.CallbackMicroflow = _callbackMicroflow;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			// Validating JA input parameters
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(InvokeModelRequest, "InvokeModelGenericRequest is required");
			requireNonNull(Region, "AWS Region is required");
			
			validateRequest();

			var ctx = getContext();
			
			BedrockRuntimeAsyncClient client = AmazonBedrockClient.getBedrockRuntimeAsyncClient(Credentials, Region, InvokeModelRequest);
//
			software.amazon.awssdk.services.bedrockruntime.model.InvokeModelWithResponseStreamRequest awsRequest = getAwsRequest();
//			LOGGER.info("AWS request: " + awsRequest);
//
			var responseStreamHandler = InvokeModelWithResponseStreamResponseHandler.builder()
					.subscriber(InvokeModelWithResponseStreamResponseHandler.Visitor.builder().onChunk(chunk -> {
						var responseTxt = chunk.bytes().asUtf8String();
						LOGGER.info("Response: " + responseTxt);

						var response = new JSONObject(responseTxt);

						// Extract and print the text from the content blocks.
						if (Objects.equals(response.getString("type"), "content_block_delta")) {
							var delta = response.getJSONObject("delta");

							if (delta.has("text")) {
								var text = delta.getString("text");
								Core.microflowCall(CallbackMicroflow)
										.withParam("RequestId", RequestId)
										.withParam("Content", text).execute(ctx);
							}
						}
					}).build()).build();

			Future<Void> r = client.invokeModelWithResponseStream(awsRequest, responseStreamHandler);
			r.get();
			LOGGER.info("AWS invoke done...");

//			LOGGER.info("AWS response: " + awsResponse);
//
//			InvokeModelResponse mxResponse = getMxResponse(awsResponse);
			
//			return mxResponse.getMendixObject();
			return null;
		} catch (Exception e) {
			LOGGER.error(e);
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InvokeModelWithResponseStream";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(InvokeModelWithResponseStream.class);
	
	private static final ObjectMapper objectMapper = new ObjectMapper();
	
	private void validateRequest() {
		if (InvokeModelRequest.getModelID() == null|| InvokeModelRequest.getModelID().isBlank()) {
			throw new IllegalArgumentException("ModelId is required. Please provide the model id of the model you want to invoke.");
		}
		
		if (InvokeModelRequest.getRequestBody() == null || InvokeModelRequest.getRequestBody().isBlank()) {
			throw new IllegalArgumentException("RequestBody is required. Please provide a valid request body of the model you want to invoke.");
		}
	}

	private software.amazon.awssdk.services.bedrockruntime.model.InvokeModelWithResponseStreamRequest getAwsRequest() {
		return InvokeModelWithResponseStreamRequest.builder()
				.body(SdkBytes.fromUtf8String(InvokeModelRequest.getRequestBody()))
				.modelId(InvokeModelRequest.getModelID())
				.build();
	}
	
	private InvokeModelResponse getMxResponse(software.amazon.awssdk.services.bedrockruntime.model.InvokeModelResponse awsResponse) throws Exception {
		var mxResponse = new InvokeModelResponse(getContext());

		SdkHttpResponse httpResponse = awsResponse.sdkHttpResponse();
        Optional<String> inputTokenCountHeader = httpResponse.firstMatchingHeader("X-Amzn-Bedrock-Input-Token-Count");

        // Retrieve the existing JSON body
        String responseBody = awsResponse.body().asUtf8String();

        try {
            // Parse the existing JSON body
            ObjectNode jsonNode = (ObjectNode) objectMapper.readTree(responseBody);

            // If the header is present, add it to the JSON as a key-value pair
            inputTokenCountHeader.ifPresent(headerValue -> {
                jsonNode.put("request_tokens", headerValue);
            });

            // Convert the updated JSON back to a string
            String updatedResponseBody = jsonNode.toString();

            // Set the updated JSON string as the response body
            mxResponse.setResponseBody(updatedResponseBody);

        } catch (Exception e) {
                    LOGGER.error("Error processing JSON response: " + e.getMessage());
                    throw e;
        }
		
		return mxResponse;
	}
	
	// END EXTRA CODE
}
