// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxgenaiconnector.impl.MxLogger;
import okhttp3.*;
import okhttp3.sse.*;
import java.util.concurrent.CountDownLatch;

public class MendixCloud_Stream extends UserAction<java.lang.Void>
{
	public MendixCloud_Stream(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			CountDownLatch latch = new CountDownLatch(1);
			
			OkHttpClient client = new OkHttpClient.Builder()
		            .readTimeout(0, java.util.concurrent.TimeUnit.MILLISECONDS)
		            .build();
		        
	        // JSON payload for POST request
	        String jsonData = """
	            {
	                    "inferenceConfig": {},
	                    "messages": [
	                        {
	                            "content": [
	                                {
	                                    "text": "tell me a story"
	                                }
	                            ],
	                            "toolCalls": [],
	                            "role": "user"
	                        }
	                    ]
	                }
	            """;
	        
	        MediaType JSON = MediaType.get("application/json; charset=utf-8");
	        RequestBody requestBody = RequestBody.create(jsonData, JSON);
	        
	        Request request = new Request.Builder()
	            .url("https://peuc1-compute.services.genai-eu-1a.mendixcloud.com/api/v1/resources/868ecf15-7856-4835-b46e-c0f0f86a0fe3/converse-stream")
	            .header("Accept", "text/event-stream")
	            .header("Content-Type", "application/json")
	            .header("x-api-key", "vAzhiLvKAc6DSlwcKEKLeNFBdcQf7kRxCGWkr3v5kAoPEgU45r")
	            .post(requestBody)
	            .build();
	        
	        EventSourceListener listener = new EventSourceListener() {
	            @Override
	            public void onOpen(EventSource eventSource, Response response) {
	            	LOGGER.info("SSE Connection opened");
	            	LOGGER.info("Response Status: " + response.code());
	            }
	            
	            @Override
	            public void onEvent(EventSource eventSource, String id, String type, String data) {
	                LOGGER.info("Event Type: " + type + "; Event Data: " + data);
	            }
	            
	            @Override
	            public void onClosed(EventSource eventSource) {
	            	LOGGER.info("SSE Connection closed");
	            	latch.countDown(); // Signal completion
	            }
	            
	            @Override
	            public void onFailure(EventSource eventSource, Throwable t, Response response) {
	            	LOGGER.info("SSE Connection failed: " + t.getMessage());
	                if (response != null) {
	                	LOGGER.info("Response Status: " + response.code());
	                }
	                latch.countDown(); // Signal completion
	            }
	        };
	        
	        EventSource eventSource = EventSources.createFactory(client)
	            .newEventSource(request, listener);
	        
	        try {
	        	latch.await(); // Wait indefinitely until stream completes
	        } catch (InterruptedException e) {
	            Thread.currentThread().interrupt();
	        }
	        
	        eventSource.cancel();
	        LOGGER.info("EventSource cancelled");
	        return null;
		        
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MendixCloud_Stream";
	}

	// BEGIN EXTRA CODE
	private static final mxgenaiconnector.impl.MxLogger LOGGER = new MxLogger(MendixCloud_Stream.class);
	// END EXTRA CODE
}
