// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxgenaiconnector.impl.MxLogger;
import okhttp3.*;
import okhttp3.sse.*;
import static java.util.Objects.requireNonNull;
import java.util.concurrent.CountDownLatch;

public class MendixCloud_ChatCompletions_Stream extends UserAction<java.lang.Void>
{
	private final java.lang.String RequestBodyJSON;
	/** @deprecated use MxCloudDeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MxCloudDeployedModel;
	private final mxgenaiconnector.proxies.MxCloudDeployedModel MxCloudDeployedModel;
	private final java.lang.String CallbackMicroflow;
	private final java.lang.String RequestID;

	public MendixCloud_ChatCompletions_Stream(
		IContext context,
		java.lang.String _requestBodyJSON,
		IMendixObject _mxCloudDeployedModel,
		java.lang.String _callbackMicroflow,
		java.lang.String _requestID
	)
	{
		super(context);
		this.RequestBodyJSON = _requestBodyJSON;
		this.__MxCloudDeployedModel = _mxCloudDeployedModel;
		this.MxCloudDeployedModel = _mxCloudDeployedModel == null ? null : mxgenaiconnector.proxies.MxCloudDeployedModel.initialize(getContext(), _mxCloudDeployedModel);
		this.CallbackMicroflow = _callbackMicroflow;
		this.RequestID = _requestID;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(this.RequestBodyJSON, "A Request object is required");
		requireNonNull(this.MxCloudDeployedModel, "A DeployedModel object is required");
		requireNonNull(this.CallbackMicroflow, "A callback microflow name is required");
		requireNonNull(this.RequestID, "A RequestID is required");
		try {
			
			CountDownLatch latch = new CountDownLatch(1);
			
			OkHttpClient client = new OkHttpClient.Builder()
		            .readTimeout(0, java.util.concurrent.TimeUnit.MILLISECONDS)
		            .build();
	        
	        MediaType JSON = MediaType.get("application/json; charset=utf-8");
	        RequestBody requestBody = RequestBody.create(this.RequestBodyJSON, JSON);
	        var accessKey = encryption.proxies.microflows.Microflows.decrypt(getContext(),this.MxCloudDeployedModel.getMxCloudDeployedModel_Configuration().getAccessToken());
	        
	        Request request = new Request.Builder()
	            .url(this.MxCloudDeployedModel.getMxCloudDeployedModel_Configuration().getResourceBaseUrl() + "/converse-stream")
	            .header("Accept", "text/event-stream")
	            .header("Content-Type", "application/json")
	            .header("x-api-key", accessKey)
	            .post(requestBody)
	            .build();
	        
	        EventSourceListener listener = new EventSourceListener() {
	            @Override
	            public void onOpen(EventSource eventSource, Response response) {
	            	LOGGER.info("SSE Connection opened");
	            	LOGGER.info("Response Status: " + response.code());
	            }
	            
	            @Override
	            public void onEvent(EventSource eventSource, String id, String type, String data) {
	            	LOGGER.info("Event Type: " + type);
	            	if ("CONTENT_BLOCK_DELTA".equals(type)) {
	            		 try {
	            	            JsonNode rootNode = mapper.readTree(data);
	            	            String responseText  = rootNode.path("delta").path("text").asText();
	            	            LOGGER.info("Response text: " + responseText);
	            	            Core.microflowCall(CallbackMicroflow)
								.withParam("RequestId", RequestID)
								.withParam("Content", responseText).execute(getContext());
	            	             
	            	        } catch (Exception e) {
	            	            LOGGER.debug("Error parsing JSON: " + e.getMessage());
	            	            
	            	        }
	            	}
	                
	            }
	            
	            @Override
	            public void onClosed(EventSource eventSource) {
	            	LOGGER.info("SSE Connection closed");
	            	latch.countDown(); // Signal completion
	            }
	            
	            @Override
	            public void onFailure(EventSource eventSource, Throwable t, Response response) {
	            	LOGGER.info("SSE Connection failed: " + t.getMessage());
	                if (response != null) {
	                	LOGGER.info("Response Status: " + response.code());
	                }
	                latch.countDown(); // Signal completion
	            }
	        };
	        
	        EventSource eventSource = EventSources.createFactory(client)
	            .newEventSource(request, listener);
	        
	        try {
	        	latch.await(); // Wait indefinitely until stream completes
	        } catch (InterruptedException e) {
	            Thread.currentThread().interrupt();
	        }
	        
	        eventSource.cancel();
	        LOGGER.info("EventSource cancelled");
	        return null;
		        
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MendixCloud_ChatCompletions_Stream";
	}

	// BEGIN EXTRA CODE
	private static final mxgenaiconnector.impl.MxLogger LOGGER = new MxLogger(MendixCloud_ChatCompletions_Stream.class);
	private static final ObjectMapper mapper = new ObjectMapper();
	// END EXTRA CODE
}
