// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import static java.util.Objects.requireNonNull;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Map.Entry;
import java.util.concurrent.Future;
import java.util.stream.Collectors;
import org.apache.commons.io.IOUtils;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import genaicommons.impl.FunctionImpl;
import genaicommons.impl.FunctionMappingImpl;
import genaicommons.proxies.ENUM_FileType;
import genaicommons.proxies.ENUM_MessageRole;
import genaicommons.proxies.ENUM_ToolChoice;
import genaicommons.proxies.EnumValue;
import genaicommons.proxies.Argument;
import genaicommons.proxies.ArgumentInput;
import genaicommons.proxies.FileCollection;
import genaicommons.proxies.FileContent;
import genaicommons.proxies.Request;
import genaicommons.proxies.Response;
import genaicommons.proxies.StopSequence;
import genaicommons.proxies.Tool;
import genaicommons.proxies.ToolCall;
import genaicommons.proxies.ToolCollection;
import genaicommons.proxies.DeployedModel;
import myfirstmodule.handlers.OpenAIStreamResponseHandler;
import openaiconnector.proxies.OpenAIRequest_Extension;
import openaiconnector.proxies.OpenAIDeployedModel;
import com.mendix.systemwideinterfaces.core.UserAction;

public class OpenAI_ChatCompletions_Stream extends UserAction<java.lang.Void>
{
	/** @deprecated use OpenAIRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OpenAIRequest;
	private final openaiconnector.proxies.OpenAIRequest_Extension OpenAIRequest;
	/** @deprecated use OpenAIDeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __OpenAIDeployedModel;
	private final openaiconnector.proxies.OpenAIDeployedModel OpenAIDeployedModel;
	private final java.lang.String CallbackMicroflow;
	private final java.lang.String RequestID;

	public OpenAI_ChatCompletions_Stream(
		IContext context,
		IMendixObject _openAIRequest,
		IMendixObject _openAIDeployedModel,
		java.lang.String _callbackMicroflow,
		java.lang.String _requestID
	)
	{
		super(context);
		this.__OpenAIRequest = _openAIRequest;
		this.OpenAIRequest = _openAIRequest == null ? null : openaiconnector.proxies.OpenAIRequest_Extension.initialize(getContext(), _openAIRequest);
		this.__OpenAIDeployedModel = _openAIDeployedModel;
		this.OpenAIDeployedModel = _openAIDeployedModel == null ? null : openaiconnector.proxies.OpenAIDeployedModel.initialize(getContext(), _openAIDeployedModel);
		this.CallbackMicroflow = _callbackMicroflow;
		this.RequestID = _requestID;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(this.OpenAIRequest, "A Request object is required");
			requireNonNull(this.OpenAIDeployedModel, "A DeployedModel object is required");
			requireNonNull(this.CallbackMicroflow, "A callback microflow name is required");
			requireNonNull(this.RequestID, "A RequestID is required");
			
			LOGGER.info("Starting OpenAI streaming request with ID: " + RequestID);
			
			// Build the OpenAI request by calling the microflow
			IMendixObject requestResult = Core.microflowCall("Request_CallAPI")
				.withParam("Request", OpenAIRequest.getMendixObject())
				.withParam("DeployedModel", OpenAIDeployedModel.getMendixObject())
				.execute(getContext());
			
			if (requestResult == null) {
				LOGGER.error("Request_CallAPI returned null");
				return null;
			}
			
			// Build the response stream handler
			OpenAIStreamResponseHandler responseHandler = buildResponseHandler();
			
			// Execute the async streaming request
			executeStreamingRequest(responseHandler);
			
			LOGGER.info("OpenAI streaming request initiated successfully");
			return null;
			
		} catch (Exception e) {
			LOGGER.error("Error in OpenAI streaming: " + e.getMessage(), e);
			notifyCallbackOnError(e);
			return null;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpenAI_ChatCompletions_Stream";
	}

	// BEGIN EXTRA CODE
	private static final genaicommons.impl.MxLogger LOGGER = new genaicommons.impl.MxLogger(OpenAI_ChatCompletions_Stream.class);
	private static final ObjectMapper MAPPER = new ObjectMapper();
	
	/**
	 * Builds the response stream handler that processes incoming chunks
	 */
	private OpenAIStreamResponseHandler buildResponseHandler() {
		return new OpenAIStreamResponseHandler(
			getContext(),
			RequestID,
			CallbackMicroflow,
			LOGGER
		);
	}
	
	/**
	 * Executes the async streaming request
	 * This method handles the actual HTTP streaming communication with OpenAI
	 */
	private void executeStreamingRequest(OpenAIStreamResponseHandler responseHandler) {
		try {
			// TODO: Implement actual OpenAI API streaming call
			// The implementation should:
			// 1. Make HTTP request to OpenAI API with streaming enabled
			// 2. Process each chunk as it arrives by calling responseHandler.onContentChunk(chunk)
			// 3. Call responseHandler.onStreamComplete() when done
			// 4. Call responseHandler.onStreamError(error) if an error occurs
			
			LOGGER.warn("Streaming request execution not yet implemented");
			responseHandler.onStreamError(new UnsupportedOperationException("Streaming not yet implemented"));
		} catch (Exception e) {
			LOGGER.error("Error executing streaming request: " + e.getMessage(), e);
			responseHandler.onStreamError(e);
		}
	}
	
	/**
	 * Notifies the callback microflow of any errors
	 */
	private void notifyCallbackOnError(Exception e) {
		try {
			Core.microflowCall(CallbackMicroflow)
				.withParam("RequestId", RequestID)
				.withParam("Content", "ERROR: " + e.getMessage())
				.execute(getContext());
		} catch (Exception callbackError) {
			LOGGER.error("Failed to notify callback of error: " + callbackError.getMessage(), callbackError);
		}
	}
	
	// END EXTRA CODE
}
