// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

/**
 * Parses a single SSE message block into its fields.
 * @param {string} message
 * @returns {{ data: string, throwError: boolean }}
 */
function parseSseMessage(message) {
	const lines = message.replace(/\r\n/g, "\n").split("\n").filter(line => line.trim() !== "");
	let data = "";
	let throwError = false;

	for (const line of lines) {
		if (line.startsWith("data:")) {
			// data lines can be multi-line; accumulate them
			data += line.substring(5).trim();
		} else if (line.startsWith("throwError:")) {
			throwError = line.substring(11).trim() === "true";
		}
	}

	return { data, throwError };
}

/**
 * Decodes a base64-encoded, UTF-8 SSE data payload into text.
 * @param {string} data
 * @returns {string}
 */
function decodeBase64ToText(data) {
	const binary = atob(data);
	const bytes = Uint8Array.from(binary, c => c.charCodeAt(0));
	return new TextDecoder("utf-8").decode(bytes);
}

/**
 * Scrolls the messages container to the bottom, unless the user has scrolled up.
 * Batched with requestAnimationFrame to avoid layout thrash during streaming.
 */
function scrollMessagesToBottom() {
	if (window.scrollPending) {
		return;
	}
	window.scrollPending = true;
	requestAnimationFrame(() => {
		const container = document.querySelector(".messages-container");
		if (container && !container.classList.contains("not-at-bottom")) {
			container.scrollTop = container.scrollHeight; // instant, no 'smooth'
		}
		window.scrollPending = false;
	});
}

// END EXTRA CODE

/**
 * @param {MxObject} streamMessage
 * @param {string} chatContextGUID
 * @returns {Promise.<undefined|"Success"|"Error"|"NotFound">}
 */
export async function JS_SubmitChatForStreaming(streamMessage, chatContextGUID) {
	// BEGIN USER CODE
	const baseUrl = mx.appUrl;
	const endpoint = `${baseUrl}llm-streaming`;
	const response = await fetch(endpoint, {
		method: "POST",
		headers: {			
			"Content-Type": "application/json",
			"Accept": "text/event-stream"
		},
		body: JSON.stringify({
			chatContextGUID: chatContextGUID
		})
	})

	// Check if the response status is 404
	if (response.status == 404) {
		console.debug(`The URL '${endpoint}' could not be found (HTTP 404). This might indicate that the request handler was not registered correctly.`);
		return "NotFound";
	}

	const reader = response.body.getReader();
	const decoder = new TextDecoder("utf-8");
	let buffer = ""; // accumulates incomplete SSE messages across chunks

	// Applies one complete SSE message to the stream message object.
	const processSseMessage = (message) => {
		const { data, throwError } = parseSseMessage(message);

		if (throwError) {
			throw new Error();
		}
		if (data) {
			const decodedData = decodeBase64ToText(data);
			const currentText = streamMessage.get("Content");
			streamMessage.set("Content", currentText + decodedData);
			scrollMessagesToBottom();
		}
	};

	try {
		while (true) {
			const { done, value } = await reader.read();

			if (done) {
				console.log("Stream finished.");
				break;
			}

			// Decode the chunk and add to buffer
			buffer += decoder.decode(value, { stream: true });
			buffer = buffer.replace(/\r\n/g, "\n");

			// SSE messages are terminated by two newline characters (\n\n)
			let messageEndIndex;
			while ((messageEndIndex = buffer.indexOf("\n\n")) !== -1) {
				const message = buffer.substring(0, messageEndIndex);
				processSseMessage(message);
				buffer = buffer.substring(messageEndIndex + 2);
			}
		}
		return "Success";
	} catch (error) {
		return "Error";
	}

	// END USER CODE
}
