// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conversationalui.actions;

import genaicommons.impl.MxLogger;
import java.util.List;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.externalinterface.connector.RequestHandler;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class InitAsyncStreamHandler extends UserAction<java.lang.Void>
{
	public InitAsyncStreamHandler(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		Core.addRequestHandler("llm", new RequestHandler() {
			@Override
			protected void processRequest(IMxRuntimeRequest req, IMxRuntimeResponse resp, String s) throws Exception {
				
				LOGGER.info("InitAsyncStreamHandler: Request handler started");
	            // Parse JSON request body
	            String jsonInput = new String(req.getInputStream().readAllBytes());
	            ObjectMapper objectMapper = new ObjectMapper();
	            try {
	            	JsonNode jsonRequest = objectMapper.readTree(jsonInput);
	                // Extract fields from JSON
	                String requestJSON = jsonRequest.get("request").asText();
	                String deployedModel = jsonRequest.get("deployedModel").asText();
	                
	                // Create system context
	                IContext ctx = Core.createSystemContext();
	                
	                // Retrieve deployed model from database using Model
	                List<IMendixObject> results = Core.createXPathQuery("//GenAICommons.DeployedModel[Model=$value]")
	                        .setVariable("value", deployedModel)
	                        .execute(ctx);
	                
	                if (results.isEmpty()) {
	                    LOGGER.error("Deployed model not found for: " + deployedModel);
	                    resp.getHttpServletResponse().setStatus(404);
	                    // NOTE: not sure about this write to output stream part
	                    resp.getOutputStream().write("Deployed model not found".getBytes());
	                    return;
	                }
	                
	                genaicommons.proxies.DeployedModel mxDeployedModel = genaicommons.proxies.DeployedModel.initialize(ctx, results.get(0));
	                LOGGER.info("Successfully retrieved deployed model: " + mxDeployedModel.getModel());
	                
	                // Construct GenAICommons.Request object from JSON!!!!
	            	
	            } catch (Exception e) {
	            	
	            }
				
			}
		});
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InitAsyncStreamHandler";
	}

	// BEGIN EXTRA CODE
	 private static final MxLogger LOGGER = new MxLogger(InitAsyncStreamHandler.class);
	// END EXTRA CODE
}
