// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conversationalui.actions;

import conversationalui.impl.MxLogger;
import conversationalui.impl.ProviderConfigImpl;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;
import genaicommons.impl.ResponseConnectionController;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.externalinterface.connector.RequestHandler;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Initializes the request handler that acts as the entry point for the streaming request from the UI and opens the SSE connection for the response stream. 
 */
public class InitAsyncStreamHandler extends UserAction<java.lang.Void>
{
	public InitAsyncStreamHandler(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		Core.addRequestHandler("llm-streaming", new RequestHandler() {
			@Override
			protected void processRequest(IMxRuntimeRequest req, IMxRuntimeResponse resp, String s) throws Exception {
				
				LOGGER.debug("Request handler started.");
				
                // Configure response for Server-Sent Events
                resp.setContentType("text/event-stream");
                resp.getHttpServletResponse().setStatus(200);
                LOGGER.debug("Configure response for Server-Sent Event");

                // Generate unique request ID for streaming
                String streamingResponseWriterId = UUID.randomUUID().toString();
                ResponseConnectionController.getInstance().addStreamingResponseWriter(streamingResponseWriterId,
                        new ResponseConnectionController.StreamingResponseWriter(resp.getOutputStream()));
                LOGGER.debug("Generated unique request ID for streaming");
                
	            // Parse JSON request body
	            String jsonInput = new String(req.getInputStream().readAllBytes());
	            ObjectMapper objectMapper = new ObjectMapper();
	            try {
	            	JsonNode jsonRequest = objectMapper.readTree(jsonInput);
	            	
	                // Extract fields from JSON
	                String chatContextGUID = jsonRequest.get("chatContextGUID").asText();
	                
	                // Create user context from session
	                IContext ctx = create_userContext_from_session(req);
	                
	                // Retrieve chat context from database using guid
	                conversationalui.proxies.ChatContext mxChatContext = get_chatContext(ctx, chatContextGUID, resp);
	                 
	                // Retrieve version from chat context
	                agentcommons.proxies.Version mxVersion = conversationalui.proxies.microflows.Microflows.chatContext_GetVersion(getContext(), mxChatContext);
	                
	                if (mxVersion == null) {
	                    resp.getHttpServletResponse().setStatus(400);
	                    throw new NullPointerException("Version could not be found.");
	                }
	                
	                if (mxVersion.getVersion_DeployedModel() == null) {
	                    resp.getHttpServletResponse().setStatus(400);
	                    throw new NullPointerException("Deployed Model could not be found.");
	                }
	                
	                // Set StreamingResponseWriterId to request to stream to UI
	                mxChatContext.setStreamingResponseWriterId(streamingResponseWriterId);
	                
	                boolean isAgentBuilderTest = agentcommons.proxies.microflows.Microflows.chatContext_IsAgentEditor(ctx, mxChatContext);
	                Boolean isSuccess = true;
	                
	                if (isAgentBuilderTest) {
	                	
	                	isSuccess = agentcommons.proxies.microflows.Microflows.chatContext_Streaming_ActionMicroflow_AgentBuilder(ctx, mxChatContext);
	                	
	                } else {
	                	
		                conversationalui.proxies.ProviderConfig mxProviderConfig = mxChatContext.getChatContext_ProviderConfig_Active();
		                
		                ProviderConfigImpl.validateActionMicroflow(mxProviderConfig.getActionMicroflow());
		    			String chatContextParameterString = Core.getInputParameters(mxProviderConfig.getActionMicroflow()).keySet().iterator().next();
		    			
		    			isSuccess = Core.microflowCall(mxProviderConfig.getActionMicroflow()).withParam(chatContextParameterString, mxChatContext).execute(ctx);
	    			}
	                
	    			if (!isSuccess) {
	                    resp.getHttpServletResponse().setStatus(500);
	                    LOGGER.debug("There was a problem while running the ActionMicroflow.");
		            	genaicommons.impl.StreamingImpl.throwError(getContext(),resp.getOutputStream());
	                    ResponseConnectionController.getInstance().removeStreamingResponseWriter(streamingResponseWriterId);
	                    return;
	                }
	    			
					// Remove ResponseConnectionController instance
					ResponseConnectionController.getInstance().removeStreamingResponseWriter(streamingResponseWriterId);
					LOGGER.debug("Request handler closed.");
	            	
	            } catch (Exception e) {
	            	LOGGER.error(e);
	            	genaicommons.impl.StreamingImpl.throwError(getContext(),resp.getOutputStream());
                    ResponseConnectionController.getInstance().removeStreamingResponseWriter(streamingResponseWriterId);
	            }
				
			}
		});
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InitAsyncStreamHandler";
	}

	// BEGIN EXTRA CODE
	 private static final MxLogger LOGGER = new MxLogger(InitAsyncStreamHandler.class);
	 
	 private static IContext create_userContext_from_session(IMxRuntimeRequest req) {
		 
		 String sessionId;
         String host = req.getHeader("Host");
         if (host.contains("localhost")) {
         	sessionId = req.getCookie("XASSESSIONID");
         } else {
         	sessionId = req.getCookie("__Host-XASSESSIONID");
         }
         ISession session = Core.getSessionById(UUID.fromString(sessionId));
         IContext ctx = session.createContext();
         
         return ctx;
	 }
	 
	 private static conversationalui.proxies.ChatContext get_chatContext(IContext ctx, String chatContextGUID, IMxRuntimeResponse resp) {
		 
		 List<IMendixObject> resultsChatContext = Core.createXPathQuery("//ConversationalUI.ChatContext[id=$value]")
                 .setVariable("value", chatContextGUID)
                 .execute(ctx);
         
         if (resultsChatContext.isEmpty()) {
             resp.getHttpServletResponse().setStatus(400);
             throw new NullPointerException("Chat context not found for: " + chatContextGUID);
         }
         
         conversationalui.proxies.ChatContext mxChatContext = conversationalui.proxies.ChatContext.initialize(ctx, resultsChatContext.get(0));
		 
		 return mxChatContext;
	 }
	 
	// END EXTRA CODE
}
