// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conversationalui.actions;

import conversationalui.impl.MxLogger;
import java.util.List;
import java.util.UUID;
import genaicommons.impl.ResponseConnectionController;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.externalinterface.connector.RequestHandler;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.UserAction;

public class InitAsyncStreamHandler extends UserAction<java.lang.Void>
{
	public InitAsyncStreamHandler(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		Core.addRequestHandler("llm-streaming", new RequestHandler() {
			@Override
			protected void processRequest(IMxRuntimeRequest req, IMxRuntimeResponse resp, String s) throws Exception {
				
				LOGGER.info("Request handler started");
	            // Parse JSON request body
	            String jsonInput = new String(req.getInputStream().readAllBytes());
	            ObjectMapper objectMapper = new ObjectMapper();
	            try {
	            	JsonNode jsonRequest = objectMapper.readTree(jsonInput);
	            	
	                // Extract fields from JSON
	                String chatContextGUID = jsonRequest.get("chatContextGUID").asText();
	                
	                // Create user context from session
	                String sessionId = req.getCookie("XASSESSIONID");
	                ISession session = Core.getSessionById(UUID.fromString(sessionId));
	                IContext ctx = session.createContext();
	                
	                // Retrieve chat context from database using id
	                List<IMendixObject> resultsChatContext = Core.createXPathQuery("//ConversationalUI.ChatContext[id=$value]")
	                        .setVariable("value", chatContextGUID)
	                        .execute(ctx);
	                
	                if (resultsChatContext.isEmpty()) {
	                    LOGGER.error("Chat context not found for: " + chatContextGUID);
	                    resp.getHttpServletResponse().setStatus(404);
	                    genaicommons.impl.StreamingImpl.throwError(ctx,resp.getOutputStream());
	                    return;
	                }
	                
	                conversationalui.proxies.ChatContext mxChatContext = conversationalui.proxies.ChatContext.initialize(ctx, resultsChatContext.get(0));
	                
	                agentcommons.proxies.Version mxVersion = new agentcommons.proxies.Version(getContext());
	                
	                if (mxChatContext.getChatContext_Version() == null && mxChatContext.getChatContext_Agent().getAgent_Version_InUse() == null) {
	                	mxVersion = null;
	                }
	                else if (mxChatContext.getChatContext_Version() == null) {
	                	mxVersion = mxChatContext.getChatContext_Agent().getAgent_Version_InUse();
	                			
	                } else {
	                	mxVersion = mxChatContext.getChatContext_Version();
	                }
	                
	                if (mxVersion == null) {
	                    LOGGER.error("Version could not be found.");
	                    resp.getHttpServletResponse().setStatus(404);
	                    genaicommons.impl.StreamingImpl.throwError(ctx,resp.getOutputStream());
	                    return;
	                }
	                
	                if (mxVersion.getVersion_DeployedModel() == null) {
	                    LOGGER.error("Deployed Model could not be found.");
	                    resp.getHttpServletResponse().setStatus(404);
	                    genaicommons.impl.StreamingImpl.throwError(ctx,resp.getOutputStream());
	                    return;
	                }

	                // Construct request from ChatContex by using PreProcessing microflow
	                IMendixObject mxRequestObject = Core.microflowCall(mxVersion.getStreamingPreProcess())
							.withParam("ChatContext", mxChatContext)
							.execute(ctx);
	                
	                genaicommons.proxies.Request mxRequest = genaicommons.proxies.Request.initialize(ctx, mxRequestObject);
	                
	                if (mxRequest == null) {
	                    LOGGER.error("Request could not be created from ChatContext by running the PreProcessing microflow.");
	                    resp.getHttpServletResponse().setStatus(404);
	                    genaicommons.impl.StreamingImpl.throwError(ctx,resp.getOutputStream());
	                    return;
	                }

	                LOGGER.debug("Successfully created Request " + mxRequest);
	                
	                // Configure response for Server-Sent Events
	                resp.setContentType("text/event-stream");
	                resp.getHttpServletResponse().setStatus(200);
	                
	                LOGGER.debug("Configure response for Server-Sent Event");

	                // Generate unique request ID for streaming
	                String connectionId = UUID.randomUUID().toString();
	                ResponseConnectionController.getInstance().addStreamingResponseWriter(connectionId,
	                        new ResponseConnectionController.StreamingResponseWriter(resp.getOutputStream()));
	                
	                LOGGER.debug("Generate unique request ID for streaming");
	                
	                mxRequest.setStreamingResponseWriterId(connectionId);
						
					genaicommons.proxies.Response mxResponse = genaicommons.proxies.microflows.Microflows.chatCompletions_WithHistory(ctx, mxRequest, mxVersion.getVersion_DeployedModel());
					
					if (mxResponse == null) {
	                    LOGGER.error("There was an issue when calling the Chat Completions API, no response was returned.");
	                    resp.getHttpServletResponse().setStatus(404);
	                    genaicommons.impl.StreamingImpl.throwError(ctx,resp.getOutputStream());
	                    ResponseConnectionController.getInstance().removeStreamingResponseWriter(connectionId);
	                    return;
	                }
					
					LOGGER.debug("Chat with history completed.");
					
					// run Post Processing microflow with ChatContext and Reponse
					Core.microflowCall(mxVersion.getStreamingPostProcess())
							.withParam("Response", mxResponse)
							.withParam("ChatContext", mxChatContext)
							.execute(ctx);
					
					ResponseConnectionController.getInstance().removeStreamingResponseWriter(connectionId);
	            	
	            } catch (Exception e) {
	            	LOGGER.error(e);
	            	genaicommons.impl.StreamingImpl.throwError(getContext(),resp.getOutputStream());
	            }
				
			}
		});
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InitAsyncStreamHandler";
	}

	// BEGIN EXTRA CODE
	 private static final MxLogger LOGGER = new MxLogger(InitAsyncStreamHandler.class);
	// END EXTRA CODE
}
