// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conversationalui.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import conversationalui.impl.MxLogger;
import java.util.List;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

public class Request_ExportToJSON extends UserAction<java.lang.String>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;

	public Request_ExportToJSON(
		IContext context,
		IMendixObject _request
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			String requestJSON = conversationalui.proxies.microflows.Microflows.request_ExportToJSON_Basic(getContext(), this.Request);
			if (this.Request.getRequest_ToolCollection() != null && this.Request.getRequest_ToolCollection().getToolCollection_Tool() != null) {
				List<genaicommons.proxies.Tool> mxToolList = this.Request.getRequest_ToolCollection().getToolCollection_Tool();
				genaicommons.proxies.Tool mxTool_ToolChoice = this.Request.getRequest_ToolCollection().getToolCollection_ToolChoice();
				for (genaicommons.proxies.Tool mxTool : mxToolList) {
				    String toolJSON;
				    
				    switch (mxTool.getInternalToolType()) {
					
				    case MCP:
						toolJSON = Core.microflowCall("MCPClient.MCP_ExportToJSON")
								.withParam("Tool", mxTool)
								.execute(this.getContext());
						if (toolJSON == null) {
							LOGGER.info("There was a problem while export mapping Tool " + mxTool.getName() + ". Because of this issue, this tool was not added to the request.");
						} else {
							toolJSON = addToolChoice(mxTool_ToolChoice, mxTool, toolJSON);
							requestJSON = addTool(requestJSON, toolJSON);
						}
						break;
						
					case KnowledgeBaseRetrieval:
						toolJSON = Core.microflowCall("ConversationalUI.KnowledgeBaseRetrieval_ExportToJSON")
								.withParam("Tool", mxTool)
								.execute(this.getContext());
						if (toolJSON == null) {
							LOGGER.info("There was a problem while export mapping Tool " + mxTool.getName() + ". Because of this issue, this tool was not added to the request.");
						} else {
							toolJSON = addToolChoice(mxTool_ToolChoice, mxTool, toolJSON);
							toolJSON = addDeployedKnowledgeBaseName(mxTool,toolJSON);
							requestJSON = addTool(requestJSON, toolJSON);
						}
						break;
						
					case null:
						
						break;

					default:
						toolJSON = Core.microflowCall("ConversationalUI.Tool_ExportToJSON")
							.withParam("Tool", mxTool)
							.execute(this.getContext());
						if (toolJSON == null) {
							LOGGER.info("There was a problem while export mapping Tool " + mxTool.getName() + ". Because of this issue, this tool was not added to the request.");
						} else {
							toolJSON = addToolChoice(mxTool_ToolChoice, mxTool, toolJSON);
							requestJSON = addTool(requestJSON, toolJSON);
						}
						break;
					}
					
				}
				
				
			}
			
			
			return requestJSON;
			
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ExportToJSON";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Request_ExportToJSON.class);
	
	private static final ObjectMapper MAPPER = new ObjectMapper();
	
	private static String addTool(String requestJson, String toolJson) throws Exception {
        ObjectNode root = (ObjectNode) MAPPER.readTree(requestJson);
        JsonNode toolNode = MAPPER.readTree(toolJson);

        if (!toolNode.isObject()) {
            LOGGER.error("toolJson must be a JSON object");
            return null;
        }

        ObjectNode toolCollection;
        JsonNode toolCollectionNode = root.get("toolCollection");

        if (toolCollectionNode == null || toolCollectionNode.isNull()) {
            toolCollection = MAPPER.createObjectNode();
            root.set("toolCollection", toolCollection);
        } else if (toolCollectionNode.isObject()) {
            toolCollection = (ObjectNode) toolCollectionNode;
        } else {
        	LOGGER.error("toolCollection exists but is not an object");
        	return null;
        }

        ArrayNode tools;
        JsonNode toolsNode = toolCollection.get("tools");

        if (toolsNode == null || toolsNode.isNull()) {
            tools = MAPPER.createArrayNode();
            toolCollection.set("tools", tools);
        } else if (toolsNode.isArray()) {
            tools = (ArrayNode) toolsNode;
        } else {
        	LOGGER.error("toolCollection.tools exists but is not an array");
        	return null;
        }

        tools.add(toolNode);
        return MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(root);
    }
	
	private static String addToolChoice(genaicommons.proxies.Tool mxTool_ToolChoice, genaicommons.proxies.Tool mxTool, String toolJson) throws Exception {
		
		ObjectNode toolNode = (ObjectNode) MAPPER.readTree(toolJson);
		if (mxTool_ToolChoice != null && mxTool.getName() == mxTool_ToolChoice.getName()) {
	        toolNode.put("isToolChoice", true);
	        return MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(toolNode);
		} else {
			 toolNode.put("isToolChoice", false);
		        return MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(toolNode);

		}
		
	}
	
	private static String addDeployedKnowledgeBaseName(genaicommons.proxies.Tool mxTool, String toolJson) throws Exception {

		genaicommons.proxies.KnowledgeBaseRetrieval mxKnowledgeBaseRetrieval = (genaicommons.proxies.KnowledgeBaseRetrieval) mxTool;
		ObjectNode toolNode = (ObjectNode) MAPPER.readTree(toolJson);
        toolNode.put("DeployedKnowledgeBaseName", mxKnowledgeBaseRetrieval.getKnowledgeBaseRetrieval_DeployedKnowledgeBase().getName());
        return MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(toolNode);

	}
	// END EXTRA CODE
}
