// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package conversationalui.actions;

import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import conversationalui.impl.MxLogger;

public class Request_ImportFromJSON extends UserAction<IMendixObject>
{
	private final java.lang.String RequestJSONBody;

	public Request_ImportFromJSON(
		IContext context,
		java.lang.String _requestJSONBody
	)
	{
		super(context);
		this.RequestJSONBody = _requestJSONBody;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			genaicommons.proxies.Request mxRequest = conversationalui.proxies.microflows.Microflows.request_ImportFromJSON_Basic(getContext(), this.RequestJSONBody);
			ArrayNode tools = getToolJSONBodies(this.RequestJSONBody);
			if (tools == null) {
				LOGGER.debug("No tools have been found in the Request JSON body.");
			} else {
				genaicommons.proxies.ToolCollection mxToolCollection = new genaicommons.proxies.ToolCollection(getContext());
				List<genaicommons.proxies.Tool> mxToolList = new ArrayList<>();
				for (JsonNode tool : tools) {
					IMendixObject mxObject;
					genaicommons.proxies.Tool mxTool;
					String toolJSON = MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(tool);
					switch (tool.get("internalToolType").asText()) {
					
					case "MCP":
						mxObject = Core.microflowCall("MCPClient.MCP_ImportFromJSON")
							.withParam("ToolJSON", toolJSON)
							.execute(this.getContext());
						mxTool = genaicommons.proxies.Tool.load(getContext(), mxObject.getId());
						mxToolList.add(mxTool);
						break;
						
					case "KnowledgeBaseRetrieval":
						mxObject = Core.microflowCall("ConversationalUI.KnowledgeBaseRetrieval_ImportFromJSON")
							.withParam("ToolJSON", toolJSON)
							.execute(this.getContext());
						mxTool = genaicommons.proxies.Tool.load(getContext(), mxObject.getId());
						genaicommons.proxies.KnowledgeBaseRetrieval mxKnowledgeBaseRetrieval = (genaicommons.proxies.KnowledgeBaseRetrieval) mxTool;
							
						// Retrieve deployed KB from database using name
		                List<IMendixObject> results = Core.createXPathQuery("//GenAICommons.DeployedKnowledgeBase[Name=$value]")
		                        .setVariable("value", tool.get("DeployedKnowledgeBaseName").asText())
		                        .execute(getContext());
		                
		                genaicommons.proxies.DeployedKnowledgeBase mxDeployedKnowledgeBase = genaicommons.proxies.DeployedKnowledgeBase.initialize(getContext(), results.get(0));
		                
		                mxKnowledgeBaseRetrieval.setKnowledgeBaseRetrieval_DeployedKnowledgeBase(mxDeployedKnowledgeBase);
						mxToolList.add(mxKnowledgeBaseRetrieval);
						break;

					default:
						mxObject = Core.microflowCall("ConversationalUI.Tool_ImportFromJSON")
							.withParam("ToolJSON", toolJSON)
							.execute(this.getContext());
						mxTool = genaicommons.proxies.Tool.load(getContext(), mxObject.getId());
						mxToolList.add(mxTool);
						break;
					}
					setToolChoice(mxToolCollection, mxTool, tool.get("isToolChoice").asBoolean());
					
				}
				mxToolCollection.setToolCollection_Tool(mxToolList);
				mxRequest.setRequest_ToolCollection(mxToolCollection);
			}
			LOGGER.debug("Request created.");
			return mxRequest.getMendixObject();
			
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ImportFromJSON";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Request_ImportFromJSON.class);
	
	private static final ObjectMapper MAPPER = new ObjectMapper();
	
	private static ArrayNode getToolJSONBodies(String requestJSON) throws Exception {
		// Parse the JSON body
        JsonNode root = MAPPER.readTree(requestJSON);
        JsonNode toolsNode = root.path("toolCollection").path("tools");

        // Check if tools exist and are an array
        if (toolsNode.isArray()) {
            ArrayNode tools = (ArrayNode) toolsNode;
            return tools;
        } else {
            return null;
        }
	}
	
	private static void setToolChoice(genaicommons.proxies.ToolCollection mxToolCollection, genaicommons.proxies.Tool mxTool, Boolean isToolChoice) {
		
		if (isToolChoice) {
			mxToolCollection.setToolCollection_ToolChoice(mxTool);
		}
		
	}
	// END EXTRA CODE
}
