// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agentcommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import agentcommons.impl.MxLogger;
import agentcommons.proxies.PromptToUse;

public class Agent_Call_WithHistory extends UserAction<IMendixObject>
{
	/** @deprecated use Agent.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Agent;
	private final agentcommons.proxies.Agent Agent;
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	private final IMendixObject OptionalContextObject;

	public Agent_Call_WithHistory(
		IContext context,
		IMendixObject _agent,
		IMendixObject _request,
		IMendixObject _optionalContextObject
	)
	{
		super(context);
		this.__Agent = _agent;
		this.Agent = _agent == null ? null : agentcommons.proxies.Agent.initialize(getContext(), _agent);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.OptionalContextObject = _optionalContextObject;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try{
			requireNonNull(Agent, "Agent is required.");
			IMendixObject promptObject = Core.userActionCall("AgentCommons." + PromptToUse_GetAndReplace.class.getSimpleName())
					.withParams(Agent.getMendixObject(), OptionalContextObject)
					.execute(getContext());
			if (promptObject == null)
				return null;
			PromptToUse promptToUse = PromptToUse.initialize(getContext(), promptObject);
			agentcommons.proxies.microflows.Microflows.request_AddAgentCapabilities(getContext(), Request, promptToUse);
			return genaicommons.proxies.microflows.Microflows.chatCompletions_WithHistory(getContext(), Request, Agent.getAgent_DeployedModel()).getMendixObject();
			
		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Agent_Call_WithHistory";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Agent_Call_WithHistory.class);
	// END EXTRA CODE
}
