// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agentcommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import agentcommons.impl.MxLogger;

/**
 * Returns true if a microflow with the passed name exists.
 */
public class Tool_FindMicroflow extends UserAction<java.lang.Boolean>
{
	private final java.lang.String MicroflowName;

	public Tool_FindMicroflow(
		IContext context,
		java.lang.String _microflowName
	)
	{
		super(context);
		this.MicroflowName = _microflowName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(MicroflowName, "MicroflowName is required.");
			
			return Core.getMicroflowNames().stream()
					.filter(name -> name.equals(MicroflowName))
					.collect(Collectors.toList()).size() > 0;
		} catch (Exception e) {
			LOGGER.error(e);
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Tool_FindMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Tool_FindMicroflow.class);
	// END EXTRA CODE
}
