// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agentcommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import agentcommons.impl.MxLogger;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Version_SetMicroflow extends UserAction<java.lang.Void>
{
	/** @deprecated use Version.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Version;
	private final agentcommons.proxies.Version Version;
	private final java.lang.String Microflow;
	private final java.lang.Boolean isPreprocessing;

	public Version_SetMicroflow(
		IContext context,
		IMendixObject _version,
		java.lang.String _microflow,
		java.lang.Boolean _isPreprocessing
	)
	{
		super(context);
		this.__Version = _version;
		this.Version = _version == null ? null : agentcommons.proxies.Version.initialize(getContext(), _version);
		this.Microflow = _microflow;
		this.isPreprocessing = _isPreprocessing;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Microflow, "Microflow is required.");
			
			
			return null;
		} catch (Exception e) {
			LOGGER.error(e);
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Version_SetMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Version_SetMicroflow.class);
	// END EXTRA CODE
}
