// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agentcommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.HashMap;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.UserAction;
import agentcommons.impl.MxLogger;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Version_SetMicroflow extends UserAction<java.lang.Void>
{
	/** @deprecated use Version.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Version;
	private final agentcommons.proxies.Version Version;
	private final java.lang.String Microflow;
	private final java.lang.Boolean isPreprocessing;

	public Version_SetMicroflow(
		IContext context,
		IMendixObject _version,
		java.lang.String _microflow,
		java.lang.Boolean _isPreprocessing
	)
	{
		super(context);
		this.__Version = _version;
		this.Version = _version == null ? null : agentcommons.proxies.Version.initialize(getContext(), _version);
		this.Microflow = _microflow;
		this.isPreprocessing = _isPreprocessing;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Microflow, "Microflow is required.");
			
			validate();
			
			if (this.isPreprocessing) {
				this.Version.setStreamingPreProcess(this.Microflow);
			} else {
				this.Version.setStreamingPostProcess(this.Microflow);
			}
			
			return null;
		} catch (Exception e) {
			LOGGER.error(e);
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Version_SetMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Version_SetMicroflow.class);
	
	private void validate() {
		 if (this.isPreprocessing) {
			 
			java.util.Map<String, IDataType> inputParameters = new HashMap<>();
			inputParameters.put("ChatContext", Core.createDataType("ConversationalUI.ChatContext"));
			
			if (!Core.getInputParameters(this.Microflow).equals(inputParameters)) {
				throw new IllegalArgumentException("Microflow selected as preprocessing microflow for streaming must have one input variable of type ConversationalUI.ChatContext.");
				}
			if (!Core.getReturnType(this.Microflow).getType().equals(IDataType.DataTypeEnum.Object) || !Core.getReturnType(this.Microflow).getObjectType().equals("GenAICommons.Request")) {
				throw new IllegalArgumentException("Microflow selected as preprocessing microflow for streaming must have one return variable of type GenAICommons.Request.");
			}
		 } else {
		 
		 java.util.Map<String, IDataType> inputParameters = new HashMap<>();
			inputParameters.put("Response", Core.createDataType("GenAICommons.Response"));
			inputParameters.put("ChatContext", Core.createDataType("ConversationalUI.ChatContext"));
			
			if (!Core.getInputParameters(this.Microflow).equals(inputParameters)) {
				throw new IllegalArgumentException("Microflow selected as preprocessing microflow for streaming must have two input variables with them being of type ConversationalUI.ChatContext and GenAICommons.Response.");
				}
			
			if (!Core.getReturnType(this.Microflow).getType().equals(IDataType.DataTypeEnum.Nothing)) {
				throw new IllegalArgumentException("Microflow selected as postprocessing microflow for streaming must have no return value.");
			}
		 }
		
	}
	// END EXTRA CODE
}
