// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package openaiconnector.actions;

import static java.util.Objects.requireNonNull;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.openai.client.OpenAIClient;
import com.openai.client.okhttp.OpenAIOkHttpClient;
import com.openai.core.JsonValue;
import com.openai.models.chat.completions.ChatCompletionStreamOptions;
import com.openai.models.chat.completions.ChatCompletionMessageParam;
import com.openai.models.chat.completions.ChatCompletionNamedToolChoice;
import com.openai.models.chat.completions.ChatCompletionUserMessageParam;
import com.openai.models.chat.completions.ChatCompletionSystemMessageParam;
import com.openai.models.chat.completions.ChatCompletionToolMessageParam;
import com.openai.models.FunctionDefinition;
import com.openai.models.chat.completions.ChatCompletionAssistantMessageParam;
import com.openai.models.chat.completions.ChatCompletionMessageToolCall;
import com.openai.models.chat.completions.ChatCompletionMessageFunctionToolCall;
import com.openai.models.chat.completions.ChatCompletionCreateParams;
import com.openai.models.chat.completions.ChatCompletionFunctionTool;
import com.openai.models.chat.completions.ChatCompletionChunk;
import com.openai.models.chat.completions.ChatCompletionTool;
import com.openai.models.chat.completions.ChatCompletionToolChoiceOption;
import com.openai.models.chat.completions.ChatCompletionContentPart;
import com.openai.models.chat.completions.ChatCompletionContentPartImage;
import com.openai.models.chat.completions.ChatCompletionContentPartText;
import genaicommons.proxies.ENUM_ContentType;
import genaicommons.proxies.ENUM_FileType;
import genaicommons.proxies.FileCollection;
import genaicommons.proxies.FileContent;
import genaicommons.impl.FunctionImpl;
import genaicommons.impl.FunctionMappingImpl;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.ENUM_MessageRole;
import genaicommons.proxies.ENUM_ToolChoice;
import genaicommons.proxies.Request;
import genaicommons.proxies.Tool;
import genaicommons.proxies.ToolCollection;
import openaiconnector.proxies.Configuration;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Request_ChatCompletions_Stream extends UserAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use DeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedModel;
	private final openaiconnector.proxies.OpenAIDeployedModel DeployedModel;

	public Request_ChatCompletions_Stream(
		IContext context,
		IMendixObject _request,
		IMendixObject _deployedModel
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__DeployedModel = _deployedModel;
		this.DeployedModel = _deployedModel == null ? null : openaiconnector.proxies.OpenAIDeployedModel.initialize(getContext(), _deployedModel);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(this.Request, "A Request object is required");
			requireNonNull(this.DeployedModel, "A DeployedModel object is required");
			
			// Create OpenAI client with API key from deployed model
			OpenAIClient client = createOpenAIClient();
			
			// Build the chat completion request with streaming enabled
			ChatCompletionCreateParams requestParams = buildChatCompletionRequest();
			
			// Execute the streaming request
			executeStreamingRequest(client, requestParams);
			
			return mxResponse.getMendixObject();
			
		} catch (Exception e) {
			LOGGER.error("An error occurred when calling the streaming API: " + e.getMessage(), e);
			throw e;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ChatCompletions_Stream";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Request_ChatCompletions_Stream.class);
	private static final ObjectMapper MAPPER = new ObjectMapper();

	/**
	 * Creates a new Response object and initializes it
	 */
	
	genaicommons.proxies.Response mxResponse =  new genaicommons.proxies.Response(getContext());
	private final Map<Integer, ToolCallFragments> toolCallAccumulator = new LinkedHashMap<>();
	List<genaicommons.proxies.ToolCall> mxToolCallList = new ArrayList<genaicommons.proxies.ToolCall>();

	/**
	 * Accumulates the id/name/arguments fragments of a single streamed tool call across chunks
	 */
	private static class ToolCallFragments {
		final StringBuilder id = new StringBuilder();
		final StringBuilder name = new StringBuilder();
		final StringBuilder arguments = new StringBuilder();
	}
	
	/**
	 * Creates an OpenAI client using the API key from the deployed model's configuration
	 */
	private OpenAIClient createOpenAIClient() throws Exception {
		// Get the Configuration object via the many-to-one relationship
		Configuration configuration = this.DeployedModel.getOpenAIDeployedModel_Configuration();
		requireNonNull(configuration, "Configuration is required to retrieve API Key");
		
		// Get the encrypted API key from Configuration
		String encryptedApiKey = configuration.getApiKey();
		requireNonNull(encryptedApiKey, "API Key is required in Configuration");
		
		// Decrypt the API key using Encryption module microflow
		String apiKey = encryption.proxies.microflows.Microflows.decrypt(getContext(), encryptedApiKey);
		requireNonNull(apiKey, "Failed to decrypt API Key");
		
		// Get the endpoint from Configuration (optional - for Mistral AI or other OpenAI-compatible APIs)
		String endpoint = configuration.getEndpoint();
		
		// Build the client with optional endpoint
		OpenAIOkHttpClient.Builder clientBuilder = OpenAIOkHttpClient.builder()
			.apiKey(apiKey);
		
		// Add base URL if endpoint is configured (e.g., for Mistral AI)
		if (endpoint != null && !endpoint.trim().isEmpty()) {
			clientBuilder.baseUrl(endpoint);
			LOGGER.debug("Using custom endpoint: " + endpoint);
		}

		LOGGER.debug("OpenAI client created successfully");
		
		return clientBuilder.build();
	}
	
	/**
	 * Builds the ChatCompletionCreateParams request from the GenAICommons.Request
	 * Converts Mendix request object to OpenAI SDK format
	 */
	private ChatCompletionCreateParams buildChatCompletionRequest() throws Exception {
		String model = this.DeployedModel.getModel();
		requireNonNull(model, "Model name is required in DeployedModel");
		
		// Use the request provided to this action
		Request request = this.Request;
		requireNonNull(request, "GenAICommons.Request is required");
		
		// Build messages list from request
		List<ChatCompletionMessageParam> messages = buildMessagesList(request);
		requireNonNull(messages, "Messages list cannot be null");

		if (messages.isEmpty()) {
			LOGGER.warn("Request contains no messages");
		}

		// Prepend the system prompt from the Request, if set
		String systemPrompt = request.getSystemPrompt();
		if (systemPrompt != null && !systemPrompt.isBlank()) {
			messages.add(0, ChatCompletionMessageParam.ofSystem(
				ChatCompletionSystemMessageParam.builder()
					.content(systemPrompt)
					.build()
			));
		}


		// Build the request parameters with streaming enabled
		ChatCompletionCreateParams.Builder builder = ChatCompletionCreateParams.builder()
			.model(model)
			.messages(messages)
			.streamOptions(ChatCompletionStreamOptions.builder()
        		.includeUsage(true)
        		.build());
		
		// Add optional parameters if they exist
		BigDecimal temperature = request.getTemperature();
		if (temperature != null) {
			// Convert BigDecimal to double
			builder.temperature(temperature.doubleValue());
		}
		
		Integer maxTokens = request.getMaxTokens();
		if (maxTokens != null && maxTokens > 0) {
			builder.maxCompletionTokens(maxTokens.longValue());
		}
		
		BigDecimal topP = request.getTopP();
		if (topP != null && topP.signum() > 0) {
			builder.topP(topP.doubleValue());
		}

		List<genaicommons.proxies.StopSequence> stopSequences = request.getRequest_StopSequence();
		if (stopSequences != null && !stopSequences.isEmpty()) {
			List<String> stopStrings = stopSequences.stream()
				.map(genaicommons.proxies.StopSequence::getSequence)
				.collect(java.util.stream.Collectors.toList());
			builder.stop(ChatCompletionCreateParams.Stop.ofStrings(stopStrings));
		}

		applyOpenAIRequestExtension(request, builder);

		// Add tools if a ToolCollection is associated with the request
				ToolCollection toolCollection = request.getRequest_ToolCollection();
				if (toolCollection != null) {
				    List<Tool> tools = toolCollection.getToolCollection_Tool();

				    if (tools != null && !tools.isEmpty()) {
				        List<ChatCompletionTool> toolParams = buildTools(tools);
				        builder.tools(toolParams);
				        LOGGER.debug("Added ",toolParams.size()," tool(s) to the request.");

				        // Apply tool_choice if set on the request
				        ChatCompletionToolChoiceOption toolChoiceParam =
				            buildToolChoice(request, toolCollection);

				        if (toolChoiceParam != null) {
				            builder.toolChoice(toolChoiceParam);
				            LOGGER.debug("Tool choice set to: {}", request.getToolChoice());
				        }
				    } else {
				        LOGGER.debug("ToolCollection is present but contains no tools.");
				    }
				} else {
				    LOGGER.debug("No ToolCollection associated with this request.");
				}	
		
		LOGGER.debug("Chat completion request built successfully with model: " + model);

		return builder.build();
	}

	/**
	 * Applies OpenAI-specific optional parameters (ResponseFormat, FrequencyPenalty) from the
	 * OpenAIRequest_Extension associated to the Request, if present.
	 */
	private void applyOpenAIRequestExtension(Request request, ChatCompletionCreateParams.Builder builder) throws CoreException {
		openaiconnector.proxies.OpenAIRequest_Extension extension =
			openaiconnector.proxies.microflows.Microflows.openAIRequest_Extension_GetOrCreate(getContext(), request);

		if (extension == null) {
			return;
		}

		openaiconnector.proxies.ENUM_ResponseFormat_Chat responseFormat = extension.getResponseFormat();
		if (responseFormat != null) {
			switch (responseFormat) {
				case json_object:
					builder.responseFormat(com.openai.models.ResponseFormatJsonObject.builder().build());
					break;
				case text:
					builder.responseFormat(com.openai.models.ResponseFormatText.builder().build());
					break;
				default:
					LOGGER.warn("Unknown ResponseFormat on OpenAIRequest_Extension: " + responseFormat);
					break;
			}
		}

		BigDecimal frequencyPenalty = extension.getFrequencyPenalty();
		if (frequencyPenalty != null) {
			builder.frequencyPenalty(frequencyPenalty.doubleValue());
		}
	}

	/**
	 * Converts GenAICommons.Request messages to OpenAI SDK ChatCompletionMessage format
	 * Accesses messages via the many-to-many relationship from Request
	 */
	private List<ChatCompletionMessageParam> buildMessagesList(Request request) throws Exception {
		List<ChatCompletionMessageParam> messages = new ArrayList<>();

		List<genaicommons.proxies.Message> messageList = Core.retrieveByPath(getContext(), request.getMendixObject(), genaicommons.proxies.Request.MemberNames.Request_Message.toString())
				.stream()
				.map(mxObj -> genaicommons.proxies.Message.initialize(getContext(), mxObj))
				.collect(java.util.stream.Collectors.toList());

		if (messageList == null || messageList.isEmpty()) {
			LOGGER.warn("No messages found in Request object");
			return messages;
		}

		for (genaicommons.proxies.Message msg : messageList) {
			ENUM_MessageRole role = msg.getRole();
			String content = msg.getContent();

			if (role == ENUM_MessageRole.tool) {

				String toolCallId = msg.getToolCallId();

				// Build Tool Result message
				messages.add(ChatCompletionMessageParam.ofTool(
					ChatCompletionToolMessageParam.builder()
						.toolCallId(toolCallId)
						.content(content != null ? content : "")
						.build()
				));
				LOGGER.debug("Added tool result message for tool_call_id: " + toolCallId);

			} else if (role == ENUM_MessageRole.assistant) {
				// Assistant message — may have text content, tool calls, or both
				List<genaicommons.proxies.ToolCall> toolCalls = msg.getMessage_ToolCall();
				boolean hasToolCalls = toolCalls != null && !toolCalls.isEmpty();
				boolean hasContent = content != null && !content.trim().isEmpty();

				if (!hasContent && !hasToolCalls) {
					LOGGER.warn("buildMessagesList: Skipping assistant message — no content and no tool calls found");
					continue;
				}

				ChatCompletionAssistantMessageParam.Builder builder = ChatCompletionAssistantMessageParam.builder();
				if (hasContent) {
					builder.content(content);
				}
				if (hasToolCalls) {

					// Convert List of Tool Call objects for SDK
					List<ChatCompletionMessageToolCall> sdkToolCalls = toolCalls.stream()
						.map(toolc -> ChatCompletionMessageToolCall.ofFunction(
							ChatCompletionMessageFunctionToolCall.builder()
								.id(toolc.getToolCallId())
								.function(ChatCompletionMessageFunctionToolCall.Function.builder()
									.name(toolc.getName())
									.arguments(toolc.getInput() != null ? toolc.getInput() : "{}")
									.build())
								.build()))
							.toList();
					builder.toolCalls(sdkToolCalls);
				}
				messages.add(ChatCompletionMessageParam.ofAssistant(builder.build()));

			} else {
				// user, system
				if (role == ENUM_MessageRole.user && hasFiles(msg)) {
					LOGGER.debug("Message with Files found");
					messages.add(buildUserMessageWithFiles(msg, content));
				} else {
					if (content == null || content.trim().isEmpty()) {
						LOGGER.warn("buildMessagesList: Skipping " + role + " message with empty content");
						continue;
					}
					messages.add(convertRoleToMessageParam(role, content));
				}
			}
		}

		LOGGER.debug("buildMessagesList: final message count sent to API = " + messages.size());

		return messages;
	}
	
	/**
	 * Converts a Mendix Message role (user/system; assistant/tool are handled separately
	 * in buildMessagesList) to an OpenAI SDK ChatCompletionMessageParam
	 */
	private ChatCompletionMessageParam convertRoleToMessageParam(ENUM_MessageRole role, String content) {
		if (role == null) {
			LOGGER.debug("Role is null, defaulting to USER");
			return ChatCompletionMessageParam.ofUser(
				ChatCompletionUserMessageParam.builder()
					.content(content)
					.build()
			);
		}

		return switch (role) {
			case system -> ChatCompletionMessageParam.ofSystem(
				ChatCompletionSystemMessageParam.builder()
					.content(content)
					.build()
			);
			case user -> ChatCompletionMessageParam.ofUser(
				ChatCompletionUserMessageParam.builder()
					.content(content)
					.build()
			);
			default -> {
				LOGGER.warn("Unexpected role: " + role + ", defaulting to USER");
				yield ChatCompletionMessageParam.ofUser(
					ChatCompletionUserMessageParam.builder()
						.content(content)
						.build()
				);
			}
		};
	}


	/**
	 * Executes the streaming request using OpenAI Java SDK (https://github.com/openai/openai-java/)
	 * Processes each chunk as it arrives from the API
	 */
	private void executeStreamingRequest(OpenAIClient client, ChatCompletionCreateParams requestParams) throws Exception {
		LOGGER.debug("Initiating OpenAI streaming request");

		genaicommons.impl.StreamingImpl.createResponseMessage(getContext(), mxResponse);

		// Create streaming request - returns a StreamResponse<ChatCompletionChunk>
		try (com.openai.core.http.StreamResponse<ChatCompletionChunk> streamResponse =
			client.chat().completions().createStreaming(requestParams)) {

			// Process the stream of chunks
			streamResponse.stream()
				.forEach(chunk -> {
					try {
						processChunk(chunk);
					} catch (Exception e) {
						LOGGER.error("Error processing chunk: " + e.getMessage(), e);
						// Continue processing remaining chunks
					}
				});
		}

		// Finalize any accumulated tool calls now that the stream is complete
		finalizeToolCalls();

		mxResponse.getResponse_Message().setContent(mxResponse.getResponseText());
		if (!mxToolCallList.isEmpty()) {
			mxResponse.getResponse_Message().setMessage_ToolCall(mxToolCallList);
		}

		LOGGER.debug("Stream completed successfully");
	}

	/**
	 * Processes a single ChatCompletionChunk from the stream
	 * Extracts the content delta and updates the Response object
	 */
	private void processChunk(ChatCompletionChunk chunk) throws Exception {
		// Extract the content from the chunk (which contains the delta)
		Request request = this.Request;
		
		if (chunk.choices() != null && !chunk.choices().isEmpty()) {
			chunk.choices().stream()
				.forEach(choice -> {
					try {
						// Update ResponseText with content delta
						if (choice.delta() != null && choice.delta().content().isPresent()) {
							String content = choice.delta().content().get();
							if (request.getStreamingResponseWriterId() != null) {
			                    	genaicommons.impl.StreamingImpl.pushChunkToUI(getContext(), request.getStreamingResponseWriterId(), content);
			                    }

							genaicommons.impl.StreamingImpl.updateResponseText(mxResponse, content);

							LOGGER.debug("Received chunk content: " + content);
						}

						// Collect information for ToolCall
						if (choice.delta() != null && choice.delta().toolCalls().isPresent()) {
	                        accumulateToolCallFragments(choice.delta());
	                        LOGGER.debug("Accumulating tool call fragments.");
	                    }

						// Extract and update stop reason if available
						if (choice.finishReason().isPresent()) {
							String finishReason = choice.finishReason().get().toString();
							updateStopReason(finishReason);
							LOGGER.debug("Received chunk finish reason: " + finishReason);
						}
					} catch (Exception e) {
						LOGGER.error("Error processing choice in chunk: " + e.getMessage(), e);
					}
				});
		}

		// Extract and update token counts if available (only sent on the final chunk, outside of choices)
		if (chunk.usage().isPresent()) {
			updateTokenCounts(chunk);
			LOGGER.debug("Updated token information.");
		}
	}
	
	private void accumulateToolCallFragments(ChatCompletionChunk.Choice.Delta delta) {
	    delta.toolCalls().get().forEach(toolCallChunk -> {
	        int index = (int) toolCallChunk.index();

	        ToolCallFragments entry = toolCallAccumulator.computeIfAbsent(index, i -> new ToolCallFragments());

	        if (toolCallChunk.id() != null && toolCallChunk.id().isPresent()) {
	            entry.id.append(toolCallChunk.id().get());
	        }

	        if (toolCallChunk.function() != null && toolCallChunk.function().isPresent()) {
	            var function = toolCallChunk.function().get();

	            if (function.name() != null && function.name().isPresent()) {
	                entry.name.append(function.name().get());
	            }
	            if (function.arguments() != null && function.arguments().isPresent()) {
	                entry.arguments.append(function.arguments().get());
	            }
	        }
	    });

	    LOGGER.debug("Accumulating tool call fragments, current state: {}", toolCallAccumulator);
	}
	
	// Tools
	// Build Tool part for request
	
	private JsonValue getToolParametersJson(Tool tool) throws Exception {
	    String schema = tool.getSchema();

	    // Use pre-defined schema if available and valid JSON object
	    if (schema != null && !schema.trim().isEmpty()) {
	        if (schema.startsWith("{") || schema.startsWith("[")) {
	            try {
	                JsonNode schemaNode = MAPPER.readTree(schema);
	                if (schemaNode.isObject()) {
	                    return JsonValue.fromJsonNode(schemaNode);
	                } else {
	                    LOGGER.warn("Tool schema must be a JSON object, not array or primitive. Tool: " + tool.getName());
	                }
	            } catch (Exception e) {
	                LOGGER.warn("Failed to parse tool JSON schema for tool '" + tool.getName() + "', falling back to automatic generation. Error: " + e.getMessage());
	            }
	        } else {
	            LOGGER.warn("Schema field for tool '" + tool.getName() + "' is not valid JSON (must start with '{' or '['). Falling back to automatic generation.");
	        }
	    }

	    // Fall back to auto-generation from microflow parameters
	    Map<String, IDataType> parameterList = FunctionMappingImpl.getInputParametersForModel(tool.getMicroflow());

	    ObjectNode schemaNode = MAPPER.createObjectNode();
	    schemaNode.put("type", "object");
	    ObjectNode propertiesNode = schemaNode.putObject("properties");
	    ArrayNode requiredNode = schemaNode.putArray("required");

	    if (parameterList != null && !parameterList.isEmpty()) {
	        for (Map.Entry<String, IDataType> param : parameterList.entrySet()) {
	            FunctionImpl.addProperty(propertiesNode, requiredNode, param);
	        }
	    }

	    return JsonValue.fromJsonNode(schemaNode);
	}

	private List<ChatCompletionTool> buildTools(List<Tool> tools) throws Exception {
	    List<ChatCompletionTool> toolParams = new ArrayList<>();

	    for (Tool tool : tools) {
	        String name        = tool.getName();
	        String description = tool.getDescription();

	        requireNonNull(name, "Tool name is required");

	        JsonValue parametersJson = getToolParametersJson(tool);

	        FunctionDefinition functionDefinition = FunctionDefinition.builder()
	            .name(name)
	            .description(description)
	            .parameters(parametersJson)
	            .build();

	        ChatCompletionFunctionTool functionTool = ChatCompletionFunctionTool.builder()
	            .function(functionDefinition)
	            .build();

	        ChatCompletionTool toolParam = ChatCompletionTool.ofFunction(functionTool);

	        toolParams.add(toolParam);
	        LOGGER.debug("Registered tool: {}", name);
	    }

	    return toolParams;
	}
	
	// Build ToolChoice 
	private ChatCompletionToolChoiceOption buildToolChoice(
	        Request request,
	        ToolCollection toolCollection) throws Exception {

		    ENUM_ToolChoice toolChoice = request.getToolChoice(); 
	
		    if (toolChoice == null) {
		        return null;
		    }
	
		    switch (toolChoice) {
		        case none:
		            return ChatCompletionToolChoiceOption.ofAuto(
		                ChatCompletionToolChoiceOption.Auto.NONE
		            );
		        case auto:
		            return ChatCompletionToolChoiceOption.ofAuto(
		                ChatCompletionToolChoiceOption.Auto.AUTO
		            );
		        case any:
		            // "any" can only be forced on the first iteration of the agent loop,
		            // otherwise a tool call would be forced on every turn indefinitely
		            if (FunctionMappingImpl.getToolCallMessages(request, getContext()).isEmpty()) {
		                return ChatCompletionToolChoiceOption.ofAuto(
		                    ChatCompletionToolChoiceOption.Auto.REQUIRED
		                );
		            }
		            return null;
		        case tool: {
		            // Retrieve the single forced tool via the ToolChoice association
		            Tool forcedTool = toolCollection.getToolCollection_ToolChoice();
		            requireNonNull(forcedTool,
		                "ToolChoice is set to 'tool' but no tool is linked via ToolCollection_ToolChoice"
		            );

		            // Stop forcing the tool once it has already been called in this agent loop,
		            // otherwise the model would be forced to call it again indefinitely
		            if (FunctionMappingImpl.isToolRecall(request, forcedTool.getName(), getContext())) {
		                LOGGER.debug("ToolChoice " + forcedTool.getName() + " has already been called. Removing forced ToolChoice from request.");
		                return null;
		            }

		            ChatCompletionNamedToolChoice namedToolChoice =
		                ChatCompletionNamedToolChoice.builder()
		                    .function(
		                        ChatCompletionNamedToolChoice.Function.builder()
		                            .name(forcedTool.getName())
		                            .build()
		                    )
		                    .build();

		            return ChatCompletionToolChoiceOption.ofNamedToolChoice(
		                namedToolChoice
		            );
		        }
		        default:
		            LOGGER.warn("Unrecognized ToolChoice value: {}, defaulting to auto", toolChoice);
		            return ChatCompletionToolChoiceOption.ofAuto(
		                ChatCompletionToolChoiceOption.Auto.AUTO
		            );
		    }
		}

	private void createToolCall(String toolCallId, String functionName, String arguments) {
	    genaicommons.proxies.ToolCall mxToolCall = new genaicommons.proxies.ToolCall(getContext());

	    mxToolCall.setToolCallId(toolCallId);
	    mxToolCall.setName(functionName);
	    mxToolCall.setInput(arguments);
	    mxToolCallList.add(mxToolCall);

	    LOGGER.debug("Created ToolCall — ID: {}, Function: {}, Args: {}",
	        toolCallId, functionName, arguments);
	}

	private void finalizeToolCalls() throws Exception {
	    if (toolCallAccumulator.isEmpty()) {
	        return;
	    }

	    for (Map.Entry<Integer, ToolCallFragments> accumEntry : toolCallAccumulator.entrySet()) {
	        ToolCallFragments entry = accumEntry.getValue();
	        String toolCallId   = entry.id.toString();
	        String functionName = entry.name.toString();
	        String arguments    = entry.arguments.toString();

	        LOGGER.debug("Finalizing tool call [{}] — Function: {}", accumEntry.getKey(), functionName);
	        createToolCall(toolCallId, functionName, arguments);
	    }

	    // Clear accumulator for the next request
	    toolCallAccumulator.clear();
	}

	/**
	 * Updates token count attributes when usage information is available
	 */
	private void updateTokenCounts(ChatCompletionChunk chunk) {
		chunk.usage().ifPresent(usage -> {

			Long requestTokens  = (long) usage.promptTokens();
            Long responseTokens = (long) usage.completionTokens();
            Long totalTokens  = (long) usage.totalTokens();

            mxResponse.setRequestTokens(requestTokens.intValue());
            mxResponse.setResponseTokens(responseTokens.intValue());
            mxResponse.setTotalTokens(totalTokens.intValue());

		});
	}

	/**
	 * Updates the StopReason attribute when the stream finishes
	 */
	private void updateStopReason(String stopReason) {
		if (mxResponse != null && stopReason != null) {
			mxResponse.setStopReason(stopReason);
		}
	}
	
	// Files / Vision support
	
	private boolean hasFiles(genaicommons.proxies.Message mxMsg) throws CoreException {
		FileCollection fileCol = mxMsg.getMessage_FileCollection();
		if (fileCol == null) {
			return false;
		}
		List<FileContent> fileContents = fileCol.getFileCollection_FileContent();
		return fileContents != null && !fileContents.isEmpty();
	}
	
	private List<FileContent> getFiles(genaicommons.proxies.Message mxMsg) throws CoreException {
		return mxMsg.getMessage_FileCollection().getFileCollection_FileContent();
	}
	
	private ChatCompletionMessageParam buildUserMessageWithFiles(genaicommons.proxies.Message mxMsg, String content) throws Exception {
		List<ChatCompletionContentPart> contentParts = new ArrayList<>();
		
		// Add message text content first, if present
		if (content != null && !content.isBlank()) {
			contentParts.add(ChatCompletionContentPart.ofText(
				ChatCompletionContentPartText.builder()
					.text(content)
					.build()
			));
		}
		
		List<FileContent> files = getFiles(mxMsg);
		for (FileContent file : files) {
			
			// Add filename as text part
			if (file.getFileName() != null && !file.getFileName().isBlank()) {
				contentParts.add(ChatCompletionContentPart.ofText(
					ChatCompletionContentPartText.builder()
						.text(file.getFileName())
						.build()
				));
			}
			
			// Add text content of the file if present
			if (file.getTextContent() != null && !file.getTextContent().isBlank()) {
				contentParts.add(ChatCompletionContentPart.ofText(
					ChatCompletionContentPartText.builder()
						.text(file.getTextContent())
						.build()
				));
			}
			
			ENUM_FileType fileType = file.getFileType();
			if (fileType != null) {
				switch (fileType) {
					case image: {
						ChatCompletionContentPart imagePart = buildImageContentPart(file);
						if (imagePart != null) {
							contentParts.add(imagePart);
						}
						break;
					}
					case document: {
						ChatCompletionContentPart documentPart = buildDocumentContentPart(file);
						if (documentPart != null) {
							contentParts.add(documentPart);
						}
						break;
					}
					default:
						LOGGER.warn("Unsupported FileContent or FileType found in request.");
						break;
				}
			} else {
				LOGGER.error("FileContent with empty FileType found in request.");
			}
		}
		
		return ChatCompletionMessageParam.ofUser(
			ChatCompletionUserMessageParam.builder()
				.content(ChatCompletionUserMessageParam.Content.ofArrayOfContentParts(contentParts))
				.build()
		);
	}
	
	private ChatCompletionContentPart buildImageContentPart(FileContent file) {
		String imageUrl;
		ENUM_ContentType contentType = file.getContentType();

		if (contentType == ENUM_ContentType.Url) {
			imageUrl = file.getFileContent();
		} else {
			// Base64: build a data URI
			String ext = file.getFileExtension();
			if (ext != null && ext.equalsIgnoreCase("jpg")) {
				ext = "jpeg";
			}
			imageUrl = "data:image/" + ext + ";base64," + file.getFileContent();
		}

		ChatCompletionContentPartImage.ImageUrl.Builder imageUrlBuilder =
			ChatCompletionContentPartImage.ImageUrl.builder().url(imageUrl);

		if (file instanceof openaiconnector.proxies.OpenAIImageContent) {
			openaiconnector.proxies.ENUM_ImageDetail detail = ((openaiconnector.proxies.OpenAIImageContent) file).getDetail();
			if (detail != null) {
				imageUrlBuilder.detail(ChatCompletionContentPartImage.ImageUrl.Detail.of(detail.toString()));
			}
		}

		return ChatCompletionContentPart.ofImageUrl(
			ChatCompletionContentPartImage.builder()
				.imageUrl(imageUrlBuilder.build())
				.build()
		);
	}

	private ChatCompletionContentPart buildDocumentContentPart(FileContent file) {
		ENUM_ContentType contentType = file.getContentType();

		if (contentType == ENUM_ContentType.Url) {
			LOGGER.warn("URL-based documents are not supported for OpenAI file content parts. Skipping.");
			return null;
		}

		// OpenAI expects file_data as a base64-encoded data URL, e.g. "data:application/pdf;base64,..."
		String mimeType = getDocumentMimeType(file.getFileExtension());
		String fileData = "data:" + mimeType + ";base64," + file.getFileContent();

		ChatCompletionContentPart.File.FileObject fileObject =
			ChatCompletionContentPart.File.FileObject.builder()
				.fileData(fileData)
				.filename(file.getFileName() != null ? file.getFileName() : "document")
				.build();

		return ChatCompletionContentPart.ofFile(
			ChatCompletionContentPart.File.builder()
				.file(fileObject)
				.build()
		);
	}

	private String getDocumentMimeType(String fileExtension) {
		if (fileExtension == null) {
			return "application/pdf";
		}
		switch (fileExtension.trim().toLowerCase()) {
			case "pdf":
				return "application/pdf";
			case "txt":
				return "text/plain";
			case "csv":
				return "text/csv";
			case "json":
				return "application/json";
			case "doc":
				return "application/msword";
			case "docx":
				return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
			default:
				LOGGER.warn("Unrecognized document file extension '" + fileExtension + "', defaulting to application/pdf");
				return "application/pdf";
		}
	}
	
	// END EXTRA CODE
}
