// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpClient;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.client.transport.HttpClientSseClientTransport;
import io.modelcontextprotocol.client.transport.HttpClientStreamableHttpTransport;
import io.modelcontextprotocol.spec.McpClientTransport;
import io.modelcontextprotocol.spec.McpSchema;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.MCPClient;
import system.proxies.HttpHeader;
import java.net.URI;
import java.net.http.HttpRequest;
import java.time.Duration;
import java.util.List;

/**
 * Create an MCPClient that is connected to an MCP Server. The input follows the MCP specifications.
 */
public class CreateMCPClient extends UserAction<IMendixObject>
{
	/** @deprecated use ClientConfig.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ClientConfig;
	private final mcpclient.proxies.MCPClientConfig ClientConfig;

	public CreateMCPClient(
		IContext context,
		IMendixObject _clientConfig
	)
	{
		super(context);
		this.__ClientConfig = _clientConfig;
		this.ClientConfig = _clientConfig == null ? null : mcpclient.proxies.MCPClientConfig.initialize(getContext(), _clientConfig);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			//Validating Config
			requireNonNull(ClientConfig, "MCP Client Config is required.");
			requireNonNull(ClientConfig.getMCPEndpoint(), "MCP Endpoint is required.");
			requireNonNull(ClientConfig.getName(), "MCP Name is required.");
			requireNonNull(ClientConfig.getProtocolVersion(), "Protocol version is required.");	
			
			//Client NPE creation
			MCPClient clientNpe = new MCPClient(getContext());
			clientNpe.setMCPEndpoint(ClientConfig.getMCPEndpoint());
			
			//Prepare connection
			McpClientTransport transport = createTransport();
			
			McpSchema.ClientCapabilities capabilities = McpSchema.ClientCapabilities.builder().build();
			McpSchema.Implementation clientInfo = new McpSchema.Implementation(ClientConfig.getName(), ClientConfig.getVersion());

			McpSyncClient client = McpClient.sync(transport)
					.requestTimeout(Duration.ofSeconds(getConnectionTimeout()))
					.loggingConsumer(notification -> {
			            LOGGER.debug("MCP Log: " + notification.data());
			        })
					.capabilities(capabilities)
					.clientInfo(clientInfo)
					.build();
			
			McpSchema.InitializeResult initResult = client.initialize();
			LOGGER.debug("Client connected. configuredProtocol=" + ClientConfig.getProtocolVersion().toString() + ", negotiatedProtocol=" + initResult.protocolVersion() + ", endpoint=" + ClientConfig.getMCPEndpoint() + ", clientName=" + ClientConfig.getName());
			clientNpe.setConnected(true);
			McpClientRegistry.putClient(clientNpe.getMendixObject().getId().toLong(), client);
			return clientNpe.getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e, "Failed to create MCP client for configuration with name: ", ClientConfig != null ? ClientConfig.getName(): null);
			if (e.getCause() != null) {
			    LOGGER.error("Root cause:", e.getCause());
			}
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateMCPClient";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(CreateMCPClient.class);

	/**
	 * Creates the appropriate MCP transport based on the protocol version.
	 * Protocol version v2024 uses SSE transport, newer versions use Streamable HTTP.
	 * 
	 * @return Transport instance (either HttpClientSseClientTransport or HttpClientStreamableHttpTransport)
	 * @throws CoreException if there's an error creating the request builder
	 */
	private McpClientTransport createTransport() throws CoreException {
		HttpRequest.Builder customRequestBuilder = getCustomRequestBuilder();
		String protocolVersion = ClientConfig.getProtocolVersion().toString();
		URI endpointUri = getValidatedEndpointUri();
		String baseUrl = getBaseUrl(endpointUri);
		String endpointPath = getEndpointPath(endpointUri);
		
		if (protocolVersion.equals("v2024_11_05")) {
			// Use SSE transport for v2024-11-05
			LOGGER.debug("Transport=SSE, protocol=" + protocolVersion + ", configuredEndpoint=" + endpointUri + ", base=" + baseUrl + ", endpointPath=" + endpointPath);
			return HttpClientSseClientTransport
					.builder(baseUrl)
					.sseEndpoint(endpointPath)
					.requestBuilder(customRequestBuilder)
					.build();
		} else if (protocolVersion.equals("v2025_03_26")) {
			// Use Streamable HTTP transport for v2025-03-26
			LOGGER.debug("Transport=HTTP, protocol=" + protocolVersion + ", configuredEndpoint=" + endpointUri + ", base=" + baseUrl + ", endpointPath=" + endpointPath);
			return HttpClientStreamableHttpTransport
					.builder(baseUrl)
					.endpoint(endpointPath)
					.requestBuilder(customRequestBuilder)
					.build();
		} else {
			throw new IllegalArgumentException("Unsupported protocol version: " + protocolVersion);
		}
	}

	/**
	 * Parses and validates the configured MCP endpoint URL.
	 */
	private URI getValidatedEndpointUri() {
		String configuredEndpoint = requireNonNull(ClientConfig.getMCPEndpoint(), "MCP Endpoint is required.").trim();
		URI endpointUri;

		try {
			endpointUri = URI.create(configuredEndpoint);
		} catch (IllegalArgumentException e) {
			throw new IllegalArgumentException("MCP Endpoint must be a valid absolute URL: " + configuredEndpoint, e);
		}

		if (endpointUri.getScheme() == null || endpointUri.getHost() == null) {
			throw new IllegalArgumentException("MCP Endpoint must be a valid absolute URL with scheme and host: " + configuredEndpoint);
		}

		return endpointUri;
	}

	/**
	 * Returns URL base in the form scheme://authority.
	 */
	private String getBaseUrl(URI endpointUri) {
		return endpointUri.getScheme() + "://" + endpointUri.getRawAuthority();
	}

	/**
	 * Returns the path component from endpoint URL and defaults to "/" when absent.
	 */
	private String getEndpointPath(URI endpointUri) {
		String rawPath = endpointUri.getRawPath();
		return (rawPath == null || rawPath.isEmpty()) ? "/" : rawPath;
	}
	
	/**
	 * Creates a custom request builder to add headers passed in the configuration
	 * @throws CoreException
	 */
	private HttpRequest.Builder getCustomRequestBuilder() throws CoreException{
		List<HttpHeader> headersMendix = ClientConfig.getMCPClientConfig_HttpHeader();
		
		HttpRequest.Builder customRequestBuilder = HttpRequest.newBuilder();
		for (system.proxies.HttpHeader header : headersMendix) {
		    String name  = header.getKey();
		    String value = header.getValue();
		    if (name != null && value != null) {
		    	customRequestBuilder.header(name, value);
		    }
		}
		return customRequestBuilder;
	}

	/**
	 * Either uses passed timeout settings or sets to default 10s
	 * @return
	 */
	private Long getConnectionTimeout(){
		if(ClientConfig.getConnectionTimeOutInSeconds() != null && ClientConfig.getConnectionTimeOutInSeconds() <= 0) {
			LOGGER.warn("Invalid connection timeout specified; using default of 10 seconds.");
			return 10L;
		}
		return ClientConfig.getConnectionTimeOutInSeconds() != null ? ClientConfig.getConnectionTimeOutInSeconds() : 10L;
	}
	
	// END EXTRA CODE
}
