// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpClient;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.client.transport.HttpClientSseClientTransport;
import io.modelcontextprotocol.spec.McpSchema;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.MCPClient;
import mcpserver.impl.McpServerRegistry;
import java.time.Duration;

public class CreateMCPClient extends UserAction<IMendixObject>
{
	/** @deprecated use ClientConfig.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ClientConfig;
	private final mcpclient.proxies.MCPClientConfig ClientConfig;

	public CreateMCPClient(
		IContext context,
		IMendixObject _clientConfig
	)
	{
		super(context);
		this.__ClientConfig = _clientConfig;
		this.ClientConfig = _clientConfig == null ? null : mcpclient.proxies.MCPClientConfig.initialize(getContext(), _clientConfig);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Create Client NPE
		MCPClient clientNpe = new MCPClient(getContext());
		clientNpe.setMCPEndpoint(ClientConfig.getMCPEndpoint());

		HttpClientSseClientTransport transport = HttpClientSseClientTransport
				.builder(ClientConfig.getMCPEndpoint())
				.build();

		McpSyncClient client = McpClient.sync(transport)
				.requestTimeout(Duration.ofSeconds(10))
				.capabilities(McpSchema.ClientCapabilities.builder()
//						.roots(true)      // Enable roots capability
//						.sampling()       // Enable sampling capability
						.build())
//				.sampling(request -> new McpSchema.CreateMessageResult(response))
				.build();

		McpSchema.InitializeResult initResult = client.initialize();
		LOGGER.info("Client connected to server using: " + initResult.protocolVersion() + " version.");
		clientNpe.setConnected(true);

		McpClientRegistry.putClient(clientNpe.getMendixObject().getId().toLong(), client);
		return clientNpe.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateMCPClient";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(CreateMCPClient.class);
	// END EXTRA CODE
}
