// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpClient;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.client.transport.HttpClientSseClientTransport;
import io.modelcontextprotocol.client.transport.HttpClientStreamableHttpTransport;
import io.modelcontextprotocol.spec.McpClientTransport;
import io.modelcontextprotocol.spec.McpSchema;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.MCPClient;
import system.proxies.HttpHeader;
import java.net.http.HttpRequest;
import java.time.Duration;
import java.util.List;

/**
 * Create an MCPClient that is connected to an MCP Server. The input follows the MCP specifications.
 */
public class CreateMCPClient extends UserAction<IMendixObject>
{
	/** @deprecated use ClientConfig.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ClientConfig;
	private final mcpclient.proxies.MCPClientConfig ClientConfig;

	public CreateMCPClient(
		IContext context,
		IMendixObject _clientConfig
	)
	{
		super(context);
		this.__ClientConfig = _clientConfig;
		this.ClientConfig = _clientConfig == null ? null : mcpclient.proxies.MCPClientConfig.initialize(getContext(), _clientConfig);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			//Validating Config
			requireNonNull(ClientConfig, "MCP Client Config is required.");
			requireNonNull(ClientConfig.getMCPEndpoint(), "MCP Endpoint is required.");
			requireNonNull(ClientConfig.getName(), "MCP Name is required.");
			requireNonNull(ClientConfig.getVersion(), "Version is required.");
			requireNonNull(ClientConfig.getProtocolVersion(), "Protocol version is required.");	
			
			//Client NPE creation
			MCPClient clientNpe = new MCPClient(getContext());
			clientNpe.setMCPEndpoint(ClientConfig.getMCPEndpoint());
			
			//Prepare connection
			McpClientTransport transport = createTransport();
			
			McpSchema.ClientCapabilities capabilities = McpSchema.ClientCapabilities.builder().build();
			McpSchema.Implementation clientInfo = new McpSchema.Implementation(ClientConfig.getName(), ClientConfig.getVersion());

			McpSyncClient client = McpClient.sync(transport)
					.requestTimeout(Duration.ofSeconds(10))
					.loggingConsumer(notification -> {
			            LOGGER.debug("MCP Log: " + notification.data());
			        })
					.capabilities(capabilities)
					.clientInfo(clientInfo)
					.build();
			
			//Connect to server (single attempt; endpoint normalization fixed path)
			McpSchema.InitializeResult initResult = client.initialize();
			LOGGER.info("Client connected to server using: " + initResult.protocolVersion() + " version.");
			// Some servers do not enable logging capabilities; avoid failing hard
			try {
				client.setLoggingLevel(McpSchema.LoggingLevel.DEBUG);
			} catch (IllegalStateException unsupported) {
				LOGGER.info("Server logging capabilities not enabled; skipping setLoggingLevel.");
			}
			clientNpe.setConnected(true);
			McpClientRegistry.putClient(clientNpe.getMendixObject().getId().toLong(), client);
			return clientNpe.getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e, "Failed to create MCP client for configuration with name: ", ClientConfig != null ? ClientConfig.getName(): null);
			if (e.getCause() != null) {
			    LOGGER.error("Root cause:", e.getCause());
			}
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateMCPClient";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(CreateMCPClient.class);

	/**
	 * Creates the appropriate MCP transport based on the protocol version.
	 * Protocol version v2024-* uses SSE transport, newer versions use Streamable HTTP.
	 * 
	 * @return Transport instance (either HttpClientSseClientTransport or HttpClientStreamableHttpTransport)
	 * @throws CoreException if there's an error creating the request builder
	 */
	private McpClientTransport createTransport() throws CoreException {
		HttpRequest.Builder customRequestBuilder = getCustomRequestBuilder();
		String protocolVersion = ClientConfig.getProtocolVersion().toString();
		String endpoint;
		
		if (protocolVersion.startsWith("v2024")) {
			// Use SSE transport for 2024 protocol versions
			String base = getBaseEndpoint();
			endpoint = getSseEndpoint();
			LOGGER.info("Transport=SSE, protocol=" + protocolVersion + ", base=" + base + ", endpoint=" + endpoint);
			return HttpClientSseClientTransport
					.builder(base)
					.sseEndpoint(endpoint)
					.requestBuilder(customRequestBuilder)
					.build();
		} else {
			// Use Streamable HTTP transport for newer protocol versions
			String baseUrl = getBaseEndpoint();
			endpoint = java.net.URI.create(baseUrl + "/mcp").getRawPath(); // Streamable HTTP requires this for some reason
			LOGGER.info("Transport=HTTP, protocol=" + protocolVersion + ", base=" + baseUrl + ", endpoint=" + endpoint);
			return HttpClientStreamableHttpTransport
					.builder(baseUrl)
					.endpoint(endpoint)
					.requestBuilder(customRequestBuilder)
					.build();
		}
	}

	/**
	 * Creates the base endpoint by removing trailing slashes and known MCP suffixes (/sse, /mcp)
	 */
	private String getBaseEndpoint() {
	    String baseUrl = ClientConfig.getMCPEndpoint();
	    
	    //Remove trailing slash first
	    if (baseUrl.endsWith("/")) {
	        baseUrl = baseUrl.substring(0, baseUrl.length() - 1);
	    }
	    
	    //Remove /sse suffix if present
	    if (baseUrl.toLowerCase().endsWith("/sse")) {
	        baseUrl = baseUrl.substring(0, baseUrl.length() - 4);
	    }
	    
	    //Remove /mcp suffix if present
	    if (baseUrl.toLowerCase().endsWith("/mcp")) {
	        baseUrl = baseUrl.substring(0, baseUrl.length() - 4);
	    }
	    
	    return baseUrl;
	}

	/**
	 *Sets "/sse" to the base endpoint
	 */
	private String getSseEndpoint() {
	    return getBaseEndpoint() + "/sse";
	}
	
	/**
	 * Creates a custom request builder to add headers passed in the configuration
	 * @throws CoreException
	 */
	private HttpRequest.Builder getCustomRequestBuilder() throws CoreException{
		List<HttpHeader> headersMendix = ClientConfig.getMCPClientConfig_HttpHeader();
		
		HttpRequest.Builder customRequestBuilder = HttpRequest.newBuilder();
		for (system.proxies.HttpHeader header : headersMendix) {
		    String name  = header.getKey();
		    String value = header.getValue();
		    if (name != null && value != null) {
		    	customRequestBuilder.header(name, value);
		    }
		}
		return customRequestBuilder;
	}
	
	// END EXTRA CODE
}
