// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import mcpclient.impl.McpClientRegistry;
import mcpclient.proxies.Prompt;
import mcpclient.proxies.PromptArgumentItem;
import java.util.Map;
import java.util.List;
import java.util.stream.Collector;
import java.util.stream.Collectors;

public class GetPrompt extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;
	/** @deprecated use Prompt.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Prompt;
	private final mcpclient.proxies.Prompt Prompt;
	/** @deprecated use com.mendix.utils.ListUtils.map(Arguments, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __Arguments;
	private final java.util.List<mcpclient.proxies.PromptArgumentItem> Arguments;

	public GetPrompt(
		IContext context,
		IMendixObject _mCPClient,
		IMendixObject _prompt,
		java.util.List<IMendixObject> _arguments
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
		this.__Prompt = _prompt;
		this.Prompt = _prompt == null ? null : mcpclient.proxies.Prompt.initialize(getContext(), _prompt);
		this.__Arguments = _arguments;
		this.Arguments = java.util.Optional.ofNullable(_arguments)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(argumentsElement -> mcpclient.proxies.PromptArgumentItem.initialize(getContext(), argumentsElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());

		Map<String, Object> arguments = Arguments.stream().collect(Collectors.toMap(PromptArgumentItem::getName, PromptArgumentItem::getValue));
		McpSchema.GetPromptRequest request = new McpSchema.GetPromptRequest(Prompt.getName(), arguments);



		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetPrompt";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
