// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import io.modelcontextprotocol.spec.McpSchema.Role;
import io.modelcontextprotocol.spec.McpSchema.TextContent;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.Audience;
import mcpclient.proxies.GetPromptResult;
import mcpclient.proxies.PromptArgumentItem;
import mcpclient.proxies.PromptMessage;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class GetPrompt extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;
	/** @deprecated use Prompt.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Prompt;
	private final mcpclient.proxies.Prompt Prompt;
	/** @deprecated use com.mendix.utils.ListUtils.map(Arguments, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __Arguments;
	private final java.util.List<mcpclient.proxies.PromptArgumentItem> Arguments;

	public GetPrompt(
		IContext context,
		IMendixObject _mCPClient,
		IMendixObject _prompt,
		java.util.List<IMendixObject> _arguments
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
		this.__Prompt = _prompt;
		this.Prompt = _prompt == null ? null : mcpclient.proxies.Prompt.initialize(getContext(), _prompt);
		this.__Arguments = _arguments;
		this.Arguments = java.util.Optional.ofNullable(_arguments)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(argumentsElement -> mcpclient.proxies.PromptArgumentItem.initialize(getContext(), argumentsElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());

			Map<String, Object> arguments = Arguments.stream()
					.collect(Collectors.toMap(PromptArgumentItem::getName, PromptArgumentItem::getValue));
			
			McpSchema.GetPromptRequest request = new McpSchema.GetPromptRequest(Prompt.getName(), arguments);

			McpSchema.GetPromptResult resultMcp =  client.getPrompt(request);
			GetPromptResult getPromptResultMendix = createPromptResult(resultMcp);
			
			return getPromptResultMendix.getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetPrompt";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(GetPrompt.class);
	
	/**
	 * Create a Mendix GetPromptResult based on the MCP GetPromptResult
	 * @param getPromptResultMcp as returned from the server via MCP 
	 */
	private GetPromptResult createPromptResult(McpSchema.GetPromptResult getPromptResultMcp) {
		
		GetPromptResult getPromptResultMendix = new GetPromptResult(getContext());
		getPromptResultMendix.setDescription(getPromptResultMcp.description());
		
		List<io.modelcontextprotocol.spec.McpSchema.PromptMessage> promptMessageListMcp = getPromptResultMcp.messages();
		
		if(promptMessageListMcp == null || promptMessageListMcp.isEmpty()) {
			LOGGER.debug("Get Prompt Result returned no prompt messages.");
			return getPromptResultMendix;
		}
		
		for(io.modelcontextprotocol.spec.McpSchema.PromptMessage promptMessageMcp : promptMessageListMcp) {
			createPromptMessages(promptMessageMcp, getPromptResultMendix);
		}	
		
		return getPromptResultMendix;
	}
	
	/**
	 * For a given GetPromptResult the messages are extracted and mapped to Mendix PromptMessages
	 * @param promptMessageMcp
	 * @param getPromptResultMendix
	 */
	private void createPromptMessages(io.modelcontextprotocol.spec.McpSchema.PromptMessage promptMessageMcp, GetPromptResult getPromptResultMendix) {
		PromptMessage promptMessageMendix = new PromptMessage(getContext());
		TextContent textContent = (TextContent) promptMessageMcp.content();
		createAudiences(textContent, promptMessageMendix);
		promptMessageMendix.setContent(textContent.text());
		promptMessageMendix.setRole(promptMessageMcp.role().toString());
		promptMessageMendix.setPromptMessage_GetPromptResult(getPromptResultMendix);	
	}
	
	/**
	 * Mendix Audiences are created if they are part of the PromptMessage (Text Content)
	 * @param textContent
	 * @param promptMessageMendix
	 */
	private void createAudiences(TextContent textContent, PromptMessage promptMessageMendix){
		List<Role> audienceListMcp = textContent.audience();
		if(audienceListMcp == null || audienceListMcp.isEmpty()) {
			return;
		}
		
		for(Role role : audienceListMcp) {
			Audience audienceMendix = new Audience(getContext());
			audienceMendix.setRole(role.name());
			audienceMendix.setAudience_PromptMessage(promptMessageMendix);
		}	
	}
	
	// END EXTRA CODE
}
