// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpClient;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import mcpclient.impl.McpClientRegistry;
import mcpclient.proxies.ListPromptResult;
import mcpclient.proxies.Prompt;

public class ListPrompts extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;

	public ListPrompts(
		IContext context,
		IMendixObject _mCPClient
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());

		McpSchema.ListPromptsResult lpr = client.listPrompts();

		ListPromptResult result = new ListPromptResult(getContext());
		result.setNextCursor(lpr.nextCursor());

		lpr.prompts().forEach(e -> {
			Prompt prompt = new Prompt(getContext());
			prompt.setPrompt_ListPromptResult(result);
			prompt.setName(e.name());
			prompt.setDescription(e.description());
		});


		return result.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListPrompts";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
