// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import io.modelcontextprotocol.spec.McpSchema.PromptArgument;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.ListPromptResult;
import mcpclient.proxies.Prompt;

/**
 * Returns a ListPromptResult which contains a list of all available prompts the MCP Server exposes. The Prompts can be used for the Get Prompt Result action.
 * 
 */
public class ListPromptResult_Get extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;

	public ListPromptResult_Get(
		IContext context,
		IMendixObject _mCPClient
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());

			McpSchema.ListPromptsResult listPromptResultMcp = client.listPrompts();

			ListPromptResult listPromptResultMendix = createListPromptResult(listPromptResultMcp);

			return listPromptResultMendix.getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListPromptResult_Get";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(ListPromptResult_Get.class);
	
	/**
	 * Create a Mendix ListPromptResult based on the MCP ListPromptResult
	 * @param listPromptResultMcp as returned from the server via MCP 
	 */
	private ListPromptResult createListPromptResult(McpSchema.ListPromptsResult listPromptResultMcp) {
		ListPromptResult listPromptResultMendix = new ListPromptResult(getContext());
		List<io.modelcontextprotocol.spec.McpSchema.Prompt> promptListMcp = listPromptResultMcp.prompts();
		listPromptResultMendix.setNextCursor(listPromptResultMcp.nextCursor());
		
		if(promptListMcp == null || promptListMcp.isEmpty()) {
			LOGGER.debug("List Prompt Result returned no prompts.");
			return listPromptResultMendix;
		}
		
		for(McpSchema.Prompt promptMcp : promptListMcp ) {
			createPrompts(listPromptResultMendix, promptMcp);			
		}
		
		return listPromptResultMendix;
	}
	
	/**
	 * Create Mendix Prompts based on the MCP Prompts
	 * @param listPromptResultMendix
	 * @param promptMcp
	 */
	private void createPrompts(ListPromptResult listPromptResultMendix, McpSchema.Prompt promptMcp ) {
		Prompt promptMendix = new Prompt(getContext());
		promptMendix.setPrompt_ListPromptResult(listPromptResultMendix);
		promptMendix.setName(promptMcp.name());
		promptMendix.setDescription(promptMcp.description());
		
		List<PromptArgument> args =  promptMcp.arguments();
		
		if(args == null || args.isEmpty()) {
			return;
		}
		createPromptArguments(promptMcp, promptMendix);
	}
	
	/**
	 * Create Mendix PromptArguments based on the MCP Prompt's arguments
	 * @param promptMcp
	 * @param promptMendix
	 */
	private void createPromptArguments(McpSchema.Prompt  promptMcp, Prompt promptMendix) {
		List<PromptArgument> args =  promptMcp.arguments();
		
		for (McpSchema.PromptArgument promptArgumentMcp : args ) {
			mcpclient.proxies.PromptArgument promptArg = new mcpclient.proxies.PromptArgument(getContext());
			promptArg.setDescription(promptArgumentMcp.description());
			promptArg.setName(promptArgumentMcp.name());
			promptArg.setRequired(promptArgumentMcp.required());
			promptArg.setPromptArgument_Prompt(promptMendix);
		}
	}
	// END EXTRA CODE
}
