// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.ListToolsResult;
import mcpclient.proxies.Tool;

public class ListTools extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;

	public ListTools(
		IContext context,
		IMendixObject _mCPClient
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());
		
		McpSchema.ListToolsResult listToolsResultMcp = client.listTools();
		
		ListToolsResult listToolResultMendix = createListToolsResult(listToolsResultMcp);
		
		//listToolsResultMcp.tools().get(0).
		
		return listToolResultMendix.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListTools";
	}

	// BEGIN EXTRA CODE
	
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(ListTools.class);
	
	private ListToolsResult createListToolsResult(McpSchema.ListToolsResult listToolsResultMcp) {
		
		ListToolsResult listToolResultMendix = new ListToolsResult(getContext());
		
		listToolResultMendix.setNextCursor(listToolsResultMcp.nextCursor());
		List<McpSchema.Tool> toolListMcp = listToolsResultMcp.tools();
		
		if(toolListMcp == null || toolListMcp.isEmpty()){
			LOGGER.debug("List Tools Result returned no tools.");
			return listToolResultMendix;
		}
		
		for(McpSchema.Tool toolMcp : toolListMcp) {
			createTool(toolMcp, listToolResultMendix);
		}
		
		
		return listToolResultMendix;
		
	}
	
	private void createTool(McpSchema.Tool toolMcp, ListToolsResult listToolResultMendix) {
		Tool toolMendix = new Tool(getContext());
		toolMendix.setName(toolMcp.name());
		toolMendix.setDescription(toolMcp.description());
		toolMendix.setInputSchema(toolMcp.inputSchema().toString());
		toolMendix.setTool_ListToolsResult(listToolResultMendix);
	}
	
	// END EXTRA CODE
}
