// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import mcpclient.proxies.MCPClientConfig;
import mcpclient.impl.MxLogger;
import system.proxies.HttpHeader;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class MCPServer_CreateMCPClient extends UserAction<IMendixObject>
{
	/** @deprecated use MCPServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPServer;
	private final mcpclient.proxies.MCPServer MCPServer;

	public MCPServer_CreateMCPClient(
		IContext context,
		IMendixObject _mCPServer
	)
	{
		super(context);
		this.__MCPServer = _mCPServer;
		this.MCPServer = _mCPServer == null ? null : mcpclient.proxies.MCPServer.initialize(getContext(), _mCPServer);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(MCPServer, "MCPServer is required.");
			MCPClientConfig mcpClientConfig = new MCPClientConfig(getContext());
			mcpClientConfig.setMCPEndpoint(MCPServer.getMCPEndpoint());
			mcpClientConfig.setName(MCPServer.getName());
			mcpClientConfig.setProtocolVersion(MCPServer.getProtocolVersion());
			mcpClientConfig.setVersion(MCPServer.getVersion());
		
			if(MCPServer.getGetCredentialsMicroflow() != null && !MCPServer.getGetCredentialsMicroflow().isBlank()) {
				List<HttpHeader> httpheaderList = Core.microflowCall(MCPServer.getGetCredentialsMicroflow()).execute(getContext());
				mcpClientConfig.setMCPClientConfig_HttpHeader(httpheaderList);
			}
		
			return Core.userActionCall("MCPClient." + CreateMCPClient.class.getSimpleName())
					.withParams(mcpClientConfig.getMendixObject())
					.execute(getContext());
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MCPServer_CreateMCPClient";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(MCPServer_CreateMCPClient.class);
	// END EXTRA CODE
}
