// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.MCPTool;
import genaicommons.impl.ToolCollectionImpl;
import genaicommons.proxies.Tool;
import genaicommons.proxies.ToolCollection;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Adds a new MCPTool to a Request.
 * Parameters: 
 * - Request: The request to add the tool to.
 * - Name: The name of the tool to call.
 * - Description (optional): A description of what the tool does, used by the model to choose when and how to call the tool.
 * - ArgumentInputList (optional): describe the input parameters of a tool.
 * 
 * The action returns empty if adding the tool was not successful (errors are logged).
 */
public class Request_AddMCPTool extends UserAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use MCPServerConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPServerConfiguration;
	private final mcpclient.proxies.MCPServerConfiguration MCPServerConfiguration;
	private final java.lang.String Name;
	private final java.lang.String Description;
	/** @deprecated use com.mendix.utils.ListUtils.map(ArgumentInputList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __ArgumentInputList;
	private final java.util.List<genaicommons.proxies.ArgumentInput> ArgumentInputList;

	public Request_AddMCPTool(
		IContext context,
		IMendixObject _request,
		IMendixObject _mCPServerConfiguration,
		java.lang.String _name,
		java.lang.String _description,
		java.util.List<IMendixObject> _argumentInputList
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__MCPServerConfiguration = _mCPServerConfiguration;
		this.MCPServerConfiguration = _mCPServerConfiguration == null ? null : mcpclient.proxies.MCPServerConfiguration.initialize(getContext(), _mCPServerConfiguration);
		this.Name = _name;
		this.Description = _description;
		this.__ArgumentInputList = _argumentInputList;
		this.ArgumentInputList = java.util.Optional.ofNullable(_argumentInputList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(argumentInputListElement -> genaicommons.proxies.ArgumentInput.initialize(getContext(), argumentInputListElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try{
			requireNonNull(Request, "Request is required.");
			requireNonNull(MCPServerConfiguration, "MCPServerConfiguration is required.");
			requireNonNull(Name, "Name is required.");
			
			ToolCollection toolCollection = ToolCollectionImpl.getOrCreateToolCollection(getContext(), Request);
			
			return createMCPTool(toolCollection).getMendixObject();

		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_AddMCPTool";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Request_AddMCPTool.class);
	
	private MCPTool createMCPTool(ToolCollection toolCollection) throws CoreException {
		MCPTool tool = new MCPTool(getContext());
		
		tool.setMicroflow("MCPClient.MCPClient_ToolMicroflow");
		tool.setTool_ArgumentInput(ArgumentInputList);
		tool.setDescription(Description);
		tool.setName(Name);
		tool.setMCPTool_MCPServerConfiguration(MCPServerConfiguration);
		List<Tool> ToolList = toolCollection.getToolCollection_Tool();
		ToolList.add(tool);
		toolCollection.setToolCollection_Tool(ToolList); 
		return tool;
	}
	// END EXTRA CODE
}
