// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpclient.actions;

import static java.util.Objects.requireNonNull;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.client.McpSyncClient;
import io.modelcontextprotocol.spec.McpSchema;
import io.modelcontextprotocol.spec.McpSchema.CallToolResult;
import io.modelcontextprotocol.spec.McpSchema.Content;
import io.modelcontextprotocol.spec.McpSchema.TextContent;
import mcpclient.impl.McpClientRegistry;
import mcpclient.impl.MxLogger;
import mcpclient.proxies.ToolResult;
import mcpclient.proxies.ToolArgumentItem;

/**
 * Call the Tool on the MCP Server which returns a ToolResult. The ToolResult contains the response of the tool which is passed to the model.
 */
public class ToolResult_Get extends UserAction<IMendixObject>
{
	/** @deprecated use MCPClient.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MCPClient;
	private final mcpclient.proxies.MCPClient MCPClient;
	/** @deprecated use Tool.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Tool;
	private final mcpclient.proxies.Tool Tool;
	/** @deprecated use com.mendix.utils.ListUtils.map(ToolArgumentItemList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __ToolArgumentItemList;
	private final java.util.List<mcpclient.proxies.ToolArgumentItem> ToolArgumentItemList;

	public ToolResult_Get(
		IContext context,
		IMendixObject _mCPClient,
		IMendixObject _tool,
		java.util.List<IMendixObject> _toolArgumentItemList
	)
	{
		super(context);
		this.__MCPClient = _mCPClient;
		this.MCPClient = _mCPClient == null ? null : mcpclient.proxies.MCPClient.initialize(getContext(), _mCPClient);
		this.__Tool = _tool;
		this.Tool = _tool == null ? null : mcpclient.proxies.Tool.initialize(getContext(), _tool);
		this.__ToolArgumentItemList = _toolArgumentItemList;
		this.ToolArgumentItemList = java.util.Optional.ofNullable(_toolArgumentItemList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(toolArgumentItemListElement -> mcpclient.proxies.ToolArgumentItem.initialize(getContext(), toolArgumentItemListElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Tool,"Tool is required.");
			requireNonNull(MCPClient,"MCP Client is required.");
			
			McpSyncClient client = McpClientRegistry.getClient(MCPClient.getMendixObject().getId().toLong());
			
			Map<String, Object> arguments = new HashMap<>();;
			if (ToolArgumentItemList != null && !ToolArgumentItemList.isEmpty()) {
				arguments = ToolArgumentItemList.stream()
					.collect(Collectors.toMap(ToolArgumentItem::getName, ToolArgumentItem::getValue));
			}
			
			McpSchema.CallToolRequest callToolRequest = new McpSchema.CallToolRequest(Tool.getName(), arguments);

			CallToolResult callToolResultMcp =  client.callTool(callToolRequest);
			ToolResult toolResultMendix = createToolResult(callToolResultMcp);
			
			return toolResultMendix.getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ToolResult_Get";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpclient.impl.MxLogger(ToolResult_Get.class);
	
	/**
	 * Create a Mendix ToolResult based on the MCP CallToolResult
	 * @param callToolResultMcp
	 */
	private ToolResult createToolResult(CallToolResult callToolResultMcp) {
		List<Content> content = callToolResultMcp.content();
		TextContent textContent = (TextContent) content.get(0);
		ToolResult toolResultMendix = new ToolResult(getContext());
		toolResultMendix.setContent(textContent.text());
		return toolResultMendix;
	}	
	// END EXTRA CODE
}
