// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} requestJSON
 * @param {string} deployedModelUUID
 * @param {MxObject} responseCollector
 * @returns {Promise.<void>}
 */
export async function JS_SubmitStreaming(requestJSON, deployedModelUUID, responseCollector) {
	// BEGIN USER CODE
	const response = await fetch("http://localhost:8080/llm-streaming", {
		method: "POST",
		headers: {			
			"Content-Type": "application/json",
			"Accept": "text/event-stream"
		},
		body: JSON.stringify({
			request: requestJSON,
			deployedModelUUID: deployedModelUUID
		})
	})

	const reader = response.body.getReader();
	const decoder = new TextDecoder('utf-8');
	let buffer = ''; // Buffer to accumulate incomplete SSE messages

	// Function to process a complete SSE message
	const processSseMessage = (message) => {
		// SSE messages typically look like:
		// id: 1
		// event: update
		// data: {"status": "online", "value": 123}
		//
		// data: {"status": "offline"}
		//
		// (empty line indicates end of message)

		const lines = message.split('\n').filter(line => line.trim() !== '');
		let id = null;
		let event = 'message'; // Default event type
		let data = '';

		for (const line of lines) {
			if (line.startsWith('id:')) {
				id = line.substring(3).trim();
			} else if (line.startsWith('event:')) {
				event = line.substring(6).trim();
			} else if (line.startsWith('data:')) {
				// Accumulate data lines, they can be multi-line
				data += line.substring(5).trim();
			}
			// You might also handle 'retry:' fields if your server sends them
		}

		if (data) {
			try {
				const decodedData = atob(data);
				console.log('Data:', decodedData);
				// Here you would update your UI or application state
				
				const currentText = responseCollector.get("Text")
				responseCollector.set("Text", currentText + decodedData)
			} catch (e) {
				console.warn('Could not parse SSE data as JSON:', data, e);
				// Handle non-JSON data if expected
				updateUIWithStreamData(data, event);
			}
		}
	};

	while (true) {
		const { done, value } = await reader.read();

		if (done) {
			console.log('Stream finished.');
			break;
		}

		// Decode the chunk and add to buffer
		buffer += decoder.decode(value, { stream: true });

		// Process complete SSE messages from the buffer
		// SSE messages are terminated by two newline characters (\n\n)
		let messageEndIndex;
		while ((messageEndIndex = buffer.indexOf('\n\n')) !== -1) {
			const message = buffer.substring(0, messageEndIndex);
			processSseMessage(message);
			buffer = buffer.substring(messageEndIndex + 2); // Remove processed message and its delimiters
		}
	}

	// END USER CODE
}
