// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import java.util.ArrayList;
import com.mendix.core.Core;
import com.mendix.extensibility.CustomBlobDocumentInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.MxLogger;
import agenteditorcommons.proxies.ModelDocument;

/**
 * Imports all defined documents (such as agents and models) to the app's database so that they can be viewed at runtime and integrate with Agent Commons, Token Monitor, Observability etc.
 * This action can be used as part of your app's after startup logic.
 */
public class AgentEditor_ImportFromStudioPro extends UserAction<java.lang.Boolean>
{
	public AgentEditor_ImportFromStudioPro(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			LOGGER.info("Starting import.");

			importModelDocumentsOfType("agenteditor.model");
			importModelDocumentsOfType("agenteditor.consumedMCPService");
			importModelDocumentsOfType("agenteditor.knowledgebase");
			importModelDocumentsOfType("agenteditor.agent");

			LOGGER.info("Finished import.");
			return true;
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AgentEditor_ImportFromStudioPro";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(AgentEditor_ImportFromStudioPro.class);


	private void importModelDocumentsOfType(String documentTypeID) {
		java.util.List<CustomBlobDocumentInfo> customBlobDocumentList = Core.extensibility()
				.getCustomDocumentsOfType(documentTypeID);
		String documentFriendlyName = documentTypeID.substring(documentTypeID.lastIndexOf('.') + 1);
		LOGGER.info(customBlobDocumentList.size() + " " + documentFriendlyName
				+ "s document(s) found in the Mendix Model.");

		java.util.List<ModelDocument> modelDocuments = new ArrayList<>();
		for (CustomBlobDocumentInfo customBlobDocument : customBlobDocumentList) {
			modelDocuments.add(getModelDocument(customBlobDocument));
		}

		boolean isSuccess = false;

		switch (documentTypeID) {
		case "agenteditor.model":
			isSuccess = agenteditorcommons.proxies.microflows.Microflows
				.deployedModel_CreateUpdate_List(getContext(), modelDocuments);
			break;

		case "agenteditor.consumedMCPService":
			isSuccess = agenteditorcommons.proxies.microflows.Microflows
				.consumedMCPService_CreateUpdate_List(getContext(), modelDocuments);
			break;
			
		case "agenteditor.knowledgebase":
			isSuccess = agenteditorcommons.proxies.microflows.Microflows
					.knowledgeBase_CreateUpdate_List(getContext(), modelDocuments);
			break;
			
		case "agenteditor.agent":
			isSuccess = agenteditorcommons.proxies.microflows.Microflows
				.agent_CreateUpdate_List(getContext(), modelDocuments);
		}

		if (!isSuccess) {
			throw new IllegalArgumentException(
					"Creating/Updating " + documentFriendlyName + " documents failed due to bad input.");
		}
	}


	private ModelDocument getModelDocument(CustomBlobDocumentInfo customBlobDocumentInfo) {
		String qualifiedName = customBlobDocumentInfo.qualifiedDocumentName();
		LOGGER.debug("Importing model with qualified name '" + qualifiedName + "'.");

		String modelDocumentContent = customBlobDocumentInfo.content();

		String documentID = customBlobDocumentInfo.documentID().toString();
		LOGGER.debug(qualifiedName + " - documentID: " + documentID);

		ModelDocument modelDocument = new ModelDocument(getContext());
		modelDocument.setDocumentID(getContext(), documentID);
		modelDocument.setContent(getContext(), modelDocumentContent);
		modelDocument.setQualifiedName(getContext(), qualifiedName);
		return modelDocument;
	}

	// END EXTRA CODE
}
