// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import java.util.ArrayList;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.extensibility.CustomBlobDocumentInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.MxLogger;
import agenteditorcommons.proxies.AgentModelDocument;
import agenteditorcommons.proxies.ModelDocument;

/**
 * Imports all defined documents (such as agents and models) to the app's database so that they can be viewed at runtime and integrate with Agent Commons, Token Monitor, Observability etc.
 * This action can be used as part of your app's after startup logic.
 */
public class AgentEditor_ImportFromStudioPro extends UserAction<java.lang.Boolean>
{
	public AgentEditor_ImportFromStudioPro(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			LOGGER.info("Starting import.");

			importModelDocumentsOfType("agenteditor.model");
			importModelDocumentsOfType("agenteditor.consumedMCPService");
			importModelDocumentsOfType("agenteditor.knowledgebase");
			importAgents();

			LOGGER.info("Finished import.");
			return true;
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AgentEditor_ImportFromStudioPro";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(AgentEditor_ImportFromStudioPro.class);

	private static final ObjectMapper objectMapper = new ObjectMapper();

	private void importModelDocumentsOfType(String documentTypeID) throws JsonProcessingException {
		java.util.List<CustomBlobDocumentInfo> customBlobDocumentList = Core.extensibility()
				.getCustomDocumentsOfType(documentTypeID);
		String documentFriendlyName = documentTypeID.substring(documentTypeID.lastIndexOf('.') + 1);
		LOGGER.info(customBlobDocumentList.size() + " " + documentFriendlyName
				+ "s document(s) found in the Mendix Model.");

		java.util.List<ModelDocument> modelDocuments = new ArrayList<>();
		for (CustomBlobDocumentInfo customBlobDocument : customBlobDocumentList) {
			modelDocuments.add(getModelDocument(customBlobDocument));
		}

		boolean isSuccess = false;

		switch (documentTypeID) {
		case "agenteditor.model":
			isSuccess = agenteditorcommons.proxies.microflows.Microflows.deployedModel_CreateUpdate_List(getContext(),
					modelDocuments);
			break;

		case "agenteditor.consumedMCPService":
			isSuccess = agenteditorcommons.proxies.microflows.Microflows
					.consumedMCPService_CreateUpdate_List(getContext(), modelDocuments);
			break;

		case "agenteditor.knowledgebase":
			isSuccess = agenteditorcommons.proxies.microflows.Microflows
					.knowledgeBase_CreateUpdate_List(getContext(), modelDocuments);
			break;
		}

		if (!isSuccess) {
			throw new IllegalArgumentException(
					"Creating/Updating " + documentFriendlyName + " documents failed due to bad input.");
		}
	}

	private void importAgents() throws JsonProcessingException {
		java.util.List<CustomBlobDocumentInfo> agentDocuments = Core.extensibility()
				.getCustomDocumentsOfType("agenteditor.agent");
		LOGGER.info(agentDocuments.size() + " agent document(s) found in the Mendix Model");

		java.util.List<AgentModelDocument> agentModelDocuments = new ArrayList<>();
		for (CustomBlobDocumentInfo agent : agentDocuments) {
			agentModelDocuments.add(getAgentModelDocument(agent));
		}

		boolean isSuccess = agenteditorcommons.proxies.microflows.Microflows.agent_CreateUpdate_List(getContext(),
				agentModelDocuments);
		if (!isSuccess) {
			throw new IllegalArgumentException("Creating/Updating the Agents failed due to bad input.");
		}
	}

	private AgentModelDocument getAgentModelDocument(CustomBlobDocumentInfo agentDocument)
			throws JsonProcessingException {

		String qualifiedName = agentDocument.qualifiedDocumentName();
		LOGGER.debug("Importing Agent with qualified name: '" + qualifiedName + "'.");

		String agentDocumentContent = agentDocument.content();

		String documentID = agentDocument.documentID().toString();
		LOGGER.debug(qualifiedName + " - documentID: " + documentID);

		JsonNode rootNode = objectMapper.readTree(agentDocumentContent);

		String modelQualifiedName = rootNode.has("modelQualifiedName") ? rootNode.get("modelQualifiedName").asText()
				: null;
		LOGGER.debug(qualifiedName + " - model: " + modelQualifiedName);

		String modelModelDocumentUUID = modelQualifiedName != null ? getModelModelDocumentUUID(modelQualifiedName)
				: null;
		LOGGER.debug(qualifiedName + " - model UUID: " + modelModelDocumentUUID);

		AgentModelDocument agentModelDocument = new AgentModelDocument(getContext());
		agentModelDocument.setDocumentID(getContext(), documentID);
		agentModelDocument.setContent(getContext(), agentDocumentContent);
		agentModelDocument.setModelDocumentID(getContext(), modelModelDocumentUUID);
		agentModelDocument.setQualifiedName(getContext(), qualifiedName);
		return agentModelDocument;

	}

	private String getModelModelDocumentUUID(String modelQualifiedName) throws JsonProcessingException {
		CustomBlobDocumentInfo modelDocument = Core.extensibility().getCustomDocumentByFullName(modelQualifiedName);
		if (modelDocument == null)
			return null;

		String documentID = modelDocument.documentID().toString();
		LOGGER.debug("Model for qualifiedName '" + modelQualifiedName + "' has documentID '" + documentID + "'.");

		return documentID;
	}

	private ModelDocument getModelDocument(CustomBlobDocumentInfo customBlobDocumentInfo)
			throws JsonProcessingException {
		String qualifiedName = customBlobDocumentInfo.qualifiedDocumentName();
		LOGGER.debug("Importing model with qualified name '" + qualifiedName + "'.");

		String modelDocumentContent = customBlobDocumentInfo.content();

		String documentID = customBlobDocumentInfo.documentID().toString();
		LOGGER.debug(qualifiedName + " - documentID: " + documentID);

		ModelDocument modelDocument = new ModelDocument(getContext());
		modelDocument.setDocumentID(getContext(), documentID);
		modelDocument.setContent(getContext(), modelDocumentContent);
		modelDocument.setQualifiedName(getContext(), qualifiedName);
		return modelDocument;
	}

	// END EXTRA CODE
}
