// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.MxLogger;

public class ImportDeployedModel extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String DocumentContent;
	private final java.lang.String QualifiedName;
	private final java.lang.String DocumentID;
	private final java.lang.String Provider;

	public ImportDeployedModel(
		IContext context,
		java.lang.String _documentContent,
		java.lang.String _qualifiedName,
		java.lang.String _documentID,
		java.lang.String _provider
	)
	{
		super(context);
		this.DocumentContent = _documentContent;
		this.QualifiedName = _qualifiedName;
		this.DocumentID = _documentID;
		this.Provider = _provider;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Provider,
					"No provider was specified for Model document " + QualifiedName
							+ ". The document could not be imported.");
			String importMicroflow = getImportMicroflow(Provider);
			requireNonNull(importMicroflow, "Model provider is not one of the allowed types for Model document " + QualifiedName 
							+ "The document could not be imported. Make sure your app contains the right compatible versions.");
			
			Map<String, Object> parametersAndValues = new java.util.HashMap<>();
			parametersAndValues.put("QualifiedName", QualifiedName);
			parametersAndValues.put("DocumentID", DocumentID);
			parametersAndValues.put("DocumentContent", DocumentContent);

			return Core.microflowCall(importMicroflow).withParams(parametersAndValues)
					.execute(this.getContext());

		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImportDeployedModel";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ImportDeployedModel.class);

	private String getImportMicroflow(String provider) {
		switch (provider) {
		case "MxCloudGenAI":
			return "MxGenAIConnector.MxCloudDeployedModel_CreateUpdateFromModel";
		case "Azure":
			return "OpenAIConnector.OpenAIDeployedModel_CreateUpdateFromModel_Azure";
		default:
			return null;
		}
	}
	// END EXTRA CODE
}
