// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import static java.util.Objects.requireNonNull;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.extensibility.CustomBlobDocumentInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.MxLogger;
import agentcommons.actions.Agent_Call_WithoutHistory;

/**
 * Imports all defined documents (such as agents and models) to the app's database so that they can be viewed at runtime and integrate with Agent Commons, Token Monitor, Observability etc.
 * This action can be used as part of your app's after startup logic.
 */
public class JA_CallAgentDocument extends UserAction<IMendixObject>
{
	private final java.lang.String Agent;
	/** @deprecated use DeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedModel;
	private final genaicommons.proxies.DeployedModel DeployedModel;
	private final IMendixObject OptionalContextObject;

	public JA_CallAgentDocument(
		IContext context,
		java.lang.String _agent,
		IMendixObject _deployedModel,
		IMendixObject _optionalContextObject
	)
	{
		super(context);
		this.Agent = _agent;
		this.__DeployedModel = _deployedModel;
		this.DeployedModel = _deployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), _deployedModel);
		this.OptionalContextObject = _optionalContextObject;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			CustomBlobDocumentInfo agentDocument = Core.extensibility().getCustomDocumentByFullName(Agent);
			requireNonNull(agentDocument, "Agent document not found.");
			
			List<IMendixObject> results = Core.createXPathQuery("//AgentCommons.Agent[ModelDocumentID=$documentID]")
		            .setVariable("documentID", agentDocument.documentID().toString())
		            .setAmount(1)
		            .execute(getContext());
			
			if (results.isEmpty() || results.get(0) == null) {
			    throw new NullPointerException("Agent object with name " + Agent + " does not exist.");
			}			
			
			IMendixObject agentIMendixObject = results.get(0);
			
			return Core.userActionCall("AgentCommons." + Agent_Call_WithoutHistory.class.getSimpleName())
					.withParams(agentIMendixObject, OptionalContextObject)
					.execute(getContext());
			
		} catch (Exception e) {
		    LOGGER.error(e);
		    return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CallAgentDocument";
	}

	// BEGIN EXTRA CODE
	
	private static final MxLogger LOGGER = new MxLogger(JA_CallAgentDocument.class);

	// END EXTRA CODE
}
