// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import java.util.UUID;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.extensibility.CustomBlobDocumentInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.MxLogger;
import agentcommons.proxies.PromptToUse;
import genaicommons.proxies.Request;
import genaicommons.proxies.Response;

public class JA_CallAgentDocument extends UserAction<IMendixObject>
{
	private final java.lang.String AgentDocumentID;
	/** @deprecated use DeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedModel;
	private final genaicommons.proxies.DeployedModel DeployedModel;
	private final IMendixObject OptionalContextObject;

	public JA_CallAgentDocument(
		IContext context,
		java.lang.String _agentDocumentID,
		IMendixObject _deployedModel,
		IMendixObject _optionalContextObject
	)
	{
		super(context);
		this.AgentDocumentID = _agentDocumentID;
		this.__DeployedModel = _deployedModel;
		this.DeployedModel = _deployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), _deployedModel);
		this.OptionalContextObject = _optionalContextObject;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.UUID agentUUID = UUID.fromString(AgentDocumentID);
		
		java.util.List<CustomBlobDocumentInfo> agents = Core.extensibility().getCustomDocumentsOfType("agenteditor.agent");
		agents.forEach(a -> LOGGER.info("agent" + a.content()));
		
		java.util.List<CustomBlobDocumentInfo> agents2 = Core.extensibility().getCustomDocumentsOfType("Agent");
		agents2.forEach(a -> LOGGER.info("agent2" + a.content()));
		
		CustomBlobDocumentInfo agentDocument = Core.extensibility().getCustomDocumentById(agentUUID);
		String agentDocumentContent = agentDocument.content();
		
		ObjectMapper objectMapper = new ObjectMapper();
		JsonNode rootNode = objectMapper.readTree(agentDocumentContent);
		String systemPrompt = rootNode.has("systemPrompt") ? rootNode.get("systemPrompt").toString() : null;
		String userPrompt = rootNode.has("userPrompt") ? rootNode.get("userPrompt").asText() : null;
		String contextEntityName = rootNode.has("entity") ? rootNode.get("entity").asText() : null;
		
		PromptToUse promptToUse = createPromptToUse(systemPrompt, userPrompt);
		

		applyVariables(promptToUse, contextEntityName, OptionalContextObject);
		
		Request request = Request.initialize(getContext(), Core.instantiate(getContext(), Request.entityName));
		request.setSystemPrompt(getContext(), promptToUse.getSystemPrompt(getContext()));
		
		Response response = genaicommons.proxies.microflows.Microflows.chatCompletions_WithoutHistory(getContext(), DeployedModel, promptToUse.getUserPrompt(getContext()), null, request);
		
		return response == null ? null : response.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CallAgentDocument";
	}

	// BEGIN EXTRA CODE
	
	private static final MxLogger LOGGER = new MxLogger(JA_CallAgentDocument.class);
	
	private void applyVariables(PromptToUse promptToUse, String contextEntityName, IMendixObject contextObject)
			throws CoreException {
		
		if (contextObject == null) {
			return;
		}
		

		// Check if Entity name is not empty)
		if (contextEntityName == null || contextEntityName.isBlank()) {
			throw new IllegalArgumentException(
					"Cannot replace variables: no Variables Entity is configured for this Agent.");
		}

		// Check if entity matches the passed object's entity
		if (!contextObject.getMetaObject().getName().equals(contextEntityName)) {
			throw new IllegalArgumentException(
					"Cannot replace variables for the passed ContextObject because it does not match the Context Entity that was configured for this Agent."
							+ " Passed object's entity: " + OptionalContextObject.getMetaObject().getName() + ", expected: "
							+ contextEntityName);
		}

		java.util.List<String> variableKeys = new java.util.ArrayList<>();
		// Replacement of variables if they are found in the passed object
		contextObject.getMembers(getContext()).forEach((a, v) -> {variableKeys.add(a);});
		
		for (String variable : variableKeys) {
			applyVariable(promptToUse, contextObject, variable);

		}
	}

	private void applyVariable(PromptToUse promptToUse, IMendixObject contextObject, String variableKey) {

	
		// Check variable key is not empty
		if (variableKey == null || variableKey.isBlank()) {
			LOGGER.warn("Skipping variable with empty Key attribute");
			return;
		}
		// Check variable is attribute of passed object
		if (!contextObject.hasMember(variableKey)) {
			LOGGER.warn(
					"Cannot replace variable {{" + variableKey + "}} because it is not found in the passed object.");
			replaceVariable(promptToUse, variableKey, "");
			return;
		}
		// Check value is not empty
		if (contextObject.getValue(getContext(), variableKey) == null) {
			LOGGER.warn("Cannot replace variable {{" + variableKey + "}} because it is empty in the passed object.");
			replaceVariable(promptToUse, variableKey, "");
			return;
		}
		// Apply variable
		replaceVariable(promptToUse, variableKey, contextObject.getValue(getContext(), variableKey).toString());
	}

	private void replaceVariable(PromptToUse promptToUse, String variableKey, String value) {
		agentcommons.proxies.microflows.Microflows.promptToUse_ApplyVariable(getContext(), promptToUse, variableKey,
				value);
	}
	
	private PromptToUse createPromptToUse(String systemPrompt, String userPrompt) {
		PromptToUse promptToUse = new PromptToUse(getContext());

		promptToUse.setSystemPrompt(systemPrompt);
		promptToUse.setUserPrompt(userPrompt);

		return promptToUse;
	}

	// END EXTRA CODE
}
