// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import java.util.ArrayList;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.extensibility.CustomBlobDocumentInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.MxLogger;
import agenteditorcommons.proxies.AgentModelDocument;
import agenteditorcommons.proxies.ModelModelDocument;

public class JA_ImportAgents extends UserAction<java.lang.Boolean>
{
	public JA_ImportAgents(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		LOGGER.info("Starting JA_ImportAgents");

		importModels();
		importAgents();

		LOGGER.info("Finished JA_ImportAgents");
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ImportAgents";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(JA_ImportAgents.class);

	private static final ObjectMapper objectMapper = new ObjectMapper();

	private void importModels() throws JsonProcessingException {
		java.util.List<CustomBlobDocumentInfo> modelDocuments = Core.extensibility()
				.getCustomDocumentsOfType("agenteditor.model");
		LOGGER.info(modelDocuments.size() + " model document(s) found in the Mendix Model");
		
		java.util.List<ModelModelDocument> modelModelDocuments = new ArrayList<>();
		for (CustomBlobDocumentInfo model : modelDocuments) {
			modelModelDocuments.add(getModelModelDocument(model));
		}
		
		boolean isSuccess = agenteditorcommons.proxies.microflows.Microflows.deployedModel_CreateUpdate_List(getContext(),
				modelModelDocuments);
		if (!isSuccess) {
			throw new IllegalArgumentException("Creating/Updating the Mendix Cloud Deployed Models failed due to bad input");
		}
	}

	private void importAgents() throws JsonProcessingException {
		java.util.List<CustomBlobDocumentInfo> agentDocuments = Core.extensibility()
				.getCustomDocumentsOfType("agenteditor.agent");
		LOGGER.info(agentDocuments.size() + " agent document(s) found in the Mendix Model");
		
		java.util.List<AgentModelDocument> agentModelDocuments = new ArrayList<>();
		for (CustomBlobDocumentInfo agent : agentDocuments) {
			agentModelDocuments.add(getAgentModelDocument(agent));
		}

		boolean isSuccess = agenteditorcommons.proxies.microflows.Microflows.agent_CreateUpdate_List(getContext(),
				agentModelDocuments);
		if (!isSuccess) {
			throw new IllegalArgumentException(
					"Creating/Updating the Agents failed due to bad input");
		}
	}

	private AgentModelDocument getAgentModelDocument(CustomBlobDocumentInfo agentDocument)
			throws JsonProcessingException {

		String qualifiedName = agentDocument.qualifiedDocumentName();
		LOGGER.debug("Importing Agent with qualified name: '" + qualifiedName + "'.");

		String agentDocumentContent = agentDocument.content();
		JsonNode rootNode = objectMapper.readTree(agentDocumentContent);

		String agentModelDocumentUUID = rootNode.has("modelDocumentUUID") ? rootNode.get("modelDocumentUUID").asText()
				: null;
		LOGGER.debug(qualifiedName + " - UUID: " + agentModelDocumentUUID);

		String modelQualifiedName = rootNode.has("modelQualifiedName") ? rootNode.get("modelQualifiedName").asText()
				: null;
		LOGGER.debug(qualifiedName + " - model: " + modelQualifiedName);

		String modelModelDocumentUUID = modelQualifiedName != null ? getModelModelDocumentUUID(modelQualifiedName)
				: null;
		LOGGER.debug(qualifiedName + " - model UUID: " + modelModelDocumentUUID);

		AgentModelDocument agentModelDocument = new AgentModelDocument(getContext());
		agentModelDocument.setContent(getContext(), agentDocumentContent);
		agentModelDocument.setModelModelDocumentUUID(getContext(), modelModelDocumentUUID);
		agentModelDocument.setQualifiedName(getContext(), qualifiedName);
		return agentModelDocument;

	}

	private String getModelModelDocumentUUID(String modelQualifiedName) throws JsonProcessingException {
		CustomBlobDocumentInfo modelDocument = Core.extensibility().getCustomDocumentByFullName(modelQualifiedName);
		if (modelDocument == null)
			return null;

		String modelModelDocumentUUID;

		JsonNode modelRoot = objectMapper.readTree(modelDocument.content());
		modelModelDocumentUUID = modelRoot.has("modelDocumentUUID") ? modelRoot.get("modelDocumentUUID").asText()
				: null;
		LOGGER.debug("Model for qualifiedName '" + modelQualifiedName + "' has modelDocumentUUID '"
				+ modelModelDocumentUUID + "'.");

		return modelModelDocumentUUID;
	}

	private ModelModelDocument getModelModelDocument(CustomBlobDocumentInfo modelDocument) throws JsonProcessingException {
		String qualifiedName = modelDocument.qualifiedDocumentName();
		LOGGER.debug("Importing model with qualified name '" + qualifiedName + "'.");

		String modelDocumentContent = modelDocument.content();
		JsonNode rootNode = objectMapper.readTree(modelDocumentContent);

		String modelDocumentUUID = rootNode.has("modelDocumentUUID") ? rootNode.get("modelDocumentUUID").asText()
				: null;
		LOGGER.debug(qualifiedName + " - modelDocumentUUID: " + modelDocumentUUID);
		
		ModelModelDocument modelModelDocument = new ModelModelDocument(getContext());
		modelModelDocument.setContent(getContext(), modelDocumentContent);
		modelModelDocument.setQualifiedName(getContext(), qualifiedName);
		return modelModelDocument;
		
	}

	// END EXTRA CODE
}
