// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package agenteditorcommons.actions;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.extensibility.CustomBlobDocumentInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import agenteditorcommons.impl.MxLogger;

public class JA_ImportAgents extends UserAction<java.lang.Boolean>
{
	public JA_ImportAgents(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		LOGGER.info("Starting JA_ImportAgents");

		importModels();
		importAgents();

		LOGGER.info("Finished JA_ImportAgents");
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ImportAgents";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(JA_ImportAgents.class);

	private void importModels() throws JsonProcessingException {
		java.util.List<CustomBlobDocumentInfo> modelDocuments = Core.extensibility()
				.getCustomDocumentsOfType("agenteditor.model");
		LOGGER.info(modelDocuments.size() + " model document(s) found in the Mendix Model");

		for (CustomBlobDocumentInfo model : modelDocuments) {
			importModel(model);
		}
	}

	private void importAgents() throws JsonProcessingException, CoreException {
		java.util.List<CustomBlobDocumentInfo> agentDocuments = Core.extensibility()
				.getCustomDocumentsOfType("agenteditor.agent");
		LOGGER.info(agentDocuments.size() + " agent document(s) found in the Mendix Model");

		for (CustomBlobDocumentInfo agent : agentDocuments) {
			importAgent(agent);
		}
	}

	private void importAgent(CustomBlobDocumentInfo agentDocument) throws JsonProcessingException, CoreException {

		String qualifiedName = agentDocument.qualifiedDocumentName();
		if (!validateQualifiedName(qualifiedName)) {
			throw new IllegalArgumentException("Qualified name '" + qualifiedName
					+ "' does not follow the ModuleName.DocumentName naming convention.");
		}

		LOGGER.debug("Importing Agent with qualified name: '" + qualifiedName + "'.");
		String agentDocumentContent = agentDocument.content();

		ObjectMapper objectMapper = new ObjectMapper();
		JsonNode rootNode = objectMapper.readTree(agentDocumentContent);
		String agentModelDocumentUUID = rootNode.has("modelDocumentUUID") ? rootNode.get("modelDocumentUUID").asText()
				: null;
		LOGGER.debug(qualifiedName + " - UUID: " + agentModelDocumentUUID);

		String modelQualifiedName = rootNode.has("modelQualifiedName") ? rootNode.get("modelQualifiedName").asText()
				: null;
		LOGGER.debug(qualifiedName + " - model: " + modelQualifiedName);
		String modelModelDocumentUUID = getModelModelDocumentUUID(modelQualifiedName);
		LOGGER.debug(qualifiedName + " - model UUID: " + modelModelDocumentUUID);

		boolean isSuccess = agenteditorcommons.proxies.microflows.Microflows.agent_CreateUpdate(getContext(),
				agentDocumentContent, qualifiedName, agentModelDocumentUUID, modelModelDocumentUUID );
		if (!isSuccess) {
			throw new IllegalArgumentException(
					"Creating/Updating the Agent '" + qualifiedName + "'  failed due to bad input");
		}

	}

	private boolean validateQualifiedName(String qualifiedName) {
		String[] parts = qualifiedName.split("\\.");
		String moduleName = parts[0];
		String documentName = parts[1];
		if (parts.length == 2) {
			moduleName = parts[0];
			documentName = parts[1];
			System.out.println("Found two parts: " + moduleName + " and " + documentName);
		} else {
			return false;
		}
		return true;
	}

	

	private String getModelModelDocumentUUID(String modelQualifiedName) throws JsonProcessingException {
		CustomBlobDocumentInfo modelDocument = Core.extensibility().getCustomDocumentByFullName(modelQualifiedName);
		if (modelDocument == null)
			return null;
		ObjectMapper objectMapper = new ObjectMapper();
		String modelModelDocumentUUID;

		JsonNode modelRoot = objectMapper.readTree(modelDocument.content());
		modelModelDocumentUUID = modelRoot.has("modelDocumentUUID") ? modelRoot.get("modelDocumentUUID").asText()
				: null;
		LOGGER.debug("Model for qualifiedName '" + modelQualifiedName + "' has modelDocumentUUID '"
				+ modelModelDocumentUUID + "'.");

		return modelModelDocumentUUID;
	}


	private void importModel(CustomBlobDocumentInfo modelDocument) throws JsonProcessingException {
		String qualifiedName = modelDocument.qualifiedDocumentName();
		if (!validateQualifiedName(qualifiedName)) {
			throw new IllegalArgumentException("Qualified name '" + qualifiedName
					+ "' does not follow the ModuleName.DocumentName naming convention.");

		}
		LOGGER.debug("Importing model with qualified name '" + qualifiedName + "'.");
		String documentName = qualifiedName.split("\\.")[1];
		String modelDocumentContent = modelDocument.content();

		LOGGER.debug("Model document content: " + modelDocumentContent);

		ObjectMapper objectMapper = new ObjectMapper();

		JsonNode rootNode = objectMapper.readTree(modelDocumentContent);

		String modelDocumentUUID = rootNode.has("modelDocumentUUID") ? rootNode.get("modelDocumentUUID").asText()
				: null;
		LOGGER.debug(qualifiedName + " - modelDocumentUUID: " + modelDocumentUUID);

		JsonNode providerFields = rootNode.has("providerFields") ? rootNode.get("providerFields") : null;
		String key = providerFields.has("key") ? providerFields.get("key").asText() : null;
		LOGGER.debug(qualifiedName + " - key: " + key);

		boolean isSuccess = agenteditorcommons.proxies.microflows.Microflows
				.mxCloudDeployedModel_CreateUpdate(getContext(), key, modelDocumentUUID, documentName);
		if (!isSuccess) {
			throw new IllegalArgumentException(
					"Creating/Updating the Mendix Cloud Deployed Model '" + qualifiedName + "' failed due to bad input");
		}
	}

	// END EXTRA CODE
}
