// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxgenaiconnector.actions;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import mxgenaiconnector.impl.MxLogger;
import okhttp3.*;
import okhttp3.sse.*;
import static java.util.Objects.requireNonNull;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CountDownLatch;

public class Request_ChatCompletions_Stream extends UserAction<IMendixObject>
{
	private final java.lang.String RequestBodyJSON;
	/** @deprecated use MxCloudDeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __MxCloudDeployedModel;
	private final mxgenaiconnector.proxies.MxCloudDeployedModel MxCloudDeployedModel;
	private final java.lang.String StreamingResponseWriterId;

	public Request_ChatCompletions_Stream(
		IContext context,
		java.lang.String _requestBodyJSON,
		IMendixObject _mxCloudDeployedModel,
		java.lang.String _streamingResponseWriterId
	)
	{
		super(context);
		this.RequestBodyJSON = _requestBodyJSON;
		this.__MxCloudDeployedModel = _mxCloudDeployedModel;
		this.MxCloudDeployedModel = _mxCloudDeployedModel == null ? null : mxgenaiconnector.proxies.MxCloudDeployedModel.initialize(getContext(), _mxCloudDeployedModel);
		this.StreamingResponseWriterId = _streamingResponseWriterId;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(this.RequestBodyJSON, "A Request object is required");
		requireNonNull(this.MxCloudDeployedModel, "A DeployedModel object is required");
		try {
			LOGGER.debug("Starting Request_ChatCompletions_Stream.");
			LOGGER.trace("Request: " + this.RequestBodyJSON);

			genaicommons.impl.StreamingImpl.createResponseMessage(getContext(), mxResponse);

			CountDownLatch latch = new CountDownLatch(1);
			OkHttpClient client = buildHttpClient();
			Request mxCloudRequest = buildMxCloudRequest();
			EventSourceListener listener = createEventSourceListener(latch);
			EventSource eventSource = EventSources.createFactory(client).newEventSource(mxCloudRequest, listener);

			awaitStreamCompletion(latch, eventSource);

			if (failureException != null) {
				throw failureException;
			}

			mxResponse.getResponse_Message().setContent(mxResponse.getResponseText());
			mxResponse.getResponse_Message().setMessage_ToolCall(mxToolCallList);

			return mxResponse.getMendixObject();

		} catch (Exception e) {
			LOGGER.error("Something went wrong for model: " + this.MxCloudDeployedModel.getDisplayName() + "\n" + e);
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ChatCompletions_Stream";
	}

	// BEGIN EXTRA CODE
	private static final mxgenaiconnector.impl.MxLogger LOGGER = new MxLogger(Request_ChatCompletions_Stream.class);
	
	private static final ObjectMapper mapper = new ObjectMapper();
	
	Exception failureException = null;
	
	genaicommons.proxies.Response mxResponse =  new genaicommons.proxies.Response(getContext());
	List<genaicommons.proxies.ToolCall> mxToolCallList = new ArrayList<genaicommons.proxies.ToolCall>();

	Map<Integer, Block> blocks = new HashMap<Integer, Block>();

	private OkHttpClient buildHttpClient() {
		return new OkHttpClient.Builder()
			.readTimeout(0, java.util.concurrent.TimeUnit.MILLISECONDS)
			.build();
	}

	private Request buildMxCloudRequest() throws Exception {
		MediaType JSON = MediaType.get("application/json; charset=utf-8");
		RequestBody requestBody = RequestBody.create(this.RequestBodyJSON, JSON);
		String accessKey = encryption.proxies.microflows.Microflows.decrypt(getContext(), this.MxCloudDeployedModel.getMxCloudDeployedModel_Configuration().getAccessToken());

		return new Request.Builder()
			.url(this.MxCloudDeployedModel.getMxCloudDeployedModel_Configuration().getResourceBaseUrl() + "/converse-stream")
			.header("Accept", "text/event-stream")
			.header("Content-Type", "application/json")
			.header("x-api-key", accessKey)
			.post(requestBody)
			.build();
	}

	private void handleStreamEvent(String type, JsonNode rootNode) throws IOException {
		int blockIndex = rootNode.path("contentBlockIndex").asInt();
		switch (type) {
		case "MESSAGE_START":
			break;

		case "CONTENT_BLOCK_START":
			Block startedBlock = rootNode.path("start").has("toolUse")
				? new ToolBlock()
				: new TextBlock();
			startedBlock.start(rootNode);
			blocks.put(blockIndex, startedBlock);
			break;

		case "CONTENT_BLOCK_DELTA":
			// Bedrock only emits CONTENT_BLOCK_START for tool-use blocks; text blocks
			// stream straight to DELTA, so lazily create a TextBlock when none exists yet.
			Block deltaBlock = blocks.computeIfAbsent(blockIndex, i -> new TextBlock());
			try {
				deltaBlock.append(rootNode);
			} catch (Exception e) {
				LOGGER.error("Failed to append delta to block at index " + blockIndex + " with StreamingResponseWriterId " + StreamingResponseWriterId + ": " + e.getMessage(), e);
				throw e;
			}
			break;

		case "CONTENT_BLOCK_STOP":
			Block stoppedBlock = blocks.get(blockIndex);
			if (stoppedBlock != null) {
				stoppedBlock.complete();
			}
			break;

		case "MESSAGE_STOP":
			String stopReason = rootNode.path("stopReason").asText();
			LOGGER.debug("Stop reason: " + stopReason);
			mxResponse.setStopReason(stopReason);
			break;

		case "METADATA":
			setResponseMetadata(rootNode);
			break;

		default:
			break;
		}
	}

	private void handleStreamFailure(Throwable t, Response response) {
		try {
			if (t != null) {
				failureException = (t instanceof Exception) ? (Exception) t : new Exception("Streaming failure", t);
			} else if (response != null) {
				String responseBody = response.body() != null ? response.body().string() : null;
				failureException = new IOException("HTTP " + response.code() + ": " + response.message() + " - " + responseBody);
			} else {
				failureException = new RuntimeException("Unknown SSE failure");
			}
		} catch (Exception e) {
			failureException = e;
		}
	}

	private EventSourceListener createEventSourceListener(CountDownLatch latch) {
		return new EventSourceListener() {
			@Override
			public void onOpen(EventSource eventSource, Response response) {
				LOGGER.debug("SSE Connection opened. HTTP " + response.code());
			}

			@Override
			public void onEvent(EventSource eventSource, String id, String type, String data) {
				try {
					JsonNode rootNode = mapper.readTree(data);
					handleStreamEvent(type, rootNode);
				} catch (Exception e) {
					LOGGER.error("Error parsing JSON: " + e.getMessage());
				}
			}

			@Override
			public void onClosed(EventSource eventSource) {
				LOGGER.debug("SSE Connection closed");
				latch.countDown(); // Signal completion
			}

			@Override
			public void onFailure(EventSource eventSource, Throwable t, Response response) {
				handleStreamFailure(t, response);
				latch.countDown();
			}
		};
	}

	private void awaitStreamCompletion(CountDownLatch latch, EventSource eventSource) throws InterruptedException {
		try {
			latch.await(); // Wait indefinitely until stream completes
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
			eventSource.cancel();
			throw e;
		}
		eventSource.cancel();
	}

	private interface Block {
		void start(JsonNode rootNode);
		void append(JsonNode rootNode) throws IOException;
		void complete();
	}

	private class TextBlock implements Block {

		@Override
		public void start(JsonNode rootNode) {
			// no state to initialize for a text block
		}

		@Override
		public void append(JsonNode rootNode) throws IOException {
			String chunkText = rootNode.path("delta").path("text").asText();
			genaicommons.impl.StreamingImpl.updateResponseText(mxResponse, chunkText);
			if (StreamingResponseWriterId != null) {
				genaicommons.impl.StreamingImpl.pushChunkToUI(getContext(), StreamingResponseWriterId, chunkText);
			}
		}

		@Override
		public void complete() {
			// text is already accumulated on mxResponse as it streams in
		}
	}

	private class ToolBlock implements Block {

		private genaicommons.proxies.ToolCall mxToolCall;

		@Override
		public void start(JsonNode rootNode) {
			mxToolCall = new genaicommons.proxies.ToolCall(getContext());
			mxToolCall.setName(rootNode.path("start").path("toolUse").path("name").asText());
			mxToolCall.setToolCallId(rootNode.path("start").path("toolUse").path("toolUseId").asText());
			mxToolCallList.add(mxToolCall);
		}

		@Override
		public void append(JsonNode rootNode) throws IOException {
			String currentText = mxToolCall.getInput();
			String chunkText = rootNode.path("delta").path("toolUse").path("input").asText();
			mxToolCall.setInput(currentText == null ? chunkText : currentText + chunkText);
		}

		@Override
		public void complete() {
			if (mxToolCall.getInput() == null || mxToolCall.getInput().isBlank()) {
				mxToolCall.setInput("{}");
			}
			LOGGER.debug("Toolcall added to response.");
		}
	}

	private void setResponseMetadata(JsonNode rootNode) {
		
		mxResponse.setRequestTokens(rootNode.path("usage").path("inputTokens").asInt());
		mxResponse.setResponseTokens(rootNode.path("usage").path("outputTokens").asInt());
		mxResponse.setTotalTokens(rootNode.path("usage").path("totalTokens").asInt());
		
	}
	// END EXTRA CODE
}
