// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpserver.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.server.McpServerFeatures;
import io.modelcontextprotocol.server.McpSyncServer;
import io.modelcontextprotocol.spec.McpSchema;
import mcpserver.impl.McpServerRegistry;
import mcpserver.impl.MxLogger;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AddPrompt extends UserAction<IMendixObject>
{
	private final java.lang.String Name;
	private final java.lang.String Description;
	/** @deprecated use com.mendix.utils.ListUtils.map(Parameters, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __Parameters;
	private final java.util.List<mcpserver.proxies.PromptArgument> Parameters;
	private final java.lang.String Microflow;
	/** @deprecated use McpServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __McpServer;
	private final mcpserver.proxies.McpServer McpServer;

	public AddPrompt(
		IContext context,
		java.lang.String _name,
		java.lang.String _description,
		java.util.List<IMendixObject> _parameters,
		java.lang.String _microflow,
		IMendixObject _mcpServer
	)
	{
		super(context);
		this.Name = _name;
		this.Description = _description;
		this.__Parameters = _parameters;
		this.Parameters = java.util.Optional.ofNullable(_parameters)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(parametersElement -> mcpserver.proxies.PromptArgument.initialize(getContext(), parametersElement))
			.collect(java.util.stream.Collectors.toList());
		this.Microflow = _microflow;
		this.__McpServer = _mcpServer;
		this.McpServer = _mcpServer == null ? null : mcpserver.proxies.McpServer.initialize(getContext(), _mcpServer);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Create Prompt NPE
		mcpserver.proxies.Prompt promptNpe = new mcpserver.proxies.Prompt(getContext());
		promptNpe.setName(Name);
		promptNpe.setDescription(Description);
		promptNpe.setMicroflowName(Microflow);
		promptNpe.setPrompt_McpServer(McpServer);
		// Recreate parameters to return a clean unreferenced response
		Parameters.forEach(e -> {
			mcpserver.proxies.PromptArgument copiedArg = new mcpserver.proxies.PromptArgument(getContext());
			copiedArg.setName(e.getName());
			copiedArg.setDescription(e.getDescription());
			copiedArg.setRequired(e.getRequired());
			copiedArg.setPromptArgument_Prompt(promptNpe);
		});

		// Get McpServer instance
		McpSyncServer server = McpServerRegistry.getServerInstance(this.McpServer.getMendixObject().getId().toLong());

		// Create the prompt spec and add to server
		List<McpSchema.PromptArgument> mcpPromptArguments = Parameters.stream().map(e ->
				new McpSchema.PromptArgument(e.getName(), e.getDescription(), e.getRequired())).toList();

		McpServerFeatures.SyncPromptSpecification syncPromptSpecification = new McpServerFeatures.SyncPromptSpecification(
				new McpSchema.Prompt(Name, Description, mcpPromptArguments),
				(exchange, request) -> {
					// some request logging
					String threadName = Thread.currentThread().getName();
					long start = System.currentTimeMillis();
					LOGGER.trace(threadName + ": Start processing getPrompt " + Name + ", MF: " + Microflow);

					// process the request, create a new context first
					IContext ctx = Core.createSystemContext();

					Map<String, Object> args = new HashMap<>(request.arguments());
					args.put("Prompt", promptNpe);

					try {
						IMendixObject mxExecResult = Core.microflowCall(Microflow).withParams(args).execute(ctx);
						mcpserver.proxies.PromptMessage mxPromptMessage = mcpserver.proxies.PromptMessage.initialize(ctx, mxExecResult);

						McpSchema.PromptMessage mcpPromptMessage = new McpSchema.PromptMessage(
								McpSchema.Role.valueOf(
										mxPromptMessage.getRole()),
								new McpSchema.TextContent(mxPromptMessage.getContent())
						);
						return new McpSchema.GetPromptResult(Description, List.of(mcpPromptMessage));
					} finally {
						LOGGER.trace(threadName + ": End processing getPrompt '" + Name + ". Duration: " + (System.currentTimeMillis() - start) + "ms.");
					}
				}
		);
		server.addPrompt(syncPromptSpecification);

		return promptNpe.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddPrompt";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpserver.impl.MxLogger(AddPrompt.class);
	// END EXTRA CODE
}
