// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpserver.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.json.McpJsonDefaults;
import io.modelcontextprotocol.server.McpServerFeatures;
import io.modelcontextprotocol.server.McpSyncServer;
import io.modelcontextprotocol.spec.McpSchema;
import mcpserver.impl.McpServerRegistry;
import mcpserver.impl.McpSessionManager;
import mcpserver.impl.MxLogger;
import mcpserver.proxies.TextContent;
import mcpserver.proxies.Tool;
import static java.util.Objects.requireNonNull;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Map.Entry;

/**
 * Registers a tool with the MCP Server that gets exposed to MCP clients. If the model chooses to call the tool, the selected microflow gets executed.
 */
public class AddTool extends UserAction<IMendixObject>
{
	/** @deprecated use McpServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __McpServer;
	private final mcpserver.proxies.McpServer McpServer;
	private final java.lang.String Name;
	private final java.lang.String Description;
	private final java.lang.String ExecutingMicroflow;
	private final java.lang.String Schema;

	public AddTool(
		IContext context,
		IMendixObject _mcpServer,
		java.lang.String _name,
		java.lang.String _description,
		java.lang.String _executingMicroflow,
		java.lang.String _schema
	)
	{
		super(context);
		this.__McpServer = _mcpServer;
		this.McpServer = _mcpServer == null ? null : mcpserver.proxies.McpServer.initialize(getContext(), _mcpServer);
		this.Name = _name;
		this.Description = _description;
		this.ExecutingMicroflow = _executingMicroflow;
		this.Schema = _schema;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(Name,"Name is required.");
		requireNonNull(Description,"Description is required.");
		requireNonNull(McpServer,"MCPServer is required.");		
		
		// Create NPE for the tool
		mcpserver.proxies.Tool toolNpe = new mcpserver.proxies.Tool(getContext());
		toolNpe.setName(Name);
		toolNpe.setDescription(Description);
		
		// Get the JsonSchema for the tool
		Map<String, Object> inputSchema = getJsonSchemaForTool();
		
		toolNpe.setMicroflowName(ExecutingMicroflow);
		toolNpe.setTool_McpServer(McpServer);

		// Add the tool to the server
		McpSyncServer server = McpServerRegistry.getServerInstance(this.McpServer.getMendixObject().getId().toLong());
		
		// Get the session manager for this server instance
		Long serverId = this.McpServer.getMendixObject().getId().toLong();
		McpSessionManager sessionManager = McpServerRegistry.getSessionManager(serverId);
		
		if (sessionManager == null) {
			LOGGER.error("ERROR: SessionManager for Server ID " + serverId + " not found!");
			throw new Exception("SessionManager for Server ID " + serverId + " not found");
		}

		McpServerFeatures.SyncToolSpecification tool = new McpServerFeatures.SyncToolSpecification(
				McpSchema.Tool.builder(toolNpe.getName(), inputSchema).description(toolNpe.getDescription()).build(),
				(exchange, request) -> {
					String threadName = Thread.currentThread().getName();
					long start = System.currentTimeMillis();
					LOGGER.trace(threadName + ": Start processing tool call " + Name + ", microflow: " + ExecutingMicroflow);
					try {
						// Get user context from session (falls back to system context if no session)
						IContext contextUser = sessionManager.getContextFromSession(exchange);
						Map<String, Object> args = new HashMap<>(request.arguments());

						manipulateArgsForMicroflowCall(toolNpe, args);
						mcpserver.proxies.TextContent mxTextContent = getTextContextFromToolMicroflow(args, contextUser);

						McpSchema.TextContent mcpTextContent = McpSchema.TextContent.builder(mxTextContent.getContent()).build();
						return McpSchema.CallToolResult.builder()
							.content(List.of(mcpTextContent))
							.isError(false)
							.build();

					}catch (Exception e) {
						LOGGER.error(e, threadName + ": Error occurred during tool call.");
						McpSchema.TextContent errorContent = McpSchema.TextContent.builder(
							"Error occurred during tool call: " + e.getMessage()).build();
						return McpSchema.CallToolResult.builder()
							.content(List.of(errorContent))
							.isError(true)
							.build();
						
					}finally {
						LOGGER.trace(threadName + ": End processing tool call '" + Name + ". Duration: " + (System.currentTimeMillis() - start) + "ms.");
					}
				}
		);
		server.addTool(tool);

		return toolNpe.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddTool";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpserver.impl.MxLogger(AddTool.class);
	
	/**
	 * Convert DateTime input values to correct DataType. Add Tool to args
	 * @param tool that gets added to the args
	 * @param args args that get manipulated
	 */
	private void manipulateArgsForMicroflowCall(Tool tool, Map<String, Object> args) {
		Map<String, IDataType> allParameters = Core.getInputParameters(ExecutingMicroflow);
		Map<String, IDataType> parametersAndTypes = getInputParametersPrimitives();

		for (Entry<String, IDataType> entry : parametersAndTypes.entrySet()) {
	        String paramName = entry.getKey();
	        IDataType type = entry.getValue();

	        if (!args.containsKey(paramName)) {
	        	continue;
	        }

	        Object originalValue = args.get(paramName);
	        Object convertedValue = convertValueToExpectedType(originalValue, type, paramName);

	        if (convertedValue != null) {
	        	args.put(paramName, convertedValue);
	        }
	    }

		// Only inject the Tool object if the microflow has an object-type parameter named "Tool".
		// Prevents collision when a business microflow has a primitive parameter also named "Tool".
		IDataType toolParamType = allParameters.get("Tool");
		if (toolParamType != null && toolParamType.getObjectType() != null) {
			args.put("Tool", tool.getMendixObject());
		}
	}
	
	/**
	 * Converts a value to the expected Mendix data type
	 * @param value the original value from the LLM
	 * @param dataType the expected Mendix data type
	 * @param paramName parameter name for logging purposes
	 * @return converted value or null if no conversion needed
	 */
	private Object convertValueToExpectedType(Object value, IDataType dataType, String paramName) {
		IDataType.DataTypeEnum type = dataType.getType();
		
		if (IDataType.DataTypeEnum.Datetime.equals(type)) {
			return parseDateTime(value, paramName);
		} else if (IDataType.DataTypeEnum.Long.equals(type)) {
			return parseLong(value, paramName);
		} else if (IDataType.DataTypeEnum.Integer.equals(type)) {
			return parseInteger(value, paramName);
		} else if (IDataType.DataTypeEnum.Decimal.equals(type)) {
			return parseDecimal(value, paramName);
		} else if (IDataType.DataTypeEnum.Boolean.equals(type)) {
			return parseBoolean(value, paramName);
		}
		
		return null; // No conversion needed
	}
	
	/**
	 * Parses a value to a Date, supporting ISO strings (primary) and Unix timestamps (fallback)
	 * @param value the value to parse
	 * @param paramName parameter name for logging
	 * @return parsed Date
	 */
	private Date parseDateTime(Object value, String paramName) {
		String dateString = value.toString();
		
		try {
			// Try parsing as ISO Instant first (e.g., 2025-12-06T10:00:00Z)
			return Date.from(java.time.Instant.parse(dateString));
		} catch (java.time.format.DateTimeParseException e) {
			try {
				// Try parsing as ISO LocalDate (e.g., 2025-12-06 - converted to start-of-day)
				return Date.from(java.time.LocalDate.parse(dateString)
						.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant());
			} catch (java.time.format.DateTimeParseException e1) {
				try {
					// Fallback: Try parsing as Unix timestamp
					long timestamp = Long.parseLong(dateString);
					
					// Detect if timestamp is in seconds or milliseconds
					// Timestamps in seconds are typically 10 digits (until year 2286)
					// Timestamps in milliseconds are typically 13 digits
					if (timestamp < 10000000000L) {
						// Timestamp is in seconds, convert to milliseconds
						timestamp = timestamp * 1000;
					}
					
					return new Date(timestamp);
				} catch (NumberFormatException e2) {
					LOGGER.error("Failed to parse datetime value for parameter '" + paramName + "': " + dateString);
					throw e;
				}
			}
		}
	}
	
	/**
	 * Parses a value to Long if it's not already a Long
	 * @param value the value to parse
	 * @param paramName parameter name for logging
	 * @return parsed Long or null if already a Long
	 */
	private Long parseLong(Object value, String paramName) {
		if (value instanceof Long) {
			return null; // Already correct type
		}
		
		try {
			return Long.parseLong(value.toString());
		} catch (NumberFormatException e) {
			LOGGER.error("Failed to parse Long value for parameter '" + paramName + "': " + value);
			throw e;
		}
	}
	
	/**
	 * Parses a value to Integer if it's not already an Integer
	 * @param value the value to parse
	 * @param paramName parameter name for logging
	 * @return parsed Integer or null if already an Integer
	 */
	private Integer parseInteger(Object value, String paramName) {
		if (value instanceof Integer) {
			return null; // Already correct type
		}
		
		try {
			return Integer.parseInt(value.toString());
		} catch (NumberFormatException e) {
			LOGGER.error("Failed to parse Integer value for parameter '" + paramName + "': " + value);
			throw e;
		}
	}
	
	/**
	 * Parses a value to BigDecimal if it's not already a BigDecimal
	 * @param value the value to parse
	 * @param paramName parameter name for logging
	 * @return parsed BigDecimal or null if already a BigDecimal
	 */
	private java.math.BigDecimal parseDecimal(Object value, String paramName) {
		if (value instanceof java.math.BigDecimal) {
			return null; // Already correct type
		}
		
		try {
			return new java.math.BigDecimal(value.toString());
		} catch (NumberFormatException e) {
			LOGGER.error("Failed to parse Decimal value for parameter '" + paramName + "': " + value);
			throw e;
		}
	}
	
	/**
	 * Parses a value to Boolean if it's not already a Boolean
	 * @param value the value to parse
	 * @param paramName parameter name for logging
	 * @return parsed Boolean or null if already a Boolean
	 */
	private Boolean parseBoolean(Object value, String paramName) {
		if (value instanceof Boolean) {
			return null; // Already correct type
		}
		
		return Boolean.parseBoolean(value.toString());
	}
	
	
	/**
	 * executes the tool microflow; if the microflow returns a String, a new TextContent is created and the Content is set with the string.
	 * If the microflow already returns a TextContext, it gets returned
	 * @param args list of parameters with values
	 * @param ctx context to execute to microflow
	 * @return TextContent
	 */
	private mcpserver.proxies.TextContent getTextContextFromToolMicroflow(Map<String, Object> args, IContext ctx){
		//Using getContext() for creating the TextContent (so there is no need for entity access for the user), while user ctx for microflow execution
		if(isToolReturnTypeString()) {
			String stringResult = Core.microflowCall(ExecutingMicroflow).withParams(args).execute(ctx);
			mcpserver.proxies.TextContent mxTextContentFromString = new TextContent(getContext());
			mxTextContentFromString.setContent(stringResult);
			return mxTextContentFromString;
			
		} else
		{
			IMendixObject mxExecResult = Core.microflowCall(ExecutingMicroflow).withParams(args).execute(ctx);
			return mcpserver.proxies.TextContent.initialize(getContext(), mxExecResult);
		}		
	}
	
	/**
	 * checks if the return type of the tool microflow is of Type string
	 */
	private boolean isToolReturnTypeString() {
		IDataType returnType = Core.getReturnType(ExecutingMicroflow);
		
		if(returnType != null && IDataType.DataTypeEnum.String.equals(returnType.getType())) {
			return true;
		}
		
		return false;
	}
	
	/**
	 * Gets the JSON schema map for the tool, either from the provided Schema string or generated from the microflow
	 * @return schema as Map
	 * @throws IOException
	 */
	private Map<String, Object> getJsonSchemaForTool() throws IOException {
		if(Schema != null && !Schema.isEmpty()) {
			return parseSchemaStringToMap(Schema);
		} else {
			return getSchemaFromMicroflow();
		}
	}

	/**
	 * Parses a JSON schema string into a Map
	 * @param schemaString JSON schema as string
	 * @return schema as Map
	 * @throws IOException
	 */
	@SuppressWarnings("unchecked")
	private Map<String, Object> parseSchemaStringToMap(String schemaString) throws IOException {
		return McpJsonDefaults.getMapper().readValue(schemaString, Map.class);
	}

	/**
	 * Creates an empty schema map for tools with no parameters
	 * @return empty schema Map
	 */
	private Map<String, Object> createEmptySchema() {
		Map<String, Object> schema = new HashMap<>();
		schema.put("type", "object");
		schema.put("properties", new HashMap<>());
		return schema;
	}


	/**
	 * Creates a Schema definition for all primitive input parameters of the tool microflow
	 * @return schema as Map
	 */
	private Map<String, Object> getSchemaFromMicroflow() {
		Map<String, IDataType> inputParameters = getInputParametersPrimitives();

		// If no parameters, return empty schema
		if (inputParameters.isEmpty()) {
			return createEmptySchema();
		}

		Map<String, Object> properties = new HashMap<>();
		List<String> required = new ArrayList<>();

		for (Map.Entry<String, IDataType> param : inputParameters.entrySet()) {
			String name = param.getKey();
			IDataType.DataTypeEnum dataType = param.getValue().getType();

			Map<String, Object> typeNode = new HashMap<>();

			// Handle DateTime as string with date format for better LLM compatibility
			if (IDataType.DataTypeEnum.Datetime.equals(dataType)) {
				typeNode.put("type", "string");
				typeNode.put("format", "date-time");
				typeNode.put("description", "ISO 8601 date-time string (e.g., 2025-12-06T10:00:00Z) or date only (e.g., 2025-12-06)");
			}
			// Handle enum case to expose possible enum values
			else if (dataType.toString().toLowerCase().equals("enumeration")) {
				Set<String> enumKeySet = param.getValue().getEnumeration().getEnumValues().keySet();
				typeNode.put("enum", new ArrayList<>(enumKeySet));
				typeNode.put("type", "string");
			}
			// Handle other types
			else {
				String type = parameterGetType(param);
				if (type.equals("number") || type.equals("integer")) {
					// Accept both numeric and string representations — LLMs sometimes
					// send numbers as JSON strings. Our coercion in manipulateArgsForMicroflowCall
					// converts strings to the correct Mendix type before microflow execution.
					Map<String, Object> asNumber = new HashMap<>();
					asNumber.put("type", type);
					Map<String, Object> asString = new HashMap<>();
					asString.put("type", "string");
					typeNode.put("anyOf", List.of(asNumber, asString));
				} else {
					typeNode.put("type", type);
				}
			}

			properties.put(name, typeNode);
			required.add(name);
		}

		Map<String, Object> schema = new HashMap<>();
		schema.put("type", "object");
		schema.put("properties", properties);
		schema.put("required", required);
		return schema;
	}

	/**
	 * determines the type of parameter. Long/Decimal converted to "number", enumeration to "enum"
	 * @param inputParameter
	 */
	private String parameterGetType(Entry<String, IDataType> inputParameter) {
		String type = inputParameter.getValue().toString().toLowerCase();
		if(type.equals("long") || type.equals("decimal")) {
			type = "number";
		} else if (type.equals("integer")) {
			type = "integer";
		} else if (type.equals("enumeration")) {
			type = "enum";
		}
		return type;
	}
	/**
	 * Returns a list of primitive input parameters for the tool microflow
	 */
	private Map<String, IDataType> getInputParametersPrimitives(){
		Map<String, IDataType> inputParameters = Core.getInputParameters(ExecutingMicroflow);
		Map<String, IDataType> inputParametersModified = new HashMap<>();

		for(Map.Entry<String, IDataType> entry : inputParameters.entrySet()) {
			String objectType = entry.getValue().getObjectType();
			if (objectType == null) {
				inputParametersModified.put(entry.getKey(), entry.getValue());
			}
		}
		return inputParametersModified;
	}	
	// END EXTRA CODE
}
