// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpserver.actions;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.server.McpServerFeatures;
import io.modelcontextprotocol.server.McpSyncServer;
import io.modelcontextprotocol.server.McpSyncServerExchange;
import io.modelcontextprotocol.spec.McpSchema;
import mcpserver.impl.McpServerRegistry;
import mcpserver.impl.McpSessionManager;
import mcpserver.impl.MxLogger;
import mcpserver.proxies.TextContent;
import mcpserver.proxies.Tool;
import static java.util.Objects.requireNonNull;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Map.Entry;

/**
 * Registers a tool with the MCP Server that gets exposed to MCP clients. If the model chooses to call the tool, the selected microflow gets executed.
 * 
 * Currently, the current User is not in scope of the tool microflow.
 */
public class AddTool extends UserAction<IMendixObject>
{
	/** @deprecated use McpServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __McpServer;
	private final mcpserver.proxies.McpServer McpServer;
	private final java.lang.String Name;
	private final java.lang.String Description;
	private final java.lang.String ExecutingMicroflow;
	private final java.lang.String Schema;

	public AddTool(
		IContext context,
		IMendixObject _mcpServer,
		java.lang.String _name,
		java.lang.String _description,
		java.lang.String _executingMicroflow,
		java.lang.String _schema
	)
	{
		super(context);
		this.__McpServer = _mcpServer;
		this.McpServer = _mcpServer == null ? null : mcpserver.proxies.McpServer.initialize(getContext(), _mcpServer);
		this.Name = _name;
		this.Description = _description;
		this.ExecutingMicroflow = _executingMicroflow;
		this.Schema = _schema;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		requireNonNull(Name,"Name is required.");
		requireNonNull(Description,"Description is required.");
		requireNonNull(McpServer,"MCPServer is required.");		
		
		// Create NPE for the tool
		mcpserver.proxies.Tool toolNpe = new mcpserver.proxies.Tool(getContext());
		toolNpe.setName(Name);
		toolNpe.setDescription(Description);
		
		// Get the JsonSchema for the tool
		McpSchema.JsonSchema inputSchema = getJsonSchemaForTool();
		
		toolNpe.setMicroflowName(ExecutingMicroflow);
		toolNpe.setTool_McpServer(McpServer);

		// Add the tool to the server
		McpSyncServer server = McpServerRegistry.getServerInstance(this.McpServer.getMendixObject().getId().toLong());

		McpServerFeatures.SyncToolSpecification tool = new McpServerFeatures.SyncToolSpecification(
				new McpSchema.Tool(toolNpe.getName(), null, toolNpe.getDescription(), inputSchema, new HashMap<>(), null, new HashMap<>()),
				(exchange, arguments) -> {
					String threadName = Thread.currentThread().getName();
					long start = System.currentTimeMillis();
					LOGGER.trace(threadName + ": Start processing tool call " + Name + ", MF: " + ExecutingMicroflow);
					try {
						IContext contextUser = McpSessionManager.getContextFromSession(exchange);
						Map<String, Object> args = new HashMap<>(arguments);

						manipulateArgsForMicroflowCall(toolNpe, args);
						mcpserver.proxies.TextContent mxTextContent = getTextContextFromToolMicroflow(args, contextUser);

						McpSchema.TextContent mcpTextContent = new McpSchema.TextContent(mxTextContent.getContent());
						return new McpSchema.CallToolResult(
							List.of(mcpTextContent),
							false,
							new HashMap<>()
						);
						
					}catch (Exception e) { 
						LOGGER.error(e, threadName + ": Error occurred during tool call.");
						McpSchema.TextContent errorContent = new McpSchema.TextContent(
							"Error occurred during tool call: " + e.getMessage()
						);
						return new McpSchema.CallToolResult(
							List.of(errorContent),
							true,
							new HashMap<>()
						);
						
					}finally {
						LOGGER.trace(threadName + ": End processing tool call '" + Name + ". Duration: " + (System.currentTimeMillis() - start) + "ms.");
					}
				}
		);
		server.addTool(tool);

		return toolNpe.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddTool";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpserver.impl.MxLogger(AddTool.class);
	
	/**
	 * Convert DateTime input values to correct DataType. Add Tool to args
	 * @param tool that gets added to the args
	 * @param args args that get manipulated
	 */
	private void manipulateArgsForMicroflowCall(Tool tool, Map<String, Object> args) {
		Map<String, IDataType> parametersAndTypes = getInputParametersPrimitives();
		
		
		for (Entry<String, IDataType> entry : parametersAndTypes.entrySet()) {
	        String paramName = entry.getKey();
	        IDataType type = entry.getValue();
	        // DateTime values need to be converted
	        if (IDataType.DataTypeEnum.Datetime.equals(type.getType()) && args.containsKey(paramName)) {
	        	Object originalValue = args.get(paramName);
	        	Date date = new Date(Long.parseLong(originalValue.toString()));
	            args.put(paramName, date);
	        }
	    }
		args.put("Tool", tool);
	}
	
	
	/**
	 * executes the tool microflow; if the microflow returns a String, a new TextContent is created and the Content is set with the string.
	 * If the microflow already returns a TextContext, it gets returned
	 * @param args list of parameters with values
	 * @param ctx context to execute to microflow
	 * @return TextContent
	 */
	private mcpserver.proxies.TextContent getTextContextFromToolMicroflow(Map<String, Object> args, IContext ctx){
		//Using getContext() for creating the TextContent (so there is no need for entity access for the user), while user ctx for microflow execution
		if(isToolReturnTypeString()) {
			String stringResult = Core.microflowCall(ExecutingMicroflow).withParams(args).execute(ctx);
			mcpserver.proxies.TextContent mxTextContentFromString = new TextContent(getContext());
			mxTextContentFromString.setContent(stringResult);
			return mxTextContentFromString;
			
		} else
		{
			IMendixObject mxExecResult = Core.microflowCall(ExecutingMicroflow).withParams(args).execute(ctx);
			return mcpserver.proxies.TextContent.initialize(getContext(), mxExecResult);
		}		
	}
	
	/**
	 * checks if the return type of the tool microflow is of Type string
	 */
	private boolean isToolReturnTypeString() {
		IDataType returnType = Core.getReturnType(ExecutingMicroflow);
		
		if(returnType != null && IDataType.DataTypeEnum.String.equals(returnType.getType())) {
			return true;
		}
		
		return false;
	}
	
	/**
	 * Gets the JsonSchema for the tool, either from the provided Schema string or generated from the microflow
	 * @return McpSchema.JsonSchema object
	 * @throws JsonProcessingException
	 */
	private McpSchema.JsonSchema getJsonSchemaForTool() throws JsonProcessingException {
		if(Schema != null && !Schema.isEmpty()) {
			return parseSchemaStringToJsonSchema(Schema);
		} else {
			return getSchemaFromMicroflow();
		}
	}


	/**
	 * Parses a JSON schema string into a McpSchema.JsonSchema object
	 * @param schemaString JSON schema as string
	 * @return McpSchema.JsonSchema object
	 * @throws JsonProcessingException
	 */
	private McpSchema.JsonSchema parseSchemaStringToJsonSchema(String schemaString) throws JsonProcessingException {
		// This is a simple parser
		com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
		com.fasterxml.jackson.databind.JsonNode schemaNode = mapper.readTree(schemaString);
		
		// Extract type
		String type = schemaNode.has("type") ? schemaNode.get("type").asText() : "object";
		
		// Extract properties
		Map<String, Object> properties = new HashMap<>();
		if (schemaNode.has("properties")) {
			com.fasterxml.jackson.databind.JsonNode propertiesNode = schemaNode.get("properties");
			propertiesNode.fields().forEachRemaining(entry -> {
				properties.put(entry.getKey(), mapper.convertValue(entry.getValue(), Object.class));
			});
		}
		
		// Extract required fields
		List<String> required = null;
		if (schemaNode.has("required")) {
			com.fasterxml.jackson.databind.JsonNode requiredNode = schemaNode.get("required");
			required = new ArrayList<>();
			for (com.fasterxml.jackson.databind.JsonNode item : requiredNode) {
				required.add(item.asText());
			}
		}
		
		return new McpSchema.JsonSchema(
			type,
			properties,
			required,
			null,
			new HashMap<>(),
			new HashMap<>()
		);
	}
	
	/**
	 * Creates an empty schema for tools with no parameters
	 * @return Empty McpSchema.JsonSchema
	 */
	private McpSchema.JsonSchema createEmptySchema() {
		return new McpSchema.JsonSchema(
			"object",
			new HashMap<>(),
			null,
			null,
			new HashMap<>(),
			new HashMap<>()
		);
	}
	
	
	/**
	 * Creates a Schema definition for all primitive input parameters of the tool microflow
	 * @return Schema definition as String
	 * @throws JsonProcessingException
	 */
	private McpSchema.JsonSchema getSchemaFromMicroflow() {
		Map<String, IDataType> inputParameters = getInputParametersPrimitives();
		
		// If no parameters, return empty schema
		if (inputParameters.isEmpty()) {
			return createEmptySchema();
		}
		
		Map<String, Object> properties = new HashMap<>();
		List<String> required = new ArrayList<>();

		for (Map.Entry<String, IDataType> param : inputParameters.entrySet()) {
			String name = param.getKey();
			String type = parameterGetType(param);

			Map<String, Object> typeNode = new HashMap<>();
			typeNode.put("type", type);

			// Handle enum case to expose possible enum values
			if ("enum".equals(type)) {
				Set<String> enumKeySet = param.getValue().getEnumeration().getEnumValues().keySet();
				typeNode.put("enum", new ArrayList<>(enumKeySet));
				typeNode.put("type", "string");
			}
			
			properties.put(name, typeNode);
			required.add(name);
		}
		
		return new McpSchema.JsonSchema(
			"object",
			properties,
			required,
			null,
			new HashMap<>(),
			new HashMap<>()
		);
	}

	
	
	/**
	 * determines the type of parameter. Long/Decimal/Datetime converted to "number", enumeration to "enum"
	 * @param inputParameter
	 */
	private String parameterGetType(Entry<String, IDataType> inputParameter) {
		String type = inputParameter.getValue().toString().toLowerCase();
		if(type.equals("long") || type.equals("decimal") || type.equals("datetime")) {
			type = "number";
		} else if (type.equals("enumeration")) {
			type = "enum";
		}
		return type;
	}
	/**
	 * Returns a list of primitive input parameters for the tool microflow
	 */
	private Map<String, IDataType> getInputParametersPrimitives(){
		Map<String, IDataType> inputParameters = Core.getInputParameters(ExecutingMicroflow);
		Map<String, IDataType> inputParametersModified = new HashMap<>();

		for(Map.Entry<String, IDataType> entry : inputParameters.entrySet()) {
			String objectType = entry.getValue().getObjectType();
			if (objectType == null) {
				inputParametersModified.put(entry.getKey(), entry.getValue());
			}
		}
		return inputParametersModified;
	}	
	// END EXTRA CODE
}
