// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpserver.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.server.McpServerFeatures;
import io.modelcontextprotocol.server.McpSyncServer;
import io.modelcontextprotocol.spec.McpSchema;
import mcpserver.impl.McpServerRegistry;
import mcpserver.impl.MxLogger;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Registers a tool the with MCP Server that gets exposed to MCP clients. If the model chooses to call the tool, the selected microflow gets executed.
 * 
 * Currently, the current User is not in scope of the tool microflow.
 */
public class AddTool extends UserAction<IMendixObject>
{
	private final java.lang.String Name;
	private final java.lang.String Description;
	private final java.lang.String Schema;
	private final java.lang.String ExecutingMicroflow;
	/** @deprecated use McpServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __McpServer;
	private final mcpserver.proxies.McpServer McpServer;

	public AddTool(
		IContext context,
		java.lang.String _name,
		java.lang.String _description,
		java.lang.String _schema,
		java.lang.String _executingMicroflow,
		IMendixObject _mcpServer
	)
	{
		super(context);
		this.Name = _name;
		this.Description = _description;
		this.Schema = _schema;
		this.ExecutingMicroflow = _executingMicroflow;
		this.__McpServer = _mcpServer;
		this.McpServer = _mcpServer == null ? null : mcpserver.proxies.McpServer.initialize(getContext(), _mcpServer);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Create NPE for the tool
		mcpserver.proxies.Tool toolNpe = new mcpserver.proxies.Tool(getContext());
		toolNpe.setName(Name);
		toolNpe.setDescription(Description);
		toolNpe.setSchema(Schema);
		toolNpe.setMicroflowName(ExecutingMicroflow);
		toolNpe.setTool_McpServer(McpServer);

		// Add the tool to the server
		McpSyncServer server = McpServerRegistry.getServerInstance(this.McpServer.getMendixObject().getId().toLong());

		McpServerFeatures.SyncToolSpecification tool = new McpServerFeatures.SyncToolSpecification(
				new McpSchema.Tool(Name, Description,Schema),
				(exchange, arguments) -> {
					// some request logging
					String threadName = Thread.currentThread().getName();
					long start = System.currentTimeMillis();
					LOGGER.trace(threadName + ": Start processing tool call " + Name + ", MF: " + ExecutingMicroflow);

					IContext ctx = getContextFromSession();

					Map<String, Object> args = new HashMap<>(arguments);
					args.put("Tool", toolNpe);

					try {
						IMendixObject mxExecResult = Core.microflowCall(ExecutingMicroflow).withParams(args).execute(ctx);
						mcpserver.proxies.TextContent mxTextContent = mcpserver.proxies.TextContent.initialize(ctx, mxExecResult);

						McpSchema.TextContent mcpTextContent = new McpSchema.TextContent(mxTextContent.getContent());
						return new McpSchema.CallToolResult(List.of(mcpTextContent), false);
					} finally {
						LOGGER.trace(threadName + ": End processing tool call '" + Name + ". Duration: " + (System.currentTimeMillis() - start) + "ms.");
					}

				}
		);
		server.addTool(tool);

		return toolNpe.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddTool";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new mcpserver.impl.MxLogger(AddTool.class);
	/**
	 * Returns a context object for the tool microflow. Currently, a system session is returned.
	 * @return Context object
	 */
	private IContext getContextFromSession() {
		return Core.createSystemContext();
	}
	// END EXTRA CODE
}
