// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mcpserver.actions;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.modelcontextprotocol.server.McpServer;
import io.modelcontextprotocol.server.McpSyncServer;
import io.modelcontextprotocol.spec.McpSchema;
import mcpserver.impl.McpServerRegistry;
import mcpserver.impl.McpServerRequestHandler;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Create and start an MCP Server. The input follows the MCP specifications.
 * 
 * Note that no authentication method is applied if no authentication microflow as added, thus making the MCP server usable for anyone. It is recommended to add an authentication microflow if the Mendix application is reachable outside of your local environment.
 */
public class CreateMCPServer extends UserAction<IMendixObject>
{
	private final java.lang.String Path;
	private final java.lang.String Name;
	private final java.lang.String Version;
	private final java.lang.String AuthenticationMicroflow;

	public CreateMCPServer(
		IContext context,
		java.lang.String _path,
		java.lang.String _name,
		java.lang.String _version,
		java.lang.String _authenticationMicroflow
	)
	{
		super(context);
		this.Path = _path;
		this.Name = _name;
		this.Version = _version;
		this.AuthenticationMicroflow = _authenticationMicroflow;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Create McpServer NPE
		mcpserver.proxies.McpServer mcpServer = new mcpserver.proxies.McpServer(getContext());
		mcpServer.setName(Name);
		mcpServer.setVersion(Version);
		mcpServer.setAuthenticationMicroflow(AuthenticationMicroflow);

		// Create request handler and McpServer object
		McpServerRequestHandler mcpRequestHandler = new McpServerRequestHandler(
				new ObjectMapper(), mcpServer, getContext() ,  "/" + Path + "/messages", "/" + Path + "/sse");
				//TBD: should we remove messages and SSE path from input?
				//new ObjectMapper(), "/" + Path + "/messages", "/" + Path + "/sse");
		Core.addRequestHandler(Path + "/", mcpRequestHandler);

		McpSyncServer server = McpServer.sync(mcpRequestHandler)
				.serverInfo(Name, Version)
				.capabilities(
						McpSchema.ServerCapabilities.builder()
								.tools(true)
								.prompts(true)
								.build()
				)
				.build();

		// Associate NPE and server object for future update
		Long serverId = mcpServer.getMendixObject().getId().toLong();
		McpServerRegistry.putServerInstance(serverId, server);

		return mcpServer.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateMCPServer";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
