// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import genaicommons.impl.DeployedModelImpl;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.ENUM_ModelType;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class DeployedModel_SetMicroflow extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __DeployedModel;
	private genaicommons.proxies.DeployedModel DeployedModel;
	private java.lang.String Microflow;

	public DeployedModel_SetMicroflow(IContext context, IMendixObject DeployedModel, java.lang.String Microflow)
	{
		super(context);
		this.__DeployedModel = DeployedModel;
		this.Microflow = Microflow;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.DeployedModel = this.__DeployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), __DeployedModel);

		// BEGIN USER CODE
		try {
			requireNonNull(Microflow, "Microflow is required.");
			requireNonNull(DeployedModel, "DeployedModel is required.");
			if (DeployedModel.getModelType() != null && DeployedModel.getModelType() == ENUM_ModelType.TextGeneration)
				DeployedModelImpl.validateChatCompletionsMicroflow(Microflow);
			
			DeployedModel.setMicroflow(Microflow);
			
			return null;
			
		} catch (Exception e) {
			LOGGER.error(e);
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeployedModel_SetMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(DeployedModel_SetMicroflow.class);

	// END EXTRA CODE
}
