// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import genaicommons.impl.DeployedModelImpl;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.DeployedModel;
import genaicommons.proxies.ENUM_ModelType;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Creates a DployedModel objects (or a specialization of such if the specialization is passed) and sets all passed attributes. The DeployedModel entity replaces the Connection entity and is a required input parameter for all chat completion operations. It contains the name of the microflow to be executed for the specified model and other information relevant to connect to a model.
 */
public class DeployedModel_Create extends CustomJavaAction<IMendixObject>
{
	private java.lang.String DisplayName;
	private java.lang.String Architecture;
	private java.lang.String Model;
	private genaicommons.proxies.ENUM_ModelType ModelType;
	private java.lang.String Microflow;
	private java.lang.String DeployedModelSpecialization;

	public DeployedModel_Create(IContext context, java.lang.String DisplayName, java.lang.String Architecture, java.lang.String Model, java.lang.String ModelType, java.lang.String Microflow, java.lang.String DeployedModelSpecialization)
	{
		super(context);
		this.DisplayName = DisplayName;
		this.Architecture = Architecture;
		this.Model = Model;
		this.ModelType = ModelType == null ? null : genaicommons.proxies.ENUM_ModelType.valueOf(ModelType);
		this.Microflow = Microflow;
		this.DeployedModelSpecialization = DeployedModelSpecialization;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			if (ModelType != null && ModelType == ENUM_ModelType.TextGeneration)
				DeployedModelImpl.validateChatCompletionsMicroflow(Microflow);
			
			return createAndSetDeployedModel().getMendixObject();
			
		} catch (Exception e) {
			LOGGER.error(e);
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeployedModel_Create";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(DeployedModel_Create.class);
	
	private DeployedModel createAndSetDeployedModel() {
		// Create an instance of the specialized ProviderConfig object
		IMendixObject deployedModelSpecialization = createDeployedModel();
		validateDeployedModelSpecialization(deployedModelSpecialization);

		// Use the specialized proxy class to wrap the generic IMendixObject to set attributes
		DeployedModel deployedModel = DeployedModel.initialize(getContext(), deployedModelSpecialization);
		deployedModel.setArchitecture(Architecture);
		deployedModel.setMicroflow(Microflow);
		deployedModel.setDisplayName(DisplayName);
		deployedModel.setModel(Model);
		deployedModel.setModelType(ModelType);
		return deployedModel;
	}

	private IMendixObject createDeployedModel() {
		if (!DeployedModelSpecialization.isBlank()) {
			IMendixObject deployedModelSpecialization = Core.instantiate(getContext(), DeployedModelSpecialization);
			return deployedModelSpecialization;
		} else { // if no object is passed, then a GenAICOmmons.DeployedModel object is created
			DeployedModel deployedModel = new DeployedModel(getContext());
			return (IMendixObject) deployedModel;
		}
	}
	
	private void validateDeployedModelSpecialization(IMendixObject deployedModelSpecialization) {
		if (!deployedModelSpecialization.isInstanceOf(DeployedModel.entityName)){
			throw new IllegalArgumentException(DeployedModel.entityName + " or a specialization of such is required.");
		}
	}
	// END EXTRA CODE
}
