// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import genaicommons.impl.FunctionImpl;
import genaicommons.impl.KnowledgeBaseRetrievalImpl;
import genaicommons.impl.MxLogger;
import genaicommons.impl.ToolCollectionImpl;
import genaicommons.proxies.KnowledgeBaseRetrieval;
import genaicommons.proxies.ToolCollection;

public class Request_AddKnowledgeBaseRetrieval extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Request;
	private genaicommons.proxies.Request Request;
	private IMendixObject __Connection;
	private genaicommons.proxies.Connection Connection;
	private java.lang.String ToolName;
	private java.lang.String ToolDescription;
	private java.lang.String FunctionMicroflow;
	private IMendixObject __MetadataCollection;
	private genaicommons.proxies.MetadataCollection MetadataCollection;
	private java.math.BigDecimal MinimumSimilarity;
	private java.lang.Long MaxNumberOfResults;

	public Request_AddKnowledgeBaseRetrieval(IContext context, IMendixObject Request, IMendixObject Connection, java.lang.String ToolName, java.lang.String ToolDescription, java.lang.String FunctionMicroflow, IMendixObject MetadataCollection, java.math.BigDecimal MinimumSimilarity, java.lang.Long MaxNumberOfResults)
	{
		super(context);
		this.__Request = Request;
		this.__Connection = Connection;
		this.ToolName = ToolName;
		this.ToolDescription = ToolDescription;
		this.FunctionMicroflow = FunctionMicroflow;
		this.__MetadataCollection = MetadataCollection;
		this.MinimumSimilarity = MinimumSimilarity;
		this.MaxNumberOfResults = MaxNumberOfResults;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Request = this.__Request == null ? null : genaicommons.proxies.Request.initialize(getContext(), __Request);

		this.Connection = this.__Connection == null ? null : genaicommons.proxies.Connection.initialize(getContext(), __Connection);

		this.MetadataCollection = this.__MetadataCollection == null ? null : genaicommons.proxies.MetadataCollection.initialize(getContext(), __MetadataCollection);

		// BEGIN USER CODE
		try{
			requireNonNull(Request, "Request is required.");
			KnowledgeBaseRetrievalImpl.validateInput(FunctionMicroflow, ToolName);
			
			ToolCollection toolCollection = ToolCollectionImpl.getOrCreateToolCollection(getContext(), Request);
			
			IMendixObject knowledgeBaseRetrievalMxObject = KnowledgeBaseRetrievalImpl.createKnowledgeBaseRetrieval(getContext(), FunctionMicroflow, ToolName, toolCollection, Connection).getMendixObject();
			KnowledgeBaseRetrieval knowledgeBaseRetrieval = KnowledgeBaseRetrieval.load(getContext(), knowledgeBaseRetrievalMxObject.getId());
			KnowledgeBaseRetrievalImpl.addOptionalParameters(knowledgeBaseRetrieval, ToolDescription, MetadataCollection, MinimumSimilarity, MaxNumberOfResults);
			
			return knowledgeBaseRetrievalMxObject;
			
		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_AddKnowledgeBaseRetrieval";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new genaicommons.impl.MxLogger(Request_AddKnowledgeBaseRetrieval.class);
	// END EXTRA CODE
}
