// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import genaicommons.proxies.ENUM_ModelModality;
import genaicommons.proxies.Response;
import genaicommons.proxies.microflows.Microflows;
import genaicommons.impl.DeployedModelImpl;
import genaicommons.impl.MxLogger;

/**
 * This Java Action should only be used by connector developers. It executes the Request by calling an LLM via the passed ModelCallMicroflow.
 * 
 * If the model returns a tool call response, the function microflows are automatically executed and added as messages with MessageRole "tool" to the request. Afterwards the ModelCallMicroflow is executed again. This process is repeated until the model returns a final assistant response.
 * 
 * Additionally, this java action takes care of storing token usage metrics by calling the Usage_Create_TextAndFiles microflow, if the StoreUsageMetrics constant was set to true by the developer.
 */
public class Request_ExecuteFromConnector extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Request;
	private genaicommons.proxies.Request Request;
	private IMendixObject __DeployedModel;
	private genaicommons.proxies.DeployedModel DeployedModel;
	private java.lang.String CallModelMicroflow;

	public Request_ExecuteFromConnector(IContext context, IMendixObject Request, IMendixObject DeployedModel, java.lang.String CallModelMicroflow)
	{
		super(context);
		this.__Request = Request;
		this.__DeployedModel = DeployedModel;
		this.CallModelMicroflow = CallModelMicroflow;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Request = this.__Request == null ? null : genaicommons.proxies.Request.initialize(getContext(), __Request);

		this.DeployedModel = this.__DeployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), __DeployedModel);

		// BEGIN USER CODE
		try {
			validate();
			startTime = System.currentTimeMillis();
			return processRequest().getMendixObject();
		} catch (Exception e) {
			LOGGER.error(e);
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ExecuteFromConnector";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Request_ExecuteFromConnector.class);
	
	private int totalTokens = 0;
	private int requestTokens = 0;
	private int responseTokens = 0;
	private long startTime;
	
	//Recursive response processing until there is no ToolCall available
	private Response processRequest() throws CoreException {
		IMendixObject responseMendixObject = Core.microflowCall(CallModelMicroflow).withParam("DeployedModel", DeployedModel.getMendixObject()).withParam("Request", Request.getMendixObject()).execute(this.getContext());
		if(responseMendixObject == null) {
			throw new NullPointerException("Microflow " + CallModelMicroflow  + " returned null.");
		}
		Response response = genaicommons.proxies.Response.load(getContext(), responseMendixObject.getId());
		
		responseUpdateTokenCount(response);
		
		boolean toolCallsProcessed = Microflows.response_ProcessToolCalls(getContext(), response, Request);
		
		//Recursion if tool calls are available
		if (toolCallsProcessed) {
			return processRequest();
		}
		
		responseStoreDurationAndUsage(response);
		return response;
	}

	private void responseStoreDurationAndUsage(Response response) {
		response.setDurationMilliseconds((int) Math.ceil(System.currentTimeMillis() - startTime));
		if (genaicommons.proxies.constants.Constants.getStoreUsageMetrics()) {
			Microflows.usage_Create_TextAndFiles(getContext(), response, DeployedModel);
		}
	}
	
	private void responseUpdateTokenCount(Response response) {
		requestTokens += response.getRequestTokens();
		responseTokens += response.getResponseTokens();
		totalTokens += response.getTotalTokens();
		response.setRequestTokens(requestTokens);
		response.setResponseTokens(responseTokens);
		response.setTotalTokens(totalTokens);
	}
	
	private void validate() {
		requireNonNull(Request, "Request is required.");
		
		if (CallModelMicroflow == null || CallModelMicroflow.isBlank()) {
			throw new IllegalArgumentException("CallModelMicroflow is required.");
		}
		
		DeployedModelImpl.validate(DeployedModel, ENUM_ModelModality.TextGeneration);
	}
	// END EXTRA CODE
}
