// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import genaicommons.impl.DeployedModelImpl;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.ENUM_ModelType;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Request_ChatCompletionsWithHistory extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Request;
	private genaicommons.proxies.Request Request;
	private IMendixObject __DeployedModel;
	private genaicommons.proxies.DeployedModel DeployedModel;

	public Request_ChatCompletionsWithHistory(IContext context, IMendixObject Request, IMendixObject DeployedModel)
	{
		super(context);
		this.__Request = Request;
		this.__DeployedModel = DeployedModel;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Request = this.__Request == null ? null : genaicommons.proxies.Request.initialize(getContext(), __Request);

		this.DeployedModel = this.__DeployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), __DeployedModel);

		// BEGIN USER CODE
		try {
			validate();
			return Core.microflowCall(DeployedModel.getMicroflow()).withParam("DeployedModel", DeployedModel.getMendixObject()).withParam("Request", Request.getMendixObject()).execute(this.getContext());

		} catch (Exception e) {
			LOGGER.error(e);
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ChatCompletionsWithHistory";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(Request_ChatCompletionsWithHistory.class);
	
	private void validate() {
		requireNonNull(Request, "Request is required.");
		requireNonNull(DeployedModel, "DeployedModel is required.");
		if (DeployedModel.getModelType() == null || DeployedModel.getModelType() != ENUM_ModelType.TextGeneration) {
			throw new IllegalArgumentException("The DeployedModel needs to have the Text generation ModelType.");
		}
		DeployedModelImpl.validateChatCompletionsMicroflow(DeployedModel.getMicroflow());
	}
	
	// END EXTRA CODE
}
