// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import genaicommons.impl.MxLogger;
import genaicommons.impl.ToolCollectionImpl;
import genaicommons.proxies.Computer;
import genaicommons.proxies.Tool;
import genaicommons.proxies.ToolCollection;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Adds a new Function to a Request.
 * Parameters: 
 * - Request: The request to add the function to.
 * - ToolName: The name of the tool to call.
 * - FunctionMicroflow: The microflow that is called within this function.
 * - ToolDescription (optional): A description of what the function does, used by the model to choose when and how to call the function.
 * 
 * The action returns empty if adding the function was not successful (errors are logged).
 */
public class Request_AddComputer extends UserAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	private final java.lang.String ToolName;
	private final java.lang.String ComputerUseMicroflow;

	public Request_AddComputer(
		IContext context,
		IMendixObject _request,
		java.lang.String _toolName,
		java.lang.String _computerUseMicroflow
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.ToolName = _toolName;
		this.ComputerUseMicroflow = _computerUseMicroflow;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try{
			requireNonNull(Request, "Request is required.");
			
			ToolCollection toolCollection = ToolCollectionImpl.getOrCreateToolCollection(getContext(), Request);
			
			return createComputer(getContext(), ComputerUseMicroflow, ToolName, toolCollection).getMendixObject();

		} catch (Exception e) {
			LOGGER.error(e);
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_AddComputer";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new genaicommons.impl.MxLogger(Request_AddComputer.class);
	
	public static Computer createComputer(IContext context, String computerUseMicroflow, String toolName, ToolCollection toolCollection) throws CoreException {
		Computer computer = new Computer(context);
		computer.setMicroflow(computerUseMicroflow);
		computer.setName(toolName);	
		List<Tool> ToolList = toolCollection.getToolCollection_Tool();
		ToolList.add(computer);
		toolCollection.setToolCollection_Tool(ToolList); 
		return computer;
	}
	// END EXTRA CODE
}
