// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.Date;
import java.util.UUID;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import genaicommons.proxies.ENUM_ModelModality;
import genaicommons.proxies.Message;
import genaicommons.proxies.ModelSpan;
import genaicommons.proxies.Response;
import genaicommons.proxies.Trace;
import genaicommons.proxies.Usage;
import genaicommons.proxies.microflows.Microflows;
import genaicommons.impl.DeployedModelImpl;
import genaicommons.impl.MxLogger;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This Java Action should only be used by connector developers. It executes the Request by calling an LLM via the passed ModelCallMicroflow.
 * 
 * If the model returns a tool call response, the function microflows are automatically executed and added as messages with MessageRole "tool" to the request. Afterwards the ModelCallMicroflow is executed again. This process is repeated until the model returns a final assistant response.
 * 
 * Additionally, this java action takes care of storing token usage metrics by calling the Usage_Create_TextAndFiles microflow, if the StoreUsageMetrics constant was set to true by the developer.
 */
public class Request_ExecuteFromConnector extends UserAction<IMendixObject>
{
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use DeployedModel.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeployedModel;
	private final genaicommons.proxies.DeployedModel DeployedModel;
	private final java.lang.String CallModelMicroflow;

	public Request_ExecuteFromConnector(
		IContext context,
		IMendixObject _request,
		IMendixObject _deployedModel,
		java.lang.String _callModelMicroflow
	)
	{
		super(context);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__DeployedModel = _deployedModel;
		this.DeployedModel = _deployedModel == null ? null : genaicommons.proxies.DeployedModel.initialize(getContext(), _deployedModel);
		this.CallModelMicroflow = _callModelMicroflow;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			validate();
			startTime = System.currentTimeMillis();
			Response response = processRequest();
			if(response != null) {
				return response.getMendixObject();
			} else {
				return null;
			}
		} catch (Exception e) {
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Request_ExecuteFromConnector";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new genaicommons.impl.MxLogger(Request_ExecuteFromConnector.class);
	private int totalTokens = 0;
	private int requestTokens = 0;
	private int responseTokens = 0;
	private long startTime;
	
	//Response processing with tool approval workflow
	//Returns early if there are PENDING tool calls that need approval
	private Response processRequest() throws CoreException {
		ModelSpan modelSpan = createModelSpan();
		try {
			Response response = null;
			Message assistantMessage = null;
			
			// Check if we're resuming from an approval flow (user approved/declined tool calls)
			// In this case, there's an AssistantMessage with ToolCalls that have Approved/Declined status
			Message existingAssistantMessage = getLastAssistantMessageWithToolCalls();
			if (existingAssistantMessage != null && hasDecidedToolCalls(existingAssistantMessage)) {
				// Resume: process the decided tool calls, then call model with results
				boolean toolCallsProcessed = Microflows.message_ProcessToolCalls_IfAvailable(getContext(), existingAssistantMessage, Request, modelSpan);
				
				// Check if there are still PENDING tool calls (partial approval scenario)
				if (hasPendingToolCalls(existingAssistantMessage)) {
					return null; // Wait for more decisions
				}
				
				if (toolCallsProcessed) {
					// Tool calls were processed, now call model with results
					return processRequest();
				}
				// Nothing processed, something went wrong
				return null;
			}
			
			// Normal flow: call the model
			debugLogRequestMessages("Before calling model");
			IMendixObject responseMendixObject = Core.microflowCall(CallModelMicroflow).withParam("DeployedModel", DeployedModel.getMendixObject()).withParam("Request", Request.getMendixObject()).execute(this.getContext());
			if(responseMendixObject == null) {
				LOGGER.debug("Microflow " + CallModelMicroflow  + " returned null.");
				updateModelSpanOnError(modelSpan);
				return null;
			}
			response = genaicommons.proxies.Response.load(getContext(), responseMendixObject.getId());
			assistantMessage = response.getResponse_Message();
			response.setResponseText(assistantMessage.getContent());
			updateModelSpan(modelSpan, response);
			responseUpdateTokenCount(response);
			
			// Process tool calls: 
			// - Auto-hidden: execute, status = ExecutedHidden
			// - Auto-visible: execute, status = Executed
			// - Needs approval: status = Pending (Tool messages created but not executed)
			boolean toolCallsProcessed = Microflows.message_ProcessToolCalls_IfAvailable(getContext(), assistantMessage, Request, modelSpan);
			
			// Check if there are PENDING tool calls needing user approval
			if (hasPendingToolCalls(assistantMessage)) {
				// Early return for approval
				responsePostProcessing(response);
				return response;
			}
			
			// Check if there are visible executed tool calls that need UI update before continuing
			if (hasExecutedVisibleToolCalls(assistantMessage)) {
				// Early return for UI update - tool was executed but user should see the result
				// UI will resume after showing the tool call results
				responsePostProcessing(response);
				return response;
			}
			
			// Recursion if tool calls were processed (need to call model again with results)
			if (toolCallsProcessed) {
				return processRequest();
			}
			
			// Final response - no more tool calls
			responsePostProcessing(response);
			return response;
		}

	catch (Exception e) {
		//Update modelSpan in case of error
		updateModelSpanOnError(modelSpan);
		LOGGER.debug("Exception in Java Code, failed to process Request " + e.getMessage());
		return null;
		}
	}
	
	private void updateModelSpanOnError(ModelSpan modelSpan) {
		if (modelSpan != null) {
			modelSpan.setEndTime(new Date(System.currentTimeMillis()));
			modelSpan.setDurationMilliseconds((int) (modelSpan.getEndTime().getTime() -  modelSpan.getStartTime().getTime()));
		}
	}

	/**
	 * Sets duration of final response, sets response Id; creates Usage and updates Trace.
	 * @param response
	 * @throws CoreException
	 */
	private void responsePostProcessing(Response response) throws CoreException {
		response.setDurationMilliseconds((int) Math.ceil(System.currentTimeMillis() - startTime));
		if(response.get_ID() == null || response.get_ID().isBlank()) {
			if(Request.get_ID() != null && !Request.get_ID().isBlank()) {
				response.set_ID(Request.get_ID());
				
			}else {
				response.set_ID(UUID.randomUUID().toString());
			}
		}
		
		Trace trace = Request.getRequest_Trace();
		
		//trace == null if the constant was empty
		if (trace != null || genaicommons.proxies.constants.Constants.getStoreUsageMetrics()) {
			Usage usage = Microflows.usage_Create_TextAndFiles(getContext(), response, DeployedModel);

			if(trace != null) {
				trace.setTrace_Usage(usage);
				trace.setOutput(response.getResponseText());
				trace.setSystemPrompt(Request.getSystemPrompt());
			}
		}
	}
	
	//Updates modelspan after the response was created
	private void updateModelSpan(ModelSpan modelSpan, Response response) throws CoreException {
		if(modelSpan != null) {
			//modelSpan.setSpan_Trace(trace);
			modelSpan.setIsError(false);
			modelSpan.setInputTokens(response.getRequestTokens());
			modelSpan.setOutputTokens(response.getResponseTokens());
			modelSpan.setOutput(response.getResponseText());
			modelSpan.setEndTime(new Date(System.currentTimeMillis()));
			modelSpan.setDurationMilliseconds((int) (modelSpan.getEndTime().getTime() -  modelSpan.getStartTime().getTime()));
		}
	}
	
	//Creates ModelSpan with known startTime
	private ModelSpan createModelSpan() throws CoreException {
		Trace trace = Request.getRequest_Trace();
		if(trace != null) {
			ModelSpan modelSpan = new ModelSpan(getContext());
			modelSpan.setInput(Microflows.trace_GetModelSpanInput(getContext(),trace)); 
			modelSpan.setSpanId(UUID.randomUUID().toString());
			modelSpan.setSpan_Trace(trace);
			modelSpan.setIsError(true);
			modelSpan.set_DeploymentIdentifier(DeployedModel.getArchitecture() + ' ' + DeployedModel.getDisplayName());
			modelSpan.setStartTime(new Date(System.currentTimeMillis()));
			return modelSpan;
			
		} else {
			return null;
		}
	}
	
	private void responseUpdateTokenCount(Response response) {
		requestTokens += response.getRequestTokens() != null ? response.getRequestTokens() : 0;
		responseTokens += response.getResponseTokens() != null ? response.getResponseTokens() : 0;
		totalTokens += response.getTotalTokens() != null ? response.getTotalTokens() : 0;
		
		response.setRequestTokens(requestTokens);
		response.setResponseTokens(responseTokens);
		response.setTotalTokens(totalTokens);
	}
	
	/**
	 * Gets the last assistant message from the Request that contains tool calls.
	 * Used to check if there are decided tool calls waiting to be processed.
	 * @return the last assistant message with tool calls, or null if none exists
	 * @throws CoreException if retrieval fails
	 */
	private Message getLastAssistantMessageWithToolCalls() throws CoreException {
		java.util.List<Message> messages = Request.getRequest_Message();
		if (messages == null || messages.isEmpty()) {
			return null;
		}
		
		// Iterate in reverse to find the last assistant message with tool calls
		for (int i = messages.size() - 1; i >= 0; i--) {
			Message msg = messages.get(i);
			if (msg.getRole() == genaicommons.proxies.ENUM_MessageRole.assistant) {
				java.util.List<genaicommons.proxies.ToolCall> toolCalls = msg.getMessage_ToolCall();
				if (toolCalls != null && !toolCalls.isEmpty()) {
					return msg;
				}
			}
		}
		return null;
	}
	
	/**
	 * Checks if the assistant message contains tool calls with APPROVED or DECLINED status.
	 * These are tool calls that the user has decided on but haven't been processed yet.
	 * @param assistantMessage the assistant message containing tool calls
	 * @return true if there are decided (approved or declined) tool calls waiting to be processed
	 * @throws CoreException if retrieval fails
	 */
	private boolean hasDecidedToolCalls(Message assistantMessage) throws CoreException {
		if (assistantMessage == null) {
			return false;
		}
		java.util.List<genaicommons.proxies.ToolCall> toolCalls = assistantMessage.getMessage_ToolCall();
		if (toolCalls == null || toolCalls.isEmpty()) {
			return false;
		}
		return toolCalls.stream()
			.anyMatch(tc -> tc.getStatus() == genaicommons.proxies.ENUM_ToolCallStatus.Approved
					   || tc.getStatus() == genaicommons.proxies.ENUM_ToolCallStatus.Declined);
	}

	/**
	 * Checks if the assistant message contains any tool calls with PENDING status.
	 * Returns true if approval is needed before proceeding.
	 * @param assistantMessage the assistant message containing potential tool calls
	 * @return true if there are pending tool calls requiring approval
	 * @throws CoreException if retrieval fails
	 */
	private boolean hasPendingToolCalls(Message assistantMessage) throws CoreException {
		if (assistantMessage == null) {
			return false;
		}
		java.util.List<genaicommons.proxies.ToolCall> toolCalls = assistantMessage.getMessage_ToolCall();
		if (toolCalls == null || toolCalls.isEmpty()) {
			return false;
		}
		return toolCalls.stream()
			.anyMatch(tc -> tc.getStatus() != null && 
					   tc.getStatus() == genaicommons.proxies.ENUM_ToolCallStatus.Pending);
	}
	
	/**
	 * Checks if the assistant message contains tool calls with EXECUTED (visible) status.
	 * These are auto-approved tools that were executed but need to be shown in UI before continuing.
	 * @param assistantMessage the assistant message containing tool calls
	 * @return true if there are executed visible tool calls requiring UI update
	 * @throws CoreException if retrieval fails
	 */
	private boolean hasExecutedVisibleToolCalls(Message assistantMessage) throws CoreException {
		if (assistantMessage == null) {
			return false;
		}
		java.util.List<genaicommons.proxies.ToolCall> toolCalls = assistantMessage.getMessage_ToolCall();
		if (toolCalls == null || toolCalls.isEmpty()) {
			return false;
		}
		return toolCalls.stream()
			.anyMatch(tc -> tc.getStatus() == genaicommons.proxies.ENUM_ToolCallStatus.Executed);
	}
	
	/**
	 * Debug helper to log all messages currently in the Request.
	 */
	private void debugLogRequestMessages(String context) throws CoreException {
		java.util.List<Message> messages = Request.getRequest_Message();
		LOGGER.info("=== " + context + " === Request has " + (messages != null ? messages.size() : 0) + " messages:");
		if (messages != null) {
			for (int i = 0; i < messages.size(); i++) {
				Message msg = messages.get(i);
				String role = msg.getRole() != null ? msg.getRole().toString() : "null";
				String content = msg.getContent();
				String preview = content != null ? content.substring(0, Math.min(50, content.length())) : "null";
				
				// Check for tool calls on assistant messages
				String toolCallInfo = "";
				if (msg.getRole() == genaicommons.proxies.ENUM_MessageRole.assistant) {
					java.util.List<genaicommons.proxies.ToolCall> toolCalls = msg.getMessage_ToolCall();
					if (toolCalls != null && !toolCalls.isEmpty()) {
						toolCallInfo = " [" + toolCalls.size() + " tool calls:";
						for (genaicommons.proxies.ToolCall tc : toolCalls) {
							toolCallInfo += " {id=" + tc.getToolCallId() + ", name=" + tc.getName() + ", args=" + tc.getInput() + "}";
						}
						toolCallInfo += "]";
					}
				}
				
				// Check for tool call ID on tool messages
				String toolCallId = "";
				if (msg.getRole() == genaicommons.proxies.ENUM_MessageRole.tool) {
					String tcId = msg.getToolCallId();
					if (tcId != null && !tcId.isEmpty()) {
						toolCallId = " [responds to: " + tcId + "]";
					}
				}
				
				LOGGER.info("  [" + i + "] " + role + toolCallInfo + toolCallId + ": " + preview);
			}
		}
	}
	
	/**
	 * Removes an empty assistant message from the Request.
	 * This is needed because connectors fail when an empty assistant message is present.
	 * The Tool messages (with results) are kept - only the empty assistant message is removed.
	 * @param assistantMessage the assistant message to remove
	 * @throws CoreException if removal fails
	 */
	private void removeEmptyAssistantMessage(Message assistantMessage) throws CoreException {
		if (assistantMessage == null) {
			return;
		}
		// Only remove if content is empty/null
		String content = assistantMessage.getContent();
		if (content == null || content.isBlank()) {
			Core.delete(getContext(), assistantMessage.getMendixObject());
			LOGGER.debug("Removed empty assistant message from Request before calling model.");
		}
	}
	
	private void validate() {
		requireNonNull(Request, "Request is required.");
		
		if (CallModelMicroflow == null || CallModelMicroflow.isBlank()) {
			throw new IllegalArgumentException("CallModelMicroflow is required.");
		}
		
		DeployedModelImpl.validate(DeployedModel, ENUM_ModelModality.Text);
	}
	// END EXTRA CODE
}
