// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import genaicommons.impl.MxLogger;
import genaicommons.proxies.Argument;
import genaicommons.proxies.KnowledgeBaseSpan;
import genaicommons.proxies.MCPSpan;
import genaicommons.proxies.ModelSpan;
import genaicommons.proxies.ToolSpan;
import genaicommons.proxies.Trace;
import genaicommons.proxies.microflows.Microflows;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;

public class Tool_ExecuteMicroflow extends UserAction<java.lang.String>
{
	/** @deprecated use Tool.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Tool;
	private final genaicommons.proxies.Tool Tool;
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final genaicommons.proxies.Request Request;
	/** @deprecated use ToolCall.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ToolCall;
	private final genaicommons.proxies.ToolCall ToolCall;

	public Tool_ExecuteMicroflow(
		IContext context,
		IMendixObject _tool,
		IMendixObject _request,
		IMendixObject _toolCall
	)
	{
		super(context);
		this.__Tool = _tool;
		this.Tool = _tool == null ? null : genaicommons.proxies.Tool.initialize(getContext(), _tool);
		this.__Request = _request;
		this.Request = _request == null ? null : genaicommons.proxies.Request.initialize(getContext(), _request);
		this.__ToolCall = _toolCall;
		this.ToolCall = _toolCall == null ? null : genaicommons.proxies.ToolCall.initialize(getContext(), _toolCall);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Tool, "Tool is required.");
			requireNonNull(Tool.getMicroflow(), "Tool has no Microflow.");
			startTime = System.currentTimeMillis();
			return callTool();
		
		} catch (Exception e) {
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Tool_ExecuteMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new genaicommons.impl.MxLogger(Tool_ExecuteMicroflow.class);
	private static final ObjectMapper MAPPER = new ObjectMapper();
	
	private long startTime;
	
	/**
	 * If the Tool is of the generalization type, only Tool and Request are added to the microflow
	 * Otherwise the parameters from the microflow are mapped
	 * @throws Exception
	 */
	private String callTool() throws Exception {
		if(Tool.getClass().equals(genaicommons.proxies.Tool.class)) {
			Map<String, Object> parametersAndValues = new java.util.HashMap<>();
			parametersAndValues.put("Tool",  Tool.getMendixObject());
			parametersAndValues.put("Request",  Request.getMendixObject());
			return executeAndLogToolMicroflow(parametersAndValues);
			
		}
		else {
			return executeToolMicroflow();
		}
	}

	private String executeToolMicroflow() throws Exception {
		
		Map<String, Object> parametersAndValues = new java.util.HashMap<>();
		//Iterate over input params
		Map<String, IDataType> parametersAndTypes = Core.getInputParameters(Tool.getMicroflow());
		
		// Get argument list, fall back to parsing Input JSON if empty
		List<Argument> argumentList = ToolCall.getToolCall_Argument();
		if (argumentList == null || argumentList.isEmpty()) {
			argumentList = parseArgumentsFromInput();
		}
		
		for(Map.Entry<String, IDataType> entry : parametersAndTypes.entrySet()) {
			IDataType value = entry.getValue();
			String key = entry.getKey();
			//find Argument.Value in ArgumentList
			final List<Argument> finalArgumentList = argumentList;
			String argumentValue = finalArgumentList.stream()
				    .filter(arg -> key.equals(arg.getKey()))
				    .map(Argument::getValue)
				    .findFirst()
				    .orElse(null);
			
			//If there is no argumentValue, it is either a Mendix Object or nothing was passed
			if (argumentValue == null && isMetaObjectSubClass(value,genaicommons.proxies.Tool.getType())){
				parametersAndValues.put(key,  Tool.getMendixObject());
				continue;
				
			} else if (argumentValue == null && isMetaObjectSubClass(value, genaicommons.proxies.Request.getType())){
				parametersAndValues.put(key, Request.getMendixObject());
				continue;
				
			} else if (argumentValue == null) {
				parametersAndValues.put(key, null);
				continue;
			}
						
			// Convert input into type of tool microflow's parameter type and add to list
			if (IDataType.DataTypeEnum.Boolean.equals(value.getType())) {
				parametersAndValues.put(key, Boolean.parseBoolean(argumentValue));
				
			} else if (IDataType.DataTypeEnum.Integer.equals(value.getType()) || IDataType.DataTypeEnum.Long.equals(value.getType()) ) {
					parametersAndValues.put(key, Long.parseLong(argumentValue));
					
			} else if (IDataType.DataTypeEnum.Datetime.equals(value.getType())) {
				Date date = new Date(Long.parseLong(argumentValue) *1000L); //Convert UNIX timestamp to DateTime
				parametersAndValues.put(key, date);
				
			} else if (IDataType.DataTypeEnum.Decimal.equals(value.getType())) {
				parametersAndValues.put(key, Float.parseFloat(argumentValue));
				
			} else if(IDataType.DataTypeEnum.String.equals(value.getType())){
				parametersAndValues.put(key, argumentValue);	
				
			} else if(IDataType.DataTypeEnum.Enumeration.equals(value.getType())){
				parametersAndValues.put(key, argumentValue);	
				
			}
		}		
		return executeAndLogToolMicroflow(parametersAndValues);
	}
	
	/**
	 * Checks if the input object of a parameter (as IDataType) matches the (Sub)class of a given String type (should be passed using the class.getType() method)
	 * @param value
	 * @param type
	 * @return true if the Object matches the Sub(class).
	 */
	private Boolean isMetaObjectSubClass(IDataType value, String type) {
		String objectType = value.getObjectType();
		
		if(objectType == null) {
			return false;
		}
		
		IMetaObject metaObject = Core.getMetaObject(objectType);
		if (metaObject != null) {
			return metaObject.isSubClassOf(type);
		}
	
		return false;		
	}
	
	private String executeAndLogToolMicroflow(Map<String, Object> params) throws CoreException {
		String response;
		String logMessageInfo = "Finished toolcall " + ToolCall.getName() + " with Id " + ToolCall.getToolCallId() + " using microflow " + Tool.getMicroflow() + " with " + getContext();
		String logMessageTrace = logMessageInfo;
		if(params == null || params.isEmpty()) {
			logMessageTrace = logMessageTrace + "\nwithout input parameters ";
			response = Core.microflowCall(Tool.getMicroflow()).execute(getContext());
		} else {
			logMessageTrace = logMessageTrace +  "\n\nInput parameter(s):";
			logMessageTrace = logMessageTrace + getArgumentsString();
			logMessageTrace = logMessageTrace + params.toString();
			response = Core.microflowCall(Tool.getMicroflow()).withParams(params).execute(getContext());
		}
		
		long executionTime = System.currentTimeMillis() - startTime;
		String duration = "\n\nDuration:\n" + executionTime + "ms";
		LOGGER.info(logMessageInfo + duration);
		LOGGER.trace(logMessageTrace+ "\n\nReturn value:\n" + response + duration);
		return response;
	}
	
	/**
	 * Parses the Input JSON field from ToolCall and converts it to a list of Argument objects.
	 * This is used as a fallback when ToolCall_Argument association is empty.
	 */
	private List<Argument> parseArgumentsFromInput() {
		List<Argument> arguments = new ArrayList<>();
		String input = ToolCall.getInput();
		
		if (input == null || input.trim().isEmpty()) {
			return arguments;
		}
		
		try {
			JsonNode inputNode = MAPPER.readTree(input);
			if (inputNode != null && inputNode.isObject()) {
				Iterator<Map.Entry<String, JsonNode>> fields = inputNode.fields();
				while (fields.hasNext()) {
					Map.Entry<String, JsonNode> field = fields.next();
					Argument arg = new Argument(getContext());
					arg.setKey(field.getKey());
					// Convert value to string - handle different JSON types
					JsonNode valueNode = field.getValue();
					if (valueNode.isTextual()) {
						arg.setValue(valueNode.asText());
					} else {
						arg.setValue(valueNode.toString());
					}
					arguments.add(arg);
				}
			}
		} catch (Exception e) {
			LOGGER.warn("Failed to parse Input JSON for ToolCall: " + e.getMessage());
		}
		
		return arguments;
	}
	
	/**
	 * Gets a string of input arguments (passed by the model only)
	 * First tries to use ToolCall.getInput(), falls back to constructing from ToolCall_Argument
	 */
	private String getArgumentsString() throws CoreException {
		// First try to use the Input field directly if available
		String input = ToolCall.getInput();
		if (input != null && !input.trim().isEmpty()) {
			return "\n\n" + input;
		}
		
		// Fall back to constructing from argument list
		List<Argument> argumentList = ToolCall.getToolCall_Argument();
		if (argumentList == null || argumentList.isEmpty()) {
			return "";
		}
		
		String argumentString = "\n\n" + "{";
		for (int i = 0; i < argumentList.size(); i++) {
		    Argument arg = argumentList.get(i);
		    argumentString += arg.getKey() + "=" + arg.getValue();
		    if (i < argumentList.size() - 1) {
		        argumentString += ", ";
		    }
		}
		argumentString += "}";
		return argumentString;
	}
	// END EXTRA CODE
}
