// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import static java.util.Objects.requireNonNull;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import genaicommons.impl.MxLogger;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Tool_ExecuteMicroflow extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __Tool;
	private genaicommons.proxies.Tool Tool;
	private IMendixObject __Request;
	private genaicommons.proxies.Request Request;
	private java.lang.String Arguments;

	public Tool_ExecuteMicroflow(IContext context, IMendixObject Tool, IMendixObject Request, java.lang.String Arguments)
	{
		super(context);
		this.__Tool = Tool;
		this.__Request = Request;
		this.Arguments = Arguments;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.Tool = this.__Tool == null ? null : genaicommons.proxies.Tool.initialize(getContext(), __Tool);

		this.Request = this.__Request == null ? null : genaicommons.proxies.Request.initialize(getContext(), __Request);

		// BEGIN USER CODE
		try {
			requireNonNull(Tool, "Tool is required.");
			requireNonNull(Tool.getMicroflow(), "Tool has no Microflow.");
			
			return executeToolMicroflow();
		
		} catch (Exception e) {
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Tool_ExecuteMicroflow";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new genaicommons.impl.MxLogger(Tool_ExecuteMicroflow.class);

	private String executeToolMicroflow() throws Exception {		
		ObjectMapper mapper = new ObjectMapper();
		JsonNode rootNodeArguments = mapper.readTree(Arguments);
		Map<String, Object> parametersAndValues = new java.util.HashMap<>();
		//Iterate over input params
		Map<String, IDataType> parametersAndTypes = Core.getInputParameters(Tool.getMicroflow());
		for(Map.Entry<String, IDataType> entry : parametersAndTypes.entrySet()) {
			IDataType value = entry.getValue();
			String key = entry.getKey();
			
			if(IDataType.DataTypeEnum.String.equals(value.getType())) {
				JsonNode inputParamNode = rootNodeArguments.path(key);
				parametersAndValues.put(key, inputParamNode.asText());
			}
			else if (Core.getMetaObject(value.getObjectType()).isSubClassOf(genaicommons.proxies.Tool.getType())){
				parametersAndValues.put(key,  Tool.getMendixObject());
			}
			else if (Core.getMetaObject(value.getObjectType()).isSubClassOf(genaicommons.proxies.Request.getType())){
				parametersAndValues.put(key, Request.getMendixObject());
			}
		}
		return executeAndLogToolMicroflow(parametersAndValues);
	}
	
	private String executeAndLogToolMicroflow(Map<String, Object> params) {
		String response;
		String logMessageInfo = "Finished calling microflow " + Tool.getMicroflow() + " with " + getContext();
		String logMessageTrace = logMessageInfo;
		long startTime = System.currentTimeMillis();
		if(params == null || params.isEmpty()) {
			logMessageTrace = logMessageTrace + "\nwithout input parameters ";
			response = Core.microflowCall(Tool.getMicroflow()).execute(getContext());
		} else {
			logMessageTrace = logMessageTrace +  "\n\nInput parameter(s): " + params.toString();
			response = Core.microflowCall(Tool.getMicroflow()).withParams(params).execute(getContext());
		}
		long endTime = System.currentTimeMillis();
		long executionTime = endTime - startTime;
		String duration = "\n\nDuration:\n" + executionTime + "ms";
		LOGGER.info(logMessageInfo + duration);
		LOGGER.trace(logMessageTrace+ "\n\nReturn value:\n" + response + duration);
		return response;
	}
	
	// END EXTRA CODE
}
