// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package genaicommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class WriteToResponseStream extends UserAction<java.lang.Void>
{
	private final java.lang.String RequestId;
	private final java.lang.String Content;

	public WriteToResponseStream(
		IContext context,
		java.lang.String _requestId,
		java.lang.String _content
	)
	{
		super(context);
		this.RequestId = _requestId;
		this.Content = _content;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		genaicommons.impl.ResponseConnectionController.getInstance().getStreamingResponseWriter(RequestId).write(Content.getBytes());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "WriteToResponseStream";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
